.TH "common Directory Reference" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcommon\&.h\fP"
.br
.ti -1c
.RI "file \fBshader\&.cpp\fP"
.br
.ti -1c
.RI "file \fBshader\&.hpp\fP"
.br
.in -1c
