.TH "DerivedData/Build/Intermediates/BrainHarmonics.build/Debug/BrainHarmonics.build/Objects-normal Directory Reference" 3 "Tue Oct 10 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DerivedData/Build/Intermediates/BrainHarmonics.build/Debug/BrainHarmonics.build/Objects-normal Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBx86_64\fP"
.br
.in -1c
