.TH "opengl Directory Reference" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
opengl Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcommon\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBfirst_glfw\&.cpp\fP"
.br
.ti -1c
.RI "file \fBheightmap\&.c\fP"
.br
.ti -1c
.RI "file \fBhw\&.c\fP"
.br
.ti -1c
.RI "file \fBmainshader\&.cpp\fP"
.br
.ti -1c
.RI "file \fBpy_cmake\&.py\fP"
.br
.ti -1c
.RI "file \fBscrap\&.cpp\fP"
.br
.ti -1c
.RI "file \fBscrap\&.py\fP"
.br
.ti -1c
.RI "file \fBtransition_text\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtriangles\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtwod\&.cpp\fP"
.br
.ti -1c
.RI "file \fBwave\&.cpp\fP"
.br
.ti -1c
.RI "file \fBwaveback\&.c\fP"
.br
.in -1c
