.TH "BrainHarmonics/abstraction.cc" 3 "Tue Oct 10 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BrainHarmonics/abstraction.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'abstraction\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
