.TH "DerivedData/Build/Intermediates/BrainHarmonics.build/Debug/BrainHarmonics.build/Objects-normal/x86_64/abstraction.d" 3 "Tue Oct 10 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DerivedData/Build/Intermediates/BrainHarmonics.build/Debug/BrainHarmonics.build/Objects-normal/x86_64/abstraction.d
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
