.TH "Abstraction" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Abstraction
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <abstraction\&.h>\fP
.PP
Inherits \fBUniverse\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAbstraction\fP ()"
.br
.ti -1c
.RI "virtual \fB~Abstraction\fP ()"
.br
.ti -1c
.RI "unsigned int \fBGetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time, unsigned int \fBval\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 23 of file abstraction\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Abstraction::Abstraction ()"
Default constructor 
.SS "virtual Abstraction::~Abstraction ()\fC [virtual]\fP"
Default destructor 
.SH "Member Function Documentation"
.PP 
.SS "unsigned int Abstraction::GetCounter (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"
Access m_Counter 
.PP
\fBReturns:\fP
.RS 4
The current value of m_Counter 
.RE
.PP

.PP
Definition at line 33 of file abstraction\&.h\&.
.SS "\fBvoid\fP Abstraction::SetCounter (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)\fC [inline]\fP, \fC [virtual]\fP"
Set m_Counter 
.PP
\fBParameters:\fP
.RS 4
\fIval\fP New value to Set 
.RE
.PP

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 37 of file abstraction\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
