.TH "AxonBranch" 3 "Tue Oct 10 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AxonBranch
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <axonbranch\&.h>\fP
.PP
Inherits \fBAxon\fP\&.
.PP
Inherited by \fBAxonBouton\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAxonBranch\fP ()"
.br
.ti -1c
.RI "\fBAxonBranch\fP (unsigned int object_type)"
.br
.ti -1c
.RI "\fBAxonBranch\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBAxonBranch\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBAxon\fP &axon_connector)"
.br
.ti -1c
.RI "virtual \fB~AxonBranch\fP ()"
.br
.ti -1c
.RI "unsigned int \fBGetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "double \fBGetEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "void \fBSetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)"
.br
.ti -1c
.RI "void \fBSetEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time, double val)"
.br
.ti -1c
.RI "bool \fBResetParameters\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBAxonBranch\fP * \fBCreateAxonBouton\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "std::vector< \fBAxonBranch\fP * > \fBCreateAxonBoutons\fP (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"
.br
.ti -1c
.RI "\fBAxonBranch\fP * \fBCloneAxonBouton\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBAxonBranch\fP *clone_object, double perfection_membership)"
.br
.ti -1c
.RI "std::vector< \fBAxonBranch\fP * > \fBCloneAxonBoutons\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBAxonBranch\fP *> cloning_list, double perfection_membership)"
.br
.ti -1c
.RI "\fBAxonBranch\fP * \fBDestroyAxonBouton\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBAxonBranch\fP *destroy_object)"
.br
.ti -1c
.RI "std::vector< \fBAxonBranch\fP * > \fBDestroyAxonBoutons\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBAxonBranch\fP *> destruction_list)"
.br
.ti -1c
.RI "\fBAxonBranch\fP * \fBAddAxonBouton\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBAxonBranch\fP *add_object)"
.br
.ti -1c
.RI "std::vector< \fBAxonBranch\fP * > \fBAddAxonBoutons\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBAxonBranch\fP *> add_objects)"
.br
.ti -1c
.RI "\fBAxonBranch\fP * \fBRemoveAxonBouton\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "std::vector< \fBAxonBranch\fP * > \fBRemoveAxonBoutons\fP (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"
.br
.ti -1c
.RI "\fBAxonBranch\fP * \fBGetAxonBouton\fP (std::chrono::time_point< \fBClock\fP > event_time, int selector)"
.br
.ti -1c
.RI "std::vector< \fBAxonBranch\fP * > \fBGetAxonBoutons\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBGrowth\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBUpdate\fP (std::chrono::time_point< std::chrono::high_resolution_clock > val)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBAxonBranch\fP * > \fBaxonbouton_list\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file axonbranch\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AxonBranch::AxonBranch ()\fC [inline]\fP"

.PP
Definition at line 17 of file axonbranch\&.h\&.
.SS "AxonBranch::AxonBranch (unsigned int object_type)\fC [inline]\fP"

.PP
Definition at line 19 of file axonbranch\&.h\&.
.SS "AxonBranch::AxonBranch (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 21 of file axonbranch\&.h\&.
.SS "AxonBranch::AxonBranch (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBAxon\fP & axon_connector)\fC [inline]\fP"

.PP
Definition at line 23 of file axonbranch\&.h\&.
.SS "virtual AxonBranch::~AxonBranch ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 36 of file axonbranch\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBAxonBranch\fP * AxonBranch::AddAxonBouton (std::chrono::time_point< \fBClock\fP > event_time, \fBAxonBranch\fP * add_object)"

.PP
Definition at line 115 of file axonbranch\&.cc\&.
.SS "std::vector< \fBAxonBranch\fP * > AxonBranch::AddAxonBoutons (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBAxonBranch\fP *> add_objects)"

.PP
Definition at line 126 of file axonbranch\&.cc\&.
.SS "\fBAxonBranch\fP * AxonBranch::CloneAxonBouton (std::chrono::time_point< \fBClock\fP > event_time, \fBAxonBranch\fP * clone_object, double perfection_membership)"

.PP
Definition at line 100 of file axonbranch\&.cc\&.
.SS "std::vector< \fBAxonBranch\fP * > AxonBranch::CloneAxonBoutons (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBAxonBranch\fP *> cloning_list, double perfection_membership)"

.PP
Definition at line 95 of file axonbranch\&.cc\&.
.SS "\fBAxonBranch\fP * AxonBranch::CreateAxonBouton (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 62 of file axonbranch\&.cc\&.
.SS "std::vector< \fBAxonBranch\fP * > AxonBranch::CreateAxonBoutons (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"

.PP
Definition at line 73 of file axonbranch\&.cc\&.
.SS "\fBAxonBranch\fP * AxonBranch::DestroyAxonBouton (std::chrono::time_point< \fBClock\fP > event_time, \fBAxonBranch\fP * destroy_object)"

.PP
Definition at line 110 of file axonbranch\&.cc\&.
.SS "std::vector< \fBAxonBranch\fP * > AxonBranch::DestroyAxonBoutons (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBAxonBranch\fP *> destruction_list)"

.PP
Definition at line 105 of file axonbranch\&.cc\&.
.SS "\fBAxonBranch\fP * AxonBranch::GetAxonBouton (std::chrono::time_point< \fBClock\fP > event_time, int selector)"

.PP
Definition at line 159 of file axonbranch\&.cc\&.
.SS "std::vector< \fBAxonBranch\fP * > AxonBranch::GetAxonBoutons (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 164 of file axonbranch\&.cc\&.
.SS "unsigned int AxonBranch::GetCounter (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 37 of file axonbranch\&.h\&.
.SS "double AxonBranch::GetEnergy (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 38 of file axonbranch\&.h\&.
.SS "int AxonBranch::Growth (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 169 of file axonbranch\&.cc\&.
.SS "\fBAxonBranch\fP * AxonBranch::RemoveAxonBouton (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 148 of file axonbranch\&.cc\&.
.SS "std::vector< \fBAxonBranch\fP * > AxonBranch::RemoveAxonBoutons (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"

.PP
Definition at line 154 of file axonbranch\&.cc\&.
.SS "bool AxonBranch::ResetParameters (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 20 of file axonbranch\&.cc\&.
.SS "void AxonBranch::SetCounter (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBAxon\fP\&.
.PP
Reimplemented in \fBSynapticVesicle\fP\&.
.PP
Definition at line 39 of file axonbranch\&.h\&.
.SS "void AxonBranch::SetEnergy (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP"

.PP
Definition at line 40 of file axonbranch\&.h\&.
.SS "int AxonBranch::Update (std::chrono::time_point< std::chrono::high_resolution_clock > val)"

.PP
Definition at line 196 of file axonbranch\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBAxonBranch\fP*> AxonBranch::axonbouton_list\fC [protected]\fP"

.PP
Definition at line 72 of file axonbranch\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
