.TH "Axon" 3 "Tue Oct 10 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Axon
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <axon\&.h>\fP
.PP
Inherits \fBAxonHillock\fP\&.
.PP
Inherited by \fBAxonBranch\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAxon\fP ()"
.br
.ti -1c
.RI "\fBAxon\fP (unsigned int object_type)"
.br
.ti -1c
.RI "\fBAxon\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBAxon\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBAxonHillock\fP &axonhillock_connector)"
.br
.ti -1c
.RI "virtual \fB~Axon\fP ()"
.br
.ti -1c
.RI "unsigned int \fBGetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "double \fBGetEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "void \fBSetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)"
.br
.ti -1c
.RI "void \fBSetEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time, double val)"
.br
.ti -1c
.RI "bool \fBResetParameters\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBAxon\fP * \fBCreateAxonBranch\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "std::vector< \fBAxon\fP * > \fBCreateAxonBranches\fP (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"
.br
.ti -1c
.RI "\fBAxon\fP * \fBCloneAxonBranch\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBAxon\fP *clone_object, double perfection_membership)"
.br
.ti -1c
.RI "std::vector< \fBAxon\fP * > \fBCloneAxonBranches\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBAxon\fP *> cloning_list, double perfection_membership)"
.br
.ti -1c
.RI "\fBAxon\fP * \fBDestroyAxonBranch\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBAxon\fP *destroy_object)"
.br
.ti -1c
.RI "std::vector< \fBAxon\fP * > \fBDestroyAxonBranches\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBAxon\fP *> destruction_list)"
.br
.ti -1c
.RI "\fBAxon\fP * \fBAddAxonBranch\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBAxon\fP *add_object)"
.br
.ti -1c
.RI "std::vector< \fBAxon\fP * > \fBAddAxonBranches\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBAxon\fP *> add_objects)"
.br
.ti -1c
.RI "\fBAxon\fP * \fBRemoveAxonBranch\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "std::vector< \fBAxon\fP * > \fBRemoveAxonBranches\fP (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"
.br
.ti -1c
.RI "\fBAxon\fP * \fBGetAxonBranch\fP (std::chrono::time_point< \fBClock\fP > event_time, int selector)"
.br
.ti -1c
.RI "std::vector< \fBAxon\fP * > \fBGetAxonBranches\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBGrowth\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBUpdate\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBAxon\fP * > \fBaxonbranch_list\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file axon\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Axon::Axon ()\fC [inline]\fP"

.PP
Definition at line 17 of file axon\&.h\&.
.SS "Axon::Axon (unsigned int object_type)\fC [inline]\fP"

.PP
Definition at line 19 of file axon\&.h\&.
.SS "Axon::Axon (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 21 of file axon\&.h\&.
.SS "Axon::Axon (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBAxonHillock\fP & axonhillock_connector)\fC [inline]\fP"

.PP
Definition at line 23 of file axon\&.h\&.
.SS "virtual Axon::~Axon ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 36 of file axon\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBAxon\fP * Axon::AddAxonBranch (std::chrono::time_point< \fBClock\fP > event_time, \fBAxon\fP * add_object)"

.PP
Definition at line 115 of file axon\&.cc\&.
.SS "std::vector< \fBAxon\fP * > Axon::AddAxonBranches (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBAxon\fP *> add_objects)"

.PP
Definition at line 126 of file axon\&.cc\&.
.SS "\fBAxon\fP * Axon::CloneAxonBranch (std::chrono::time_point< \fBClock\fP > event_time, \fBAxon\fP * clone_object, double perfection_membership)"

.PP
Definition at line 100 of file axon\&.cc\&.
.SS "std::vector< \fBAxon\fP * > Axon::CloneAxonBranches (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBAxon\fP *> cloning_list, double perfection_membership)"

.PP
Definition at line 95 of file axon\&.cc\&.
.SS "\fBAxon\fP * Axon::CreateAxonBranch (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 62 of file axon\&.cc\&.
.SS "std::vector< \fBAxon\fP * > Axon::CreateAxonBranches (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"

.PP
Definition at line 73 of file axon\&.cc\&.
.SS "\fBAxon\fP * Axon::DestroyAxonBranch (std::chrono::time_point< \fBClock\fP > event_time, \fBAxon\fP * destroy_object)"

.PP
Definition at line 110 of file axon\&.cc\&.
.SS "std::vector< \fBAxon\fP * > Axon::DestroyAxonBranches (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBAxon\fP *> destruction_list)"

.PP
Definition at line 105 of file axon\&.cc\&.
.SS "\fBAxon\fP * Axon::GetAxonBranch (std::chrono::time_point< \fBClock\fP > event_time, int selector)"

.PP
Definition at line 159 of file axon\&.cc\&.
.SS "std::vector< \fBAxon\fP * > Axon::GetAxonBranches (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 164 of file axon\&.cc\&.
.SS "unsigned int Axon::GetCounter (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"
Access m_Counter 
.PP
\fBReturns:\fP
.RS 4
The current value of m_Counter 
.RE
.PP

.PP
Definition at line 40 of file axon\&.h\&.
.SS "double Axon::GetEnergy (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 41 of file axon\&.h\&.
.SS "int Axon::Growth (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 169 of file axon\&.cc\&.
.SS "\fBAxon\fP * Axon::RemoveAxonBranch (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 148 of file axon\&.cc\&.
.SS "std::vector< \fBAxon\fP * > Axon::RemoveAxonBranches (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"

.PP
Definition at line 154 of file axon\&.cc\&.
.SS "bool Axon::ResetParameters (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 20 of file axon\&.cc\&.
.SS "void Axon::SetCounter (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Reimplemented in \fBSynapticVesicle\fP, \fBAxonBouton\fP, and \fBAxonBranch\fP\&.
.PP
Definition at line 43 of file axon\&.h\&.
.SS "void Axon::SetEnergy (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP"

.PP
Definition at line 44 of file axon\&.h\&.
.SS "int Axon::Update (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 197 of file axon\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBAxon\fP*> Axon::axonbranch_list\fC [protected]\fP"

.PP
Definition at line 77 of file axon\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
