.TH "BrainHarmonics/axonbranch.cc" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BrainHarmonics/axonbranch.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'axonbranch\&.h'\fP
.br
\fC#include 'axonbouton\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
