.TH "CaGate" 3 "Sat Apr 29 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CaGate \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cagate\&.h>\fP
.PP
Inherits \fBAxonBouton\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCaGate\fP ()"
.br
.ti -1c
.RI "virtual \fB~CaGate\fP ()"
.br
.ti -1c
.RI "unsigned int \fBGetCounter\fP ()"
.br
.ti -1c
.RI "double \fBGetEnergy\fP ()"
.br
.ti -1c
.RI "void \fBSetCounter\fP (unsigned int val)"
.br
.ti -1c
.RI "void \fBSetEnergy\fP (double val)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file cagate\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CaGate::CaGate ()\fC [inline]\fP"
Default constructor 
.PP
Definition at line 19 of file cagate\&.h\&.
.SS "virtual CaGate::~CaGate ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 24 of file cagate\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "unsigned int CaGate::GetCounter ()\fC [inline]\fP"

.PP
Definition at line 25 of file cagate\&.h\&.
.SS "double CaGate::GetEnergy ()\fC [inline]\fP"

.PP
Definition at line 26 of file cagate\&.h\&.
.SS "void CaGate::SetCounter (unsigned int val)\fC [inline]\fP"

.PP
Definition at line 27 of file cagate\&.h\&.
.SS "void CaGate::SetEnergy (double val)\fC [inline]\fP"

.PP
Definition at line 28 of file cagate\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
