.TH "BrainHarmonics/build/CMakeFiles/CheckTypeSize/CMAKE_SIZEOF_UNSIGNED_SHORT.c" 3 "Tue Oct 10 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BrainHarmonics/build/CMakeFiles/CheckTypeSize/CMAKE_SIZEOF_UNSIGNED_SHORT.c
.SH SYNOPSIS
.br
.PP
\fC#include <sys/types\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSIZE\fP   (sizeof(unsigned short))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fBinfo_size\fP []"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SIZE   (sizeof(unsigned short))"

.PP
Definition at line 17 of file CMAKE_SIZEOF_UNSIGNED_SHORT\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 33 of file CMAKE_SIZEOF_UNSIGNED_SHORT\&.c\&.
.SH "Variable Documentation"
.PP 
.SS "char info_size[]"
\fBInitial value:\fP
.PP
.nf
=  {'I', 'N', 'F', 'O', ':', 's','i','z','e','[',
  ('0' + ((SIZE / 10000)%10)),
  ('0' + ((SIZE / 1000)%10)),
  ('0' + ((SIZE / 100)%10)),
  ('0' + ((SIZE / 10)%10)),
  ('0' +  (SIZE    % 10)),
  ']',



  '\0'}
.fi
.PP
Definition at line 18 of file CMAKE_SIZEOF_UNSIGNED_SHORT\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
