.TH "CognitiveOutput" 3 "Tue Oct 10 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CognitiveOutput
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cognitiveoutput\&.h>\fP
.PP
Inherits \fBCognitiveNetwork\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCognitiveOutput\fP ()"
.br
.ti -1c
.RI "\fBCognitiveOutput\fP (unsigned int object_type)"
.br
.ti -1c
.RI "\fBCognitiveOutput\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBCognitiveOutput\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBCognitiveNetwork\fP &cognitivenetwork_connector)"
.br
.ti -1c
.RI "virtual \fB~CognitiveOutput\fP ()"
.br
.ti -1c
.RI "unsigned int \fBGetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "double \fBGetEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBGetType\fP ()"
.br
.ti -1c
.RI "void \fBSetType\fP (int val)"
.br
.ti -1c
.RI "void \fBSetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)"
.br
.ti -1c
.RI "void \fBSetEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time, double val)"
.br
.ti -1c
.RI "double \fBTakeEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "bool \fBResetParameters\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBUpdate\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file cognitiveoutput\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CognitiveOutput::CognitiveOutput ()\fC [inline]\fP"

.PP
Definition at line 20 of file cognitiveoutput\&.h\&.
.SS "CognitiveOutput::CognitiveOutput (unsigned int object_type)\fC [inline]\fP"

.PP
Definition at line 22 of file cognitiveoutput\&.h\&.
.SS "CognitiveOutput::CognitiveOutput (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 24 of file cognitiveoutput\&.h\&.
.SS "CognitiveOutput::CognitiveOutput (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBCognitiveNetwork\fP & cognitivenetwork_connector)\fC [inline]\fP"

.PP
Definition at line 26 of file cognitiveoutput\&.h\&.
.SS "virtual CognitiveOutput::~CognitiveOutput ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 38 of file cognitiveoutput\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "unsigned int CognitiveOutput::GetCounter (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 40 of file cognitiveoutput\&.h\&.
.SS "double CognitiveOutput::GetEnergy (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 41 of file cognitiveoutput\&.h\&.
.SS "int CognitiveOutput::GetType ()\fC [inline]\fP"

.PP
Definition at line 42 of file cognitiveoutput\&.h\&.
.SS "bool CognitiveOutput::ResetParameters (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 19 of file cognitiveoutput\&.cc\&.
.SS "void CognitiveOutput::SetCounter (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 45 of file cognitiveoutput\&.h\&.
.SS "void CognitiveOutput::SetEnergy (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP"

.PP
Definition at line 46 of file cognitiveoutput\&.h\&.
.SS "void CognitiveOutput::SetType (int val)\fC [inline]\fP"

.PP
Definition at line 44 of file cognitiveoutput\&.h\&.
.SS "double CognitiveOutput::TakeEnergy (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 48 of file cognitiveoutput\&.h\&.
.SS "int CognitiveOutput::Update (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 66 of file cognitiveoutput\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
