.TH "CognitiveInput" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CognitiveInput
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cognitiveinput\&.h>\fP
.PP
Inherits \fBCognitiveNetwork\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCognitiveInput\fP ()"
.br
.ti -1c
.RI "\fBCognitiveInput\fP (unsigned int object_type)"
.br
.ti -1c
.RI "\fBCognitiveInput\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBCognitiveInput\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBCognitiveNetwork\fP &cognitivenetwork_connector)"
.br
.ti -1c
.RI "virtual \fB~CognitiveInput\fP ()"
.br
.ti -1c
.RI "unsigned int \fBGetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "double \fBGetEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBGetType\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetType\fP (std::chrono::time_point< \fBClock\fP > event_time, int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time, unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBAddEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP)"
.br
.ti -1c
.RI "bool \fBResetParameters\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBUpdate\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file cognitiveinput\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CognitiveInput::CognitiveInput ()\fC [inline]\fP"

.PP
Definition at line 20 of file cognitiveinput\&.h\&.
.SS "CognitiveInput::CognitiveInput (unsigned int object_type)\fC [inline]\fP"

.PP
Definition at line 22 of file cognitiveinput\&.h\&.
.SS "CognitiveInput::CognitiveInput (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 24 of file cognitiveinput\&.h\&.
.SS "CognitiveInput::CognitiveInput (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBCognitiveNetwork\fP & cognitivenetwork_connector)\fC [inline]\fP"

.PP
Definition at line 26 of file cognitiveinput\&.h\&.
.SS "virtual CognitiveInput::~CognitiveInput ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 38 of file cognitiveinput\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP CognitiveInput::AddEnergy (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP"

.PP
Definition at line 48 of file cognitiveinput\&.h\&.
.SS "unsigned int CognitiveInput::GetCounter (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 40 of file cognitiveinput\&.h\&.
.SS "double CognitiveInput::GetEnergy (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 41 of file cognitiveinput\&.h\&.
.SS "int CognitiveInput::GetType (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 42 of file cognitiveinput\&.h\&.
.SS "bool CognitiveInput::ResetParameters (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 19 of file cognitiveinput\&.cc\&.
.SS "\fBvoid\fP CognitiveInput::SetCounter (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 45 of file cognitiveinput\&.h\&.
.SS "\fBvoid\fP CognitiveInput::SetEnergy (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP"

.PP
Definition at line 46 of file cognitiveinput\&.h\&.
.SS "\fBvoid\fP CognitiveInput::SetType (std::chrono::time_point< \fBClock\fP > event_time, int val)\fC [inline]\fP"

.PP
Definition at line 44 of file cognitiveinput\&.h\&.
.SS "int CognitiveInput::Update (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 59 of file cognitiveinput\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
