.TH "DendriteCleft" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DendriteCleft
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dendritecleft\&.h>\fP
.PP
Inherits \fBDendriteBranch\fP\&.
.PP
Inherited by \fBNeuroreceptor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDendriteCleft\fP ()"
.br
.ti -1c
.RI "\fBDendriteCleft\fP (unsigned int object_type)"
.br
.ti -1c
.RI "\fBDendriteCleft\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBDendriteCleft\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBDendriteBranch\fP &dendritebranch_connector)"
.br
.ti -1c
.RI "virtual \fB~DendriteCleft\fP ()"
.br
.ti -1c
.RI "unsigned int \fBGetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "double \fBGetEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time, unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP)"
.br
.ti -1c
.RI "bool \fBResetParameters\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBDendriteCleft\fP * \fBCreateNeuroreceptor\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "std::vector< \fBDendriteCleft\fP * > \fBCreateNeuroreceptors\fP (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"
.br
.ti -1c
.RI "\fBDendriteCleft\fP * \fBCloneNeuroreceptor\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBDendriteCleft\fP *clone_object, double perfection_membership)"
.br
.ti -1c
.RI "std::vector< \fBDendriteCleft\fP * > \fBCloneNeuroreceptors\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBDendriteCleft\fP *> cloning_list, double perfection_membership)"
.br
.ti -1c
.RI "\fBDendriteCleft\fP * \fBDestroyNeuroreceptor\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBDendriteCleft\fP *destroy_object)"
.br
.ti -1c
.RI "std::vector< \fBDendriteCleft\fP * > \fBDestroyNeuroreceptors\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBDendriteCleft\fP *> destruction_list)"
.br
.ti -1c
.RI "\fBDendriteCleft\fP * \fBAddNeuroreceptor\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBDendriteCleft\fP *add_object)"
.br
.ti -1c
.RI "std::vector< \fBDendriteCleft\fP * > \fBAddNeuroreceptors\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBDendriteCleft\fP *> add_objects)"
.br
.ti -1c
.RI "\fBDendriteCleft\fP * \fBRemoveNeuroreceptor\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "std::vector< \fBDendriteCleft\fP * > \fBRemoveNeuroreceptors\fP (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"
.br
.ti -1c
.RI "\fBDendriteCleft\fP * \fBGetNeuroreceptor\fP (std::chrono::time_point< \fBClock\fP > event_time, int selector)"
.br
.ti -1c
.RI "std::vector< \fBDendriteCleft\fP * > \fBGetNeuroreceptors\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBGrowthSurface\fP (std::chrono::time_point< \fBClock\fP > event_time, double surf_change)"
.br
.ti -1c
.RI "int \fBGrowthVolume\fP (std::chrono::time_point< \fBClock\fP > event_time, double vol_change)"
.br
.ti -1c
.RI "int \fBUpdate\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBDendriteCleft\fP * > \fBneuroreceptor_list\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file dendritecleft\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DendriteCleft::DendriteCleft ()\fC [inline]\fP"

.PP
Definition at line 17 of file dendritecleft\&.h\&.
.SS "DendriteCleft::DendriteCleft (unsigned int object_type)\fC [inline]\fP"

.PP
Definition at line 19 of file dendritecleft\&.h\&.
.SS "DendriteCleft::DendriteCleft (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 21 of file dendritecleft\&.h\&.
.SS "DendriteCleft::DendriteCleft (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBDendriteBranch\fP & dendritebranch_connector)\fC [inline]\fP"

.PP
Definition at line 23 of file dendritecleft\&.h\&.
.SS "virtual DendriteCleft::~DendriteCleft ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 36 of file dendritecleft\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBDendriteCleft\fP * DendriteCleft::AddNeuroreceptor (std::chrono::time_point< \fBClock\fP > event_time, \fBDendriteCleft\fP * add_object)"

.PP
Definition at line 132 of file dendritecleft\&.cc\&.
.SS "std::vector< \fBDendriteCleft\fP * > DendriteCleft::AddNeuroreceptors (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBDendriteCleft\fP *> add_objects)"

.PP
Definition at line 143 of file dendritecleft\&.cc\&.
.SS "\fBDendriteCleft\fP * DendriteCleft::CloneNeuroreceptor (std::chrono::time_point< \fBClock\fP > event_time, \fBDendriteCleft\fP * clone_object, double perfection_membership)"

.PP
Definition at line 117 of file dendritecleft\&.cc\&.
.SS "std::vector< \fBDendriteCleft\fP * > DendriteCleft::CloneNeuroreceptors (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBDendriteCleft\fP *> cloning_list, double perfection_membership)"

.PP
Definition at line 112 of file dendritecleft\&.cc\&.
.SS "\fBDendriteCleft\fP * DendriteCleft::CreateNeuroreceptor (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 79 of file dendritecleft\&.cc\&.
.SS "std::vector< \fBDendriteCleft\fP * > DendriteCleft::CreateNeuroreceptors (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"

.PP
Definition at line 90 of file dendritecleft\&.cc\&.
.SS "\fBDendriteCleft\fP * DendriteCleft::DestroyNeuroreceptor (std::chrono::time_point< \fBClock\fP > event_time, \fBDendriteCleft\fP * destroy_object)"

.PP
Definition at line 127 of file dendritecleft\&.cc\&.
.SS "std::vector< \fBDendriteCleft\fP * > DendriteCleft::DestroyNeuroreceptors (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBDendriteCleft\fP *> destruction_list)"

.PP
Definition at line 122 of file dendritecleft\&.cc\&.
.SS "unsigned int DendriteCleft::GetCounter (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 38 of file dendritecleft\&.h\&.
.SS "double DendriteCleft::GetEnergy (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 39 of file dendritecleft\&.h\&.
.SS "\fBDendriteCleft\fP * DendriteCleft::GetNeuroreceptor (std::chrono::time_point< \fBClock\fP > event_time, int selector)"

.PP
Definition at line 176 of file dendritecleft\&.cc\&.
.SS "std::vector< \fBDendriteCleft\fP * > DendriteCleft::GetNeuroreceptors (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 181 of file dendritecleft\&.cc\&.
.SS "int DendriteCleft::GrowthSurface (std::chrono::time_point< \fBClock\fP > event_time, double surf_change)"

.PP
Definition at line 187 of file dendritecleft\&.cc\&.
.SS "int DendriteCleft::GrowthVolume (std::chrono::time_point< \fBClock\fP > event_time, double vol_change)"

.PP
Definition at line 194 of file dendritecleft\&.cc\&.
.SS "\fBDendriteCleft\fP * DendriteCleft::RemoveNeuroreceptor (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 165 of file dendritecleft\&.cc\&.
.SS "std::vector< \fBDendriteCleft\fP * > DendriteCleft::RemoveNeuroreceptors (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"

.PP
Definition at line 171 of file dendritecleft\&.cc\&.
.SS "bool DendriteCleft::ResetParameters (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 20 of file dendritecleft\&.cc\&.
.SS "\fBvoid\fP DendriteCleft::SetCounter (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBDendriteBranch\fP\&.
.PP
Reimplemented in \fBNeuroreceptor\fP\&.
.PP
Definition at line 40 of file dendritecleft\&.h\&.
.SS "\fBvoid\fP DendriteCleft::SetEnergy (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP"

.PP
Definition at line 41 of file dendritecleft\&.h\&.
.SS "int DendriteCleft::Update (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 202 of file dendritecleft\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBDendriteCleft\fP*> DendriteCleft::neuroreceptor_list\fC [protected]\fP"

.PP
Definition at line 76 of file dendritecleft\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
