.TH "DendriteBranch" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DendriteBranch
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dendritebranch\&.h>\fP
.PP
Inherits \fBDendrite\fP\&.
.PP
Inherited by \fBDendriteCleft\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDendriteBranch\fP ()"
.br
.ti -1c
.RI "\fBDendriteBranch\fP (unsigned int object_type)"
.br
.ti -1c
.RI "\fBDendriteBranch\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBDendriteBranch\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBDendrite\fP &dendrite_connector)"
.br
.ti -1c
.RI "virtual \fB~DendriteBranch\fP ()"
.br
.ti -1c
.RI "unsigned int \fBGetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "double \fBGetEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time, unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP)"
.br
.ti -1c
.RI "bool \fBResetParameters\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBDendriteBranch\fP * \fBCreateDendriteCleft\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "std::vector< \fBDendriteBranch\fP * > \fBCreateDendriteClefts\fP (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"
.br
.ti -1c
.RI "\fBDendriteBranch\fP * \fBCloneDendriteCleft\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBDendriteBranch\fP *clone_object, double perfection_membership)"
.br
.ti -1c
.RI "std::vector< \fBDendriteBranch\fP * > \fBCloneDendriteClefts\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBDendriteBranch\fP *> cloning_list, double perfection_membership)"
.br
.ti -1c
.RI "\fBDendriteBranch\fP * \fBDestroyDendriteCleft\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBDendriteBranch\fP *destroy_object)"
.br
.ti -1c
.RI "std::vector< \fBDendriteBranch\fP * > \fBDestroyDendriteClefts\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBDendriteBranch\fP *> destruction_list)"
.br
.ti -1c
.RI "\fBDendriteBranch\fP * \fBAddDendriteCleft\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBDendriteBranch\fP *add_object)"
.br
.ti -1c
.RI "std::vector< \fBDendriteBranch\fP * > \fBAddDendriteClefts\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBDendriteBranch\fP *> add_objects)"
.br
.ti -1c
.RI "\fBDendriteBranch\fP * \fBRemoveDendriteCleft\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "std::vector< \fBDendriteBranch\fP * > \fBRemoveDendriteClefts\fP (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"
.br
.ti -1c
.RI "\fBDendriteBranch\fP * \fBGetDendriteCleft\fP (std::chrono::time_point< \fBClock\fP > event_time, int selector)"
.br
.ti -1c
.RI "std::vector< \fBDendriteBranch\fP * > \fBGetDendriteClefts\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBGrowth\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBUpdate\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBDendriteBranch\fP * > \fBdendritecleft_list\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file dendritebranch\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DendriteBranch::DendriteBranch ()\fC [inline]\fP"

.PP
Definition at line 17 of file dendritebranch\&.h\&.
.SS "DendriteBranch::DendriteBranch (unsigned int object_type)\fC [inline]\fP"

.PP
Definition at line 19 of file dendritebranch\&.h\&.
.SS "DendriteBranch::DendriteBranch (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 21 of file dendritebranch\&.h\&.
.SS "DendriteBranch::DendriteBranch (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBDendrite\fP & dendrite_connector)\fC [inline]\fP"

.PP
Definition at line 23 of file dendritebranch\&.h\&.
.SS "virtual DendriteBranch::~DendriteBranch ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 36 of file dendritebranch\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBDendriteBranch\fP * DendriteBranch::AddDendriteCleft (std::chrono::time_point< \fBClock\fP > event_time, \fBDendriteBranch\fP * add_object)"

.PP
Definition at line 119 of file dendritebranch\&.cc\&.
.SS "std::vector< \fBDendriteBranch\fP * > DendriteBranch::AddDendriteClefts (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBDendriteBranch\fP *> add_objects)"

.PP
Definition at line 130 of file dendritebranch\&.cc\&.
.SS "\fBDendriteBranch\fP * DendriteBranch::CloneDendriteCleft (std::chrono::time_point< \fBClock\fP > event_time, \fBDendriteBranch\fP * clone_object, double perfection_membership)"

.PP
Definition at line 104 of file dendritebranch\&.cc\&.
.SS "std::vector< \fBDendriteBranch\fP * > DendriteBranch::CloneDendriteClefts (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBDendriteBranch\fP *> cloning_list, double perfection_membership)"

.PP
Definition at line 99 of file dendritebranch\&.cc\&.
.SS "\fBDendriteBranch\fP * DendriteBranch::CreateDendriteCleft (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 66 of file dendritebranch\&.cc\&.
.SS "std::vector< \fBDendriteBranch\fP * > DendriteBranch::CreateDendriteClefts (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"

.PP
Definition at line 77 of file dendritebranch\&.cc\&.
.SS "\fBDendriteBranch\fP * DendriteBranch::DestroyDendriteCleft (std::chrono::time_point< \fBClock\fP > event_time, \fBDendriteBranch\fP * destroy_object)"

.PP
Definition at line 114 of file dendritebranch\&.cc\&.
.SS "std::vector< \fBDendriteBranch\fP * > DendriteBranch::DestroyDendriteClefts (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBDendriteBranch\fP *> destruction_list)"

.PP
Definition at line 109 of file dendritebranch\&.cc\&.
.SS "unsigned int DendriteBranch::GetCounter (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 38 of file dendritebranch\&.h\&.
.SS "\fBDendriteBranch\fP * DendriteBranch::GetDendriteCleft (std::chrono::time_point< \fBClock\fP > event_time, int selector)"

.PP
Definition at line 163 of file dendritebranch\&.cc\&.
.SS "std::vector< \fBDendriteBranch\fP * > DendriteBranch::GetDendriteClefts (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 168 of file dendritebranch\&.cc\&.
.SS "double DendriteBranch::GetEnergy (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 39 of file dendritebranch\&.h\&.
.SS "int DendriteBranch::Growth (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 173 of file dendritebranch\&.cc\&.
.SS "\fBDendriteBranch\fP * DendriteBranch::RemoveDendriteCleft (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 152 of file dendritebranch\&.cc\&.
.SS "std::vector< \fBDendriteBranch\fP * > DendriteBranch::RemoveDendriteClefts (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"

.PP
Definition at line 158 of file dendritebranch\&.cc\&.
.SS "bool DendriteBranch::ResetParameters (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 20 of file dendritebranch\&.cc\&.
.SS "\fBvoid\fP DendriteBranch::SetCounter (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBDendrite\fP\&.
.PP
Reimplemented in \fBNeuroreceptor\fP, and \fBDendriteCleft\fP\&.
.PP
Definition at line 41 of file dendritebranch\&.h\&.
.SS "\fBvoid\fP DendriteBranch::SetEnergy (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP"

.PP
Definition at line 42 of file dendritebranch\&.h\&.
.SS "int DendriteBranch::Update (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 197 of file dendritebranch\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBDendriteBranch\fP*> DendriteBranch::dendritecleft_list\fC [protected]\fP"

.PP
Definition at line 75 of file dendritebranch\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
