.TH "BrainHarmonics/dendritecleft.cc" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BrainHarmonics/dendritecleft.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'dendritecleft\&.h'\fP
.br
\fC#include 'neuroreceptor\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
