.TH "Dendrite" 3 "Tue Oct 10 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dendrite
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dendrite\&.h>\fP
.PP
Inherits \fBSoma\fP\&.
.PP
Inherited by \fBDendriteBranch\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDendrite\fP ()"
.br
.ti -1c
.RI "\fBDendrite\fP (unsigned int object_type)"
.br
.ti -1c
.RI "\fBDendrite\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBDendrite\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBSoma\fP &soma_connector)"
.br
.ti -1c
.RI "virtual \fB~Dendrite\fP ()"
.br
.ti -1c
.RI "unsigned int \fBGetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "double \fBGetEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "double \fBGetDendriteLength\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "double \fBGetDendriteDiameterStart\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "double \fBGetDendriteDiameterEnd\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "double \fBGetMembraneResistance\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "double \fBGetMembraneCapacitance\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "double \fBGetInternalResistance\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "double \fBGetPropagationVelocity\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "void \fBsetDendriteLength\fP (std::chrono::time_point< \fBClock\fP > event_time, double val)"
.br
.ti -1c
.RI "void \fBsetDendriteDiameterStart\fP (std::chrono::time_point< \fBClock\fP > event_time, double val)"
.br
.ti -1c
.RI "void \fBsetDendriteDiameterEnd\fP (std::chrono::time_point< \fBClock\fP > event_time, double val)"
.br
.ti -1c
.RI "void \fBsetMembraneResistance\fP (std::chrono::time_point< \fBClock\fP > event_time, double val)"
.br
.ti -1c
.RI "void \fBsetMembraneCapacitance\fP (std::chrono::time_point< \fBClock\fP > event_time, double val)"
.br
.ti -1c
.RI "void \fBsetInternalResistance\fP (std::chrono::time_point< \fBClock\fP > event_time, double val)"
.br
.ti -1c
.RI "void \fBSetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)"
.br
.ti -1c
.RI "void \fBSetEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time, double val)"
.br
.ti -1c
.RI "bool \fBResetParameters\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBDendrite\fP * \fBCreateDendriteBranch\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "std::vector< \fBDendrite\fP * > \fBCreateDendriteBranches\fP (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"
.br
.ti -1c
.RI "\fBDendrite\fP * \fBCloneDendriteBranch\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBDendrite\fP *clone_object, double perfection_membership)"
.br
.ti -1c
.RI "std::vector< \fBDendrite\fP * > \fBCloneDendriteBranches\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBDendrite\fP *> cloning_list, double perfection_membership)"
.br
.ti -1c
.RI "\fBDendrite\fP * \fBDestroyDendriteBranch\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBDendrite\fP *destroy_object)"
.br
.ti -1c
.RI "std::vector< \fBDendrite\fP * > \fBDestroyDendriteBranches\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBDendrite\fP *> destruction_list)"
.br
.ti -1c
.RI "\fBDendrite\fP * \fBAddDendriteBranch\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBDendrite\fP *add_object)"
.br
.ti -1c
.RI "std::vector< \fBDendrite\fP * > \fBAddDendriteBranches\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBDendrite\fP *> add_objects)"
.br
.ti -1c
.RI "\fBDendrite\fP * \fBRemoveDendriteBranch\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "std::vector< \fBDendrite\fP * > \fBRemoveDendriteBranches\fP (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"
.br
.ti -1c
.RI "\fBDendrite\fP * \fBGetDendriteBranch\fP (std::chrono::time_point< \fBClock\fP > event_time, int selector)"
.br
.ti -1c
.RI "std::vector< \fBDendrite\fP * > \fBGetDendriteBranches\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBGrowth\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBUpdate\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBDendrite\fP * > \fBdendritebranch_list\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 14 of file dendrite\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Dendrite::Dendrite ()\fC [inline]\fP"

.PP
Definition at line 17 of file dendrite\&.h\&.
.SS "Dendrite::Dendrite (unsigned int object_type)\fC [inline]\fP"

.PP
Definition at line 19 of file dendrite\&.h\&.
.SS "Dendrite::Dendrite (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 21 of file dendrite\&.h\&.
.SS "Dendrite::Dendrite (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBSoma\fP & soma_connector)\fC [inline]\fP"

.PP
Definition at line 23 of file dendrite\&.h\&.
.SS "virtual Dendrite::~Dendrite ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 37 of file dendrite\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBDendrite\fP * Dendrite::AddDendriteBranch (std::chrono::time_point< \fBClock\fP > event_time, \fBDendrite\fP * add_object)"

.PP
Definition at line 119 of file dendrite\&.cc\&.
.SS "std::vector< \fBDendrite\fP * > Dendrite::AddDendriteBranches (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBDendrite\fP *> add_objects)"

.PP
Definition at line 130 of file dendrite\&.cc\&.
.SS "\fBDendrite\fP * Dendrite::CloneDendriteBranch (std::chrono::time_point< \fBClock\fP > event_time, \fBDendrite\fP * clone_object, double perfection_membership)"

.PP
Definition at line 104 of file dendrite\&.cc\&.
.SS "std::vector< \fBDendrite\fP * > Dendrite::CloneDendriteBranches (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBDendrite\fP *> cloning_list, double perfection_membership)"

.PP
Definition at line 99 of file dendrite\&.cc\&.
.SS "\fBDendrite\fP * Dendrite::CreateDendriteBranch (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 66 of file dendrite\&.cc\&.
.SS "std::vector< \fBDendrite\fP * > Dendrite::CreateDendriteBranches (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"

.PP
Definition at line 77 of file dendrite\&.cc\&.
.SS "\fBDendrite\fP * Dendrite::DestroyDendriteBranch (std::chrono::time_point< \fBClock\fP > event_time, \fBDendrite\fP * destroy_object)"

.PP
Definition at line 114 of file dendrite\&.cc\&.
.SS "std::vector< \fBDendrite\fP * > Dendrite::DestroyDendriteBranches (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBDendrite\fP *> destruction_list)"

.PP
Definition at line 109 of file dendrite\&.cc\&.
.SS "unsigned int Dendrite::GetCounter (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 39 of file dendrite\&.h\&.
.SS "\fBDendrite\fP * Dendrite::GetDendriteBranch (std::chrono::time_point< \fBClock\fP > event_time, int selector)"

.PP
Definition at line 163 of file dendrite\&.cc\&.
.SS "std::vector< \fBDendrite\fP * > Dendrite::GetDendriteBranches (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 168 of file dendrite\&.cc\&.
.SS "double Dendrite::GetDendriteDiameterEnd (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 43 of file dendrite\&.h\&.
.SS "double Dendrite::GetDendriteDiameterStart (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 42 of file dendrite\&.h\&.
.SS "double Dendrite::GetDendriteLength (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 41 of file dendrite\&.h\&.
.SS "double Dendrite::GetEnergy (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 40 of file dendrite\&.h\&.
.SS "double Dendrite::GetInternalResistance (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 46 of file dendrite\&.h\&.
.SS "double Dendrite::GetMembraneCapacitance (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 45 of file dendrite\&.h\&.
.SS "double Dendrite::GetMembraneResistance (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 44 of file dendrite\&.h\&.
.SS "double Dendrite::GetPropagationVelocity (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 47 of file dendrite\&.h\&.
.SS "int Dendrite::Growth (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 173 of file dendrite\&.cc\&.
.SS "\fBDendrite\fP * Dendrite::RemoveDendriteBranch (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 152 of file dendrite\&.cc\&.
.SS "std::vector< \fBDendrite\fP * > Dendrite::RemoveDendriteBranches (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"

.PP
Definition at line 158 of file dendrite\&.cc\&.
.SS "bool Dendrite::ResetParameters (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 20 of file dendrite\&.cc\&.
.SS "void Dendrite::SetCounter (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Reimplemented in \fBNeuroreceptor\fP, \fBDendriteBranch\fP, and \fBDendriteCleft\fP\&.
.PP
Definition at line 56 of file dendrite\&.h\&.
.SS "void Dendrite::setDendriteDiameterEnd (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP"

.PP
Definition at line 52 of file dendrite\&.h\&.
.SS "void Dendrite::setDendriteDiameterStart (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP"

.PP
Definition at line 51 of file dendrite\&.h\&.
.SS "void Dendrite::setDendriteLength (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP"

.PP
Definition at line 50 of file dendrite\&.h\&.
.SS "void Dendrite::SetEnergy (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP"

.PP
Definition at line 57 of file dendrite\&.h\&.
.SS "void Dendrite::setInternalResistance (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP"

.PP
Definition at line 55 of file dendrite\&.h\&.
.SS "void Dendrite::setMembraneCapacitance (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP"

.PP
Definition at line 54 of file dendrite\&.h\&.
.SS "void Dendrite::setMembraneResistance (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP"

.PP
Definition at line 53 of file dendrite\&.h\&.
.SS "int Dendrite::Update (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 197 of file dendrite\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBDendrite\fP*> Dendrite::dendritebranch_list\fC [protected]\fP"

.PP
Definition at line 90 of file dendrite\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
