.TH "Dimension::CounterAdjustment" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dimension::CounterAdjustment
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dimension\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCounterAdjustment\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::chrono::time_point< \fBClock\fP > \fBcounter_begin\fP"
.br
.ti -1c
.RI "std::chrono::time_point< \fBClock\fP > \fBcounter_last_update\fP"
.br
.ti -1c
.RI "std::chrono::time_point< \fBClock\fP > \fBcounter_end\fP"
.br
.ti -1c
.RI "double * \fBpoint_to_counter\fP"
.br
.ti -1c
.RI "double \fBpool\fP"
.br
.ti -1c
.RI "int \fBinterval\fP"
.br
.ti -1c
.RI "int \fBshape\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 60 of file dimension\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Dimension::CounterAdjustment::CounterAdjustment ()\fC [inline]\fP"

.PP
Definition at line 62 of file dimension\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::chrono::time_point<\fBClock\fP> Dimension::CounterAdjustment::counter_begin"

.PP
Definition at line 63 of file dimension\&.h\&.
.SS "std::chrono::time_point<\fBClock\fP> Dimension::CounterAdjustment::counter_end"

.PP
Definition at line 65 of file dimension\&.h\&.
.SS "std::chrono::time_point<\fBClock\fP> Dimension::CounterAdjustment::counter_last_update"

.PP
Definition at line 64 of file dimension\&.h\&.
.SS "int Dimension::CounterAdjustment::interval"

.PP
Definition at line 68 of file dimension\&.h\&.
.SS "double* Dimension::CounterAdjustment::point_to_counter"

.PP
Definition at line 66 of file dimension\&.h\&.
.SS "double Dimension::CounterAdjustment::pool"

.PP
Definition at line 67 of file dimension\&.h\&.
.SS "int Dimension::CounterAdjustment::shape"

.PP
Definition at line 69 of file dimension\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
