.TH "Dimension" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Dimension
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <dimension\&.h>\fP
.PP
Inherits \fBUniverse\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCounterAdjustment\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDimension\fP ()"
.br
.ti -1c
.RI "\fBDimension\fP (unsigned int object_type)"
.br
.ti -1c
.RI "\fBDimension\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBDimension\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBUniverse\fP &universe_connector)"
.br
.ti -1c
.RI "virtual \fB~Dimension\fP ()"
.br
.ti -1c
.RI "unsigned int \fBGetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "double \fBGetScale\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "double \fBGetOffset\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "std::chrono::time_point< std::chrono::high_resolution_clock > \fBTheTimeNow\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time, unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetScale\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetTime\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetOffset\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBIncScale\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBDecScale\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBIncTime\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBDecTime\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBIncOffset\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBDecOffset\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetObjectType\fP (std::chrono::time_point< \fBClock\fP > event_time, int \fBval\fP)"
.br
.ti -1c
.RI "int \fBGetObjectType\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "bool \fBResetParameters\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBvoid\fP \fBAdjustCounters\fP (std::chrono::time_point< std::chrono::high_resolution_clock > currentTime)"
.br
.ti -1c
.RI "int \fBUpdate\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetCharge\fP (std::chrono::time_point< \fBClock\fP > event_time, int \fBval\fP) final"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetSpin\fP (std::chrono::time_point< \fBClock\fP > event_time, int \fBval\fP) final"
.br
.ti -1c
.RI "double \fBGetGravitation\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBGetWeak\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBGetWeakElectroweak\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBGetElectromagnetic\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBGetElectromagneticElectroweak\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBGetStrong\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBGetStrongFundamental\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBGetStrongResidual\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBApplyGravitation\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "double \fBApplyWeak\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "double \fBApplyWeakElectroweak\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "double \fBApplyElectromagnetic\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "double \fBApplyElectromagneticElectroweak\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "double \fBApplyStrong\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "double \fBApplyStrongFundamental\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "double \fBApplyStrongResidual\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetGravitation\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetWeak\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetWeakElectroweak\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetElectromagnetic\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetElectromagneticElectroweak\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetStrong\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetStrongFundamental\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetStrongResidual\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "\fBvoid\fP \fBPollElementaryForce\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBCounterAdjustment\fP * > \fBtemporal_adjustment_list\fP"
.br
.ti -1c
.RI "int \fBduration_since_last_event\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "double \fBscale_time\fP"
.br
.ti -1c
.RI "std::chrono::time_point< \fBClock\fP > \fBtime_object_created\fP"
.br
.RI "Member variable 'time_object_created'\&. "
.ti -1c
.RI "std::chrono::time_point< \fBClock\fP > \fBobjectExpiration\fP"
.br
.RI "Member variable 'objectExpiration'\&. "
.ti -1c
.RI "std::chrono::time_point< \fBClock\fP > \fBobjectLifespan\fP"
.br
.RI "Member variable 'objectLifespan'\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBCognitiveNetwork\fP"
.br
.ti -1c
.RI "class \fBCompositeForce\fP"
.br
.ti -1c
.RI "class \fBCompositeParticle\fP"
.br
.ti -1c
.RI "class \fBElementaryForce\fP"
.br
.ti -1c
.RI "class \fBElementaryParticle\fP"
.br
.ti -1c
.RI "class \fBMatter\fP"
.br
.ti -1c
.RI "class \fBMembrane\fP"
.br
.ti -1c
.RI "class \fBMonomer\fP"
.br
.ti -1c
.RI "class \fBNeuron\fP"
.br
.ti -1c
.RI "class \fBPolymer\fP"
.br
.ti -1c
.RI "class \fBPoint\fP"
.br
.ti -1c
.RI "class \fBSolid\fP"
.br
.ti -1c
.RI "class \fBSoma\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file dimension\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Dimension::Dimension ()\fC [inline]\fP"

.PP
Definition at line 42 of file dimension\&.h\&.
.SS "Dimension::Dimension (unsigned int object_type)\fC [inline]\fP"

.PP
Definition at line 44 of file dimension\&.h\&.
.SS "Dimension::Dimension (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 46 of file dimension\&.h\&.
.SS "Dimension::Dimension (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBUniverse\fP & universe_connector)\fC [inline]\fP"

.PP
Definition at line 48 of file dimension\&.h\&.
.SS "virtual Dimension::~Dimension ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 56 of file dimension\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP Dimension::AdjustCounters (std::chrono::time_point< std::chrono::high_resolution_clock > currentTime)\fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 121 of file dimension\&.cc\&.
.SS "double Dimension::ApplyElectromagnetic (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 129 of file dimension\&.h\&.
.SS "double Dimension::ApplyElectromagneticElectroweak (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 130 of file dimension\&.h\&.
.SS "double Dimension::ApplyGravitation (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 126 of file dimension\&.h\&.
.SS "double Dimension::ApplyStrong (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 131 of file dimension\&.h\&.
.SS "double Dimension::ApplyStrongFundamental (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 132 of file dimension\&.h\&.
.SS "double Dimension::ApplyStrongResidual (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 133 of file dimension\&.h\&.
.SS "double Dimension::ApplyWeak (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 127 of file dimension\&.h\&.
.SS "double Dimension::ApplyWeakElectroweak (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 128 of file dimension\&.h\&.
.SS "\fBvoid\fP Dimension::DecOffset (std::chrono::time_point< \fBClock\fP > event_time, double val)"

.PP
Definition at line 55 of file dimension\&.cc\&.
.SS "\fBvoid\fP Dimension::DecScale (std::chrono::time_point< \fBClock\fP > event_time, double val)"

.PP
Definition at line 35 of file dimension\&.cc\&.
.SS "\fBvoid\fP Dimension::DecTime (std::chrono::time_point< \fBClock\fP > event_time, double val)"

.PP
Definition at line 47 of file dimension\&.cc\&.
.SS "unsigned int Dimension::GetCounter (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 75 of file dimension\&.h\&.
.SS "double Dimension::GetElectromagnetic (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 120 of file dimension\&.h\&.
.SS "double Dimension::GetElectromagneticElectroweak (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 121 of file dimension\&.h\&.
.SS "double Dimension::GetGravitation (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 117 of file dimension\&.h\&.
.SS "int Dimension::GetObjectType (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 107 of file dimension\&.h\&.
.SS "double Dimension::GetOffset (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 79 of file dimension\&.h\&.
.SS "double Dimension::GetScale (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 77 of file dimension\&.h\&.
.SS "double Dimension::GetStrong (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 122 of file dimension\&.h\&.
.SS "double Dimension::GetStrongFundamental (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 123 of file dimension\&.h\&.
.SS "double Dimension::GetStrongResidual (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 124 of file dimension\&.h\&.
.SS "double Dimension::GetWeak (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 118 of file dimension\&.h\&.
.SS "double Dimension::GetWeakElectroweak (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 119 of file dimension\&.h\&.
.SS "\fBvoid\fP Dimension::IncOffset (std::chrono::time_point< \fBClock\fP > event_time, double val)"

.PP
Definition at line 53 of file dimension\&.cc\&.
.SS "\fBvoid\fP Dimension::IncScale (std::chrono::time_point< \fBClock\fP > event_time, double val)"

.PP
Definition at line 29 of file dimension\&.cc\&.
.SS "\fBvoid\fP Dimension::IncTime (std::chrono::time_point< \fBClock\fP > event_time, double val)"

.PP
Definition at line 41 of file dimension\&.cc\&.
.SS "\fBvoid\fP Dimension::PollElementaryForce (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 144 of file dimension\&.h\&.
.SS "bool Dimension::ResetParameters (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 63 of file dimension\&.cc\&.
.SS "\fBvoid\fP Dimension::SetCharge (std::chrono::time_point< \fBClock\fP > event_time, int val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 115 of file dimension\&.h\&.
.SS "\fBvoid\fP Dimension::SetCounter (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)\fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 24 of file dimension\&.cc\&.
.SS "\fBvoid\fP Dimension::SetElectromagnetic (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 138 of file dimension\&.h\&.
.SS "\fBvoid\fP Dimension::SetElectromagneticElectroweak (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 139 of file dimension\&.h\&.
.SS "\fBvoid\fP Dimension::SetGravitation (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 135 of file dimension\&.h\&.
.SS "\fBvoid\fP Dimension::SetObjectType (std::chrono::time_point< \fBClock\fP > event_time, int val)"

.PP
Definition at line 57 of file dimension\&.cc\&.
.SS "\fBvoid\fP Dimension::SetOffset (std::chrono::time_point< \fBClock\fP > event_time, double val)"

.PP
Definition at line 27 of file dimension\&.cc\&.
.SS "\fBvoid\fP Dimension::SetScale (std::chrono::time_point< \fBClock\fP > event_time, double val)"

.PP
Definition at line 25 of file dimension\&.cc\&.
.SS "\fBvoid\fP Dimension::SetSpin (std::chrono::time_point< \fBClock\fP > event_time, int val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 116 of file dimension\&.h\&.
.SS "\fBvoid\fP Dimension::SetStrong (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 140 of file dimension\&.h\&.
.SS "\fBvoid\fP Dimension::SetStrongFundamental (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 141 of file dimension\&.h\&.
.SS "\fBvoid\fP Dimension::SetStrongResidual (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 142 of file dimension\&.h\&.
.SS "\fBvoid\fP Dimension::SetTime (std::chrono::time_point< \fBClock\fP > event_time, double val)"

.PP
Definition at line 26 of file dimension\&.cc\&.
.SS "\fBvoid\fP Dimension::SetWeak (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 136 of file dimension\&.h\&.
.SS "\fBvoid\fP Dimension::SetWeakElectroweak (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 137 of file dimension\&.h\&.
.SS "std::chrono::time_point< std::chrono::high_resolution_clock > Dimension::TheTimeNow ()"

.PP
Definition at line 19 of file dimension\&.cc\&.
.SS "int Dimension::Update (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 178 of file dimension\&.cc\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBCognitiveNetwork\fP\fC [friend]\fP"

.PP
Definition at line 26 of file dimension\&.h\&.
.SS "friend class CompositeForce\fC [friend]\fP"

.PP
Definition at line 27 of file dimension\&.h\&.
.SS "friend class CompositeParticle\fC [friend]\fP"

.PP
Definition at line 28 of file dimension\&.h\&.
.SS "friend class \fBElementaryForce\fP\fC [friend]\fP"

.PP
Definition at line 29 of file dimension\&.h\&.
.SS "friend class \fBElementaryParticle\fP\fC [friend]\fP"

.PP
Definition at line 30 of file dimension\&.h\&.
.SS "friend class \fBMatter\fP\fC [friend]\fP"

.PP
Definition at line 31 of file dimension\&.h\&.
.SS "friend class \fBMembrane\fP\fC [friend]\fP"

.PP
Definition at line 32 of file dimension\&.h\&.
.SS "friend class \fBMonomer\fP\fC [friend]\fP"

.PP
Definition at line 33 of file dimension\&.h\&.
.SS "friend class \fBNeuron\fP\fC [friend]\fP"

.PP
Definition at line 34 of file dimension\&.h\&.
.SS "friend class \fBPoint\fP\fC [friend]\fP"

.PP
Definition at line 36 of file dimension\&.h\&.
.SS "friend class \fBPolymer\fP\fC [friend]\fP"

.PP
Definition at line 35 of file dimension\&.h\&.
.SS "friend class \fBSolid\fP\fC [friend]\fP"

.PP
Definition at line 37 of file dimension\&.h\&.
.SS "friend class \fBSoma\fP\fC [friend]\fP"

.PP
Definition at line 38 of file dimension\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int Dimension::duration_since_last_event"

.PP
Definition at line 80 of file dimension\&.h\&.
.SS "std::chrono::time_point<\fBClock\fP> Dimension::objectExpiration\fC [protected]\fP"

.PP
Member variable 'objectExpiration'\&. 
.PP
Definition at line 155 of file dimension\&.h\&.
.SS "std::chrono::time_point<\fBClock\fP> Dimension::objectLifespan\fC [protected]\fP"

.PP
Member variable 'objectLifespan'\&. 
.PP
Definition at line 156 of file dimension\&.h\&.
.SS "double Dimension::scale_time\fC [protected]\fP"

.PP
Definition at line 153 of file dimension\&.h\&.
.SS "std::vector<\fBCounterAdjustment\fP*> Dimension::temporal_adjustment_list"

.PP
Definition at line 72 of file dimension\&.h\&.
.SS "std::chrono::time_point<\fBClock\fP> Dimension::time_object_created\fC [protected]\fP"

.PP
Member variable 'time_object_created'\&. 
.PP
Definition at line 154 of file dimension\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
