.TH "ElementaryParticle" 3 "Tue Oct 10 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ElementaryParticle
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <elementaryparticle\&.h>\fP
.PP
Inherits \fBUniverse\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElementaryParticle\fP ()"
.br
.ti -1c
.RI "\fBElementaryParticle\fP (unsigned int object_type)"
.br
.ti -1c
.RI "\fBElementaryParticle\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBElementaryParticle\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBUniverse\fP &universe_connector)"
.br
.ti -1c
.RI "virtual \fB~ElementaryParticle\fP ()"
.br
.ti -1c
.RI "unsigned int \fBGetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "unsigned int \fBGetType\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBGetCharge\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBGetSpin\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "double \fBGetMass\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "void \fBSetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)"
.br
.ti -1c
.RI "void \fBSetType\fP (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)"
.br
.ti -1c
.RI "void \fBSetCharge\fP (std::chrono::time_point< \fBClock\fP > event_time, int val)"
.br
.ti -1c
.RI "void \fBSetSpin\fP (std::chrono::time_point< \fBClock\fP > event_time, int val)"
.br
.ti -1c
.RI "void \fBSetMassIndex\fP (std::chrono::time_point< \fBClock\fP > event_time, int val)"
.br
.ti -1c
.RI "void \fBSetMass\fP (std::chrono::time_point< \fBClock\fP > event_time, double val)"
.br
.ti -1c
.RI "bool \fBResetParameters\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBUpdate\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBCompositeParticle\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 24 of file elementaryparticle\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ElementaryParticle::ElementaryParticle ()\fC [inline]\fP"

.PP
Definition at line 28 of file elementaryparticle\&.h\&.
.SS "ElementaryParticle::ElementaryParticle (unsigned int object_type)\fC [inline]\fP"

.PP
Definition at line 30 of file elementaryparticle\&.h\&.
.SS "ElementaryParticle::ElementaryParticle (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 32 of file elementaryparticle\&.h\&.
.SS "ElementaryParticle::ElementaryParticle (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBUniverse\fP & universe_connector)\fC [inline]\fP"

.PP
Definition at line 34 of file elementaryparticle\&.h\&.
.SS "virtual ElementaryParticle::~ElementaryParticle ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 53 of file elementaryparticle\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "int ElementaryParticle::GetCharge (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 57 of file elementaryparticle\&.h\&.
.SS "unsigned int ElementaryParticle::GetCounter (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 55 of file elementaryparticle\&.h\&.
.SS "double ElementaryParticle::GetMass (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 59 of file elementaryparticle\&.h\&.
.SS "int ElementaryParticle::GetSpin (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 58 of file elementaryparticle\&.h\&.
.SS "unsigned int ElementaryParticle::GetType (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 56 of file elementaryparticle\&.h\&.
.SS "bool ElementaryParticle::ResetParameters (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 19 of file elementaryparticle\&.cc\&.
.SS "void ElementaryParticle::SetCharge (std::chrono::time_point< \fBClock\fP > event_time, int val)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 63 of file elementaryparticle\&.h\&.
.SS "void ElementaryParticle::SetCounter (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 61 of file elementaryparticle\&.h\&.
.SS "void ElementaryParticle::SetMass (std::chrono::time_point< \fBClock\fP > event_time, double val)"

.PP
Definition at line 166 of file elementaryparticle\&.cc\&.
.SS "void ElementaryParticle::SetMassIndex (std::chrono::time_point< \fBClock\fP > event_time, int val)"

.PP
Definition at line 42 of file elementaryparticle\&.cc\&.
.SS "void ElementaryParticle::SetSpin (std::chrono::time_point< \fBClock\fP > event_time, int val)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 64 of file elementaryparticle\&.h\&.
.SS "void ElementaryParticle::SetType (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)\fC [inline]\fP"

.PP
Definition at line 62 of file elementaryparticle\&.h\&.
.SS "int ElementaryParticle::Update (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 168 of file elementaryparticle\&.cc\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class CompositeParticle\fC [friend]\fP"

.PP
Definition at line 26 of file elementaryparticle\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
