.TH "gladGLversionStruct" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gladGLversionStruct
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <glad\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBmajor\fP"
.br
.ti -1c
.RI "int \fBminor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 658 of file glad\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int gladGLversionStruct::major"

.PP
Definition at line 659 of file glad\&.h\&.
.SS "int gladGLversionStruct::minor"

.PP
Definition at line 660 of file glad\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
