.TH "Graph< L >" 3 "Tue Oct 10 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Graph< L >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef L \fBLocation\fP"
.br
.ti -1c
.RI "typedef vector< \fBLocation\fP >::\fBiterator\fP \fBiterator\fP"
.br
.ti -1c
.RI "typedef L \fBLocation\fP"
.br
.ti -1c
.RI "typedef vector< \fBLocation\fP >::\fBiterator\fP \fBiterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const vector< \fBLocation\fP > \fBneighbors\fP (\fBLocation\fP id)"
.br
.ti -1c
.RI "const vector< \fBLocation\fP > \fBneighbors\fP (\fBLocation\fP id)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unordered_map< \fBLocation\fP, vector< \fBLocation\fP > > \fBedges\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename L>
.br
struct Graph< L >"

.PP
Definition at line 33 of file implementation orig\&.cpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename L > typedef vector<\fBLocation\fP>::\fBiterator\fP \fBGraph\fP< L >::\fBiterator\fP"

.PP
Definition at line 35 of file implementation orig\&.cpp\&.
.SS "template<typename L > typedef vector<\fBLocation\fP>::\fBiterator\fP \fBGraph\fP< L >::\fBiterator\fP"

.PP
Definition at line 41 of file search\&.cpp\&.
.SS "template<typename L > typedef L \fBGraph\fP< L >::\fBLocation\fP"

.PP
Definition at line 34 of file implementation orig\&.cpp\&.
.SS "template<typename L > typedef L \fBGraph\fP< L >::\fBLocation\fP"

.PP
Definition at line 40 of file search\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename L > const vector<\fBLocation\fP> \fBGraph\fP< L >::neighbors (\fBLocation\fP id)\fC [inline]\fP"

.PP
Definition at line 38 of file implementation orig\&.cpp\&.
.SS "template<typename L > const vector<\fBLocation\fP> \fBGraph\fP< L >::neighbors (\fBLocation\fP id)\fC [inline]\fP"

.PP
Definition at line 44 of file search\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename L > unordered_map< \fBLocation\fP, vector< \fBLocation\fP > > \fBGraph\fP< L >::edges"

.PP
Definition at line 36 of file implementation orig\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
