.TH "GridWithWeights" 3 "Tue Oct 10 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GridWithWeights
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSquareGrid\fP, and \fBSquareGrid\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGridWithWeights\fP (int w, int h)"
.br
.ti -1c
.RI "int \fBcost\fP (\fBLocation\fP a, \fBLocation\fP b)"
.br
.ti -1c
.RI "\fBGridWithWeights\fP (int w, int h)"
.br
.ti -1c
.RI "int \fBcost\fP (\fBLocation\fP a, \fBLocation\fP b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unordered_set< \fBLocation\fP > \fBforests\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 165 of file implementation orig\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GridWithWeights::GridWithWeights (int w, int h)\fC [inline]\fP"

.PP
Definition at line 167 of file implementation orig\&.cpp\&.
.SS "GridWithWeights::GridWithWeights (int w, int h)\fC [inline]\fP"

.PP
Definition at line 173 of file search\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "int GridWithWeights::cost (\fBLocation\fP a, \fBLocation\fP b)\fC [inline]\fP"

.PP
Definition at line 168 of file implementation orig\&.cpp\&.
.SS "int GridWithWeights::cost (\fBLocation\fP a, \fBLocation\fP b)\fC [inline]\fP"

.PP
Definition at line 174 of file search\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "unordered_set< \fBLocation\fP > GridWithWeights::forests"

.PP
Definition at line 166 of file implementation orig\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
