.TH "/Users/pbisaacs/Developer/BrainHarmonics/BrainHarmonics/kchannel.cc" 3 "Sat Apr 29 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/pbisaacs/Developer/BrainHarmonics/BrainHarmonics/kchannel.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Kchannel\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
