.TH "Kchannel" 3 "Sat Apr 29 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Kchannel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kchannel\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKchannel\fP ()"
.br
.ti -1c
.RI "virtual \fB~Kchannel\fP ()"
.br
.ti -1c
.RI "unsigned int \fBGetCounter\fP ()"
.br
.ti -1c
.RI "double \fBGetEnergy\fP ()"
.br
.ti -1c
.RI "void \fBSetCounter\fP (unsigned int val)"
.br
.ti -1c
.RI "void \fBSetEnergy\fP (double val)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file kchannel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Kchannel::Kchannel ()\fC [inline]\fP"
Default constructor 
.PP
Definition at line 18 of file kchannel\&.h\&.
.SS "virtual Kchannel::~Kchannel ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 24 of file kchannel\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "unsigned int Kchannel::GetCounter ()\fC [inline]\fP"
Access m_Counter 
.PP
\fBReturns:\fP
.RS 4
The current value of m_Counter 
.RE
.PP

.PP
Definition at line 28 of file kchannel\&.h\&.
.SS "double Kchannel::GetEnergy ()\fC [inline]\fP"

.PP
Definition at line 29 of file kchannel\&.h\&.
.SS "void Kchannel::SetCounter (unsigned int val)\fC [inline]\fP"
Set m_Counter 
.PP
\fBParameters:\fP
.RS 4
\fIval\fP New value to Set 
.RE
.PP

.PP
Definition at line 33 of file kchannel\&.h\&.
.SS "void Kchannel::SetEnergy (double val)\fC [inline]\fP"

.PP
Definition at line 34 of file kchannel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
