.TH "glad/include/KHR/khrplatform.h" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glad/include/KHR/khrplatform.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBKHRONOS_APICALL\fP"
.br
.ti -1c
.RI "#define \fBKHRONOS_APIENTRY\fP"
.br
.ti -1c
.RI "#define \fBKHRONOS_APIATTRIBUTES\fP"
.br
.ti -1c
.RI "#define \fBKHRONOS_SUPPORT_INT64\fP   1"
.br
.ti -1c
.RI "#define \fBKHRONOS_SUPPORT_FLOAT\fP   1"
.br
.ti -1c
.RI "#define \fBKHRONOS_MAX_ENUM\fP   0x7FFFFFFF"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int32_t \fBkhronos_int32_t\fP"
.br
.ti -1c
.RI "typedef uint32_t \fBkhronos_uint32_t\fP"
.br
.ti -1c
.RI "typedef int64_t \fBkhronos_int64_t\fP"
.br
.ti -1c
.RI "typedef uint64_t \fBkhronos_uint64_t\fP"
.br
.ti -1c
.RI "typedef signed char \fBkhronos_int8_t\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBkhronos_uint8_t\fP"
.br
.ti -1c
.RI "typedef signed short int \fBkhronos_int16_t\fP"
.br
.ti -1c
.RI "typedef unsigned short int \fBkhronos_uint16_t\fP"
.br
.ti -1c
.RI "typedef signed long int \fBkhronos_intptr_t\fP"
.br
.ti -1c
.RI "typedef unsigned long int \fBkhronos_uintptr_t\fP"
.br
.ti -1c
.RI "typedef signed long int \fBkhronos_ssize_t\fP"
.br
.ti -1c
.RI "typedef unsigned long int \fBkhronos_usize_t\fP"
.br
.ti -1c
.RI "typedef float \fBkhronos_float_t\fP"
.br
.ti -1c
.RI "typedef \fBkhronos_uint64_t\fP \fBkhronos_utime_nanoseconds_t\fP"
.br
.ti -1c
.RI "typedef \fBkhronos_int64_t\fP \fBkhronos_stime_nanoseconds_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBkhronos_boolean_enum_t\fP { \fBKHRONOS_FALSE\fP = 0, \fBKHRONOS_TRUE\fP = 1, \fBKHRONOS_BOOLEAN_ENUM_FORCE_SIZE\fP = KHRONOS_MAX_ENUM }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define KHRONOS_APIATTRIBUTES"

.PP
Definition at line 137 of file khrplatform\&.h\&.
.SS "#define KHRONOS_APICALL"

.PP
Definition at line 113 of file khrplatform\&.h\&.
.SS "#define KHRONOS_APIENTRY"

.PP
Definition at line 126 of file khrplatform\&.h\&.
.SS "#define KHRONOS_MAX_ENUM   0x7FFFFFFF"

.PP
Definition at line 275 of file khrplatform\&.h\&.
.SS "#define KHRONOS_SUPPORT_FLOAT   1"

.PP
Definition at line 220 of file khrplatform\&.h\&.
.SS "#define KHRONOS_SUPPORT_INT64   1"

.PP
Definition at line 219 of file khrplatform\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef float \fBkhronos_float_t\fP"

.PP
Definition at line 254 of file khrplatform\&.h\&.
.SS "typedef signed short int \fBkhronos_int16_t\fP"

.PP
Definition at line 230 of file khrplatform\&.h\&.
.SS "typedef int32_t \fBkhronos_int32_t\fP"

.PP
Definition at line 215 of file khrplatform\&.h\&.
.SS "typedef int64_t \fBkhronos_int64_t\fP"

.PP
Definition at line 217 of file khrplatform\&.h\&.
.SS "typedef signed char \fBkhronos_int8_t\fP"

.PP
Definition at line 228 of file khrplatform\&.h\&.
.SS "typedef signed long int \fBkhronos_intptr_t\fP"

.PP
Definition at line 244 of file khrplatform\&.h\&.
.SS "typedef signed long int \fBkhronos_ssize_t\fP"

.PP
Definition at line 246 of file khrplatform\&.h\&.
.SS "typedef \fBkhronos_int64_t\fP \fBkhronos_stime_nanoseconds_t\fP"

.PP
Definition at line 268 of file khrplatform\&.h\&.
.SS "typedef unsigned short int \fBkhronos_uint16_t\fP"

.PP
Definition at line 231 of file khrplatform\&.h\&.
.SS "typedef uint32_t \fBkhronos_uint32_t\fP"

.PP
Definition at line 216 of file khrplatform\&.h\&.
.SS "typedef uint64_t \fBkhronos_uint64_t\fP"

.PP
Definition at line 218 of file khrplatform\&.h\&.
.SS "typedef unsigned char \fBkhronos_uint8_t\fP"

.PP
Definition at line 229 of file khrplatform\&.h\&.
.SS "typedef unsigned long int \fBkhronos_uintptr_t\fP"

.PP
Definition at line 245 of file khrplatform\&.h\&.
.SS "typedef unsigned long int \fBkhronos_usize_t\fP"

.PP
Definition at line 247 of file khrplatform\&.h\&.
.SS "typedef \fBkhronos_uint64_t\fP \fBkhronos_utime_nanoseconds_t\fP"

.PP
Definition at line 267 of file khrplatform\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBkhronos_boolean_enum_t\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIKHRONOS_FALSE \fP\fP
.TP
\fB\fIKHRONOS_TRUE \fP\fP
.TP
\fB\fIKHRONOS_BOOLEAN_ENUM_FORCE_SIZE \fP\fP
.PP
Definition at line 284 of file khrplatform\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
