.TH "BrainHarmonics/mapper.cpp" 3 "Tue Oct 10 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BrainHarmonics/mapper.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <Aria\&.h>\fP
.br
\fC#include 'mapper\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
