.TH "mapper" 3 "Tue Oct 10 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mapper
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mapper\&.h>\fP
.PP
Inherits ArAction\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmapper\fP ()"
.br
.ti -1c
.RI "virtual \fB~mapper\fP ()"
.br
.ti -1c
.RI "virtual ArActionDesired * \fBfire\fP (ArActionDesired d)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ArActionDesired \fBdesiredState\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBspeed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file mapper\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "mapper::mapper ()"

.PP
Definition at line 5 of file mapper\&.cpp\&.
.SS "virtual mapper::~mapper ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 10 of file mapper\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual ArActionDesired* mapper::fire (ArActionDesired d)\fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "ArActionDesired mapper::desiredState"

.PP
Definition at line 12 of file mapper\&.h\&.
.SS "int mapper::speed\fC [protected]\fP"

.PP
Definition at line 14 of file mapper\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
