.TH "BrainHarmonics/matter.h" 3 "Tue Oct 10 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BrainHarmonics/matter.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'universe\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMatter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
