.TH "MembraneChannel" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MembraneChannel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <membranechannel\&.h>\fP
.PP
Inherits \fBMembrane\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMembraneChannel\fP ()"
.br
.ti -1c
.RI "\fBMembraneChannel\fP (unsigned int object_type)"
.br
.ti -1c
.RI "\fBMembraneChannel\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBMembraneChannel\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBMembrane\fP &membrane_connector)"
.br
.ti -1c
.RI "virtual \fB~MembraneChannel\fP ()"
.br
.ti -1c
.RI "unsigned int \fBGetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "double \fBGetEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "bool \fBGetReceptorBindingState\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBGetReceptorType\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "bool \fBGetDisabled\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBGetIons\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetReceptorBindingState\fP (bool \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBtoggleReceptorBindingState\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBvoid\fP \fBtoggleDisabled\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetDisabled\fP (std::chrono::time_point< \fBClock\fP > event_time, bool \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetReceptorType\fP (std::chrono::time_point< \fBClock\fP > event_time, int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time, unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetIons\fP (std::chrono::time_point< \fBClock\fP > event_time, int \fBval\fP)"
.br
.ti -1c
.RI "bool \fBResetParameters\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBCognitiveNetwork\fP * \fBCreateNeurotransmitter\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "std::vector< \fBCognitiveNetwork\fP * > \fBCreateNeurotransmitters\fP (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"
.br
.ti -1c
.RI "\fBCognitiveNetwork\fP * \fBCloneNeurotransmitter\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBCognitiveNetwork\fP *clone_object, double perfection_membership)"
.br
.ti -1c
.RI "std::vector< \fBCognitiveNetwork\fP * > \fBCloneNeurotransmitters\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBCognitiveNetwork\fP *> cloning_list, double perfection_membership)"
.br
.ti -1c
.RI "\fBCognitiveNetwork\fP * \fBDestroyNeurotransmitter\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBCognitiveNetwork\fP *destroy_object)"
.br
.ti -1c
.RI "std::vector< \fBCognitiveNetwork\fP * > \fBDestroyNeurotransmitters\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBCognitiveNetwork\fP *> destruction_list)"
.br
.ti -1c
.RI "\fBCognitiveNetwork\fP * \fBAddNeurotransmitter\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBCognitiveNetwork\fP *add_object)"
.br
.ti -1c
.RI "std::vector< \fBCognitiveNetwork\fP * > \fBAddNeurotransmitters\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBCognitiveNetwork\fP *> add_objects)"
.br
.ti -1c
.RI "\fBCognitiveNetwork\fP * \fBRemoveNeurotransmitter\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "std::vector< \fBCognitiveNetwork\fP * > \fBRemoveNeurotransmitters\fP (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"
.br
.ti -1c
.RI "\fBCognitiveNetwork\fP * \fBGetNeurotransmitter\fP (std::chrono::time_point< \fBClock\fP > event_time, int selector)"
.br
.ti -1c
.RI "std::vector< \fBCognitiveNetwork\fP * > \fBGetNeurotransmitters\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "bool \fBCompatibilityCheck\fP (std::chrono::time_point< \fBClock\fP > event_time, int neurotransmitterType)"
.br
.ti -1c
.RI "int \fBUpdate\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBCognitiveNetwork\fP * > \fBneurotransmitter_list\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 33 of file membranechannel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MembraneChannel::MembraneChannel ()\fC [inline]\fP"

.PP
Definition at line 36 of file membranechannel\&.h\&.
.SS "MembraneChannel::MembraneChannel (unsigned int object_type)\fC [inline]\fP"

.PP
Definition at line 38 of file membranechannel\&.h\&.
.SS "MembraneChannel::MembraneChannel (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 40 of file membranechannel\&.h\&.
.SS "MembraneChannel::MembraneChannel (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBMembrane\fP & membrane_connector)\fC [inline]\fP"

.PP
Definition at line 42 of file membranechannel\&.h\&.
.SS "virtual MembraneChannel::~MembraneChannel ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 53 of file membranechannel\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCognitiveNetwork\fP * MembraneChannel::AddNeurotransmitter (std::chrono::time_point< \fBClock\fP > event_time, \fBCognitiveNetwork\fP * add_object)"

.PP
Definition at line 127 of file membranechannel\&.cc\&.
.SS "std::vector< \fBCognitiveNetwork\fP * > MembraneChannel::AddNeurotransmitters (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBCognitiveNetwork\fP *> add_objects)"

.PP
Definition at line 138 of file membranechannel\&.cc\&.
.SS "\fBCognitiveNetwork\fP * MembraneChannel::CloneNeurotransmitter (std::chrono::time_point< \fBClock\fP > event_time, \fBCognitiveNetwork\fP * clone_object, double perfection_membership)"

.PP
Definition at line 112 of file membranechannel\&.cc\&.
.SS "std::vector< \fBCognitiveNetwork\fP * > MembraneChannel::CloneNeurotransmitters (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBCognitiveNetwork\fP *> cloning_list, double perfection_membership)"

.PP
Definition at line 107 of file membranechannel\&.cc\&.
.SS "bool MembraneChannel::CompatibilityCheck (std::chrono::time_point< \fBClock\fP > event_time, int neurotransmitterType)"

.PP
Definition at line 182 of file membranechannel\&.cc\&.
.SS "\fBCognitiveNetwork\fP * MembraneChannel::CreateNeurotransmitter (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 74 of file membranechannel\&.cc\&.
.SS "std::vector< \fBCognitiveNetwork\fP * > MembraneChannel::CreateNeurotransmitters (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"

.PP
Definition at line 85 of file membranechannel\&.cc\&.
.SS "\fBCognitiveNetwork\fP * MembraneChannel::DestroyNeurotransmitter (std::chrono::time_point< \fBClock\fP > event_time, \fBCognitiveNetwork\fP * destroy_object)"

.PP
Definition at line 122 of file membranechannel\&.cc\&.
.SS "std::vector< \fBCognitiveNetwork\fP * > MembraneChannel::DestroyNeurotransmitters (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBCognitiveNetwork\fP *> destruction_list)"

.PP
Definition at line 117 of file membranechannel\&.cc\&.
.SS "unsigned int MembraneChannel::GetCounter (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 55 of file membranechannel\&.h\&.
.SS "bool MembraneChannel::GetDisabled (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 59 of file membranechannel\&.h\&.
.SS "double MembraneChannel::GetEnergy (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 56 of file membranechannel\&.h\&.
.SS "int MembraneChannel::GetIons (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 60 of file membranechannel\&.h\&.
.SS "\fBCognitiveNetwork\fP * MembraneChannel::GetNeurotransmitter (std::chrono::time_point< \fBClock\fP > event_time, int selector)"

.PP
Definition at line 171 of file membranechannel\&.cc\&.
.SS "std::vector< \fBCognitiveNetwork\fP * > MembraneChannel::GetNeurotransmitters (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 176 of file membranechannel\&.cc\&.
.SS "bool MembraneChannel::GetReceptorBindingState (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 57 of file membranechannel\&.h\&.
.SS "int MembraneChannel::GetReceptorType (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 58 of file membranechannel\&.h\&.
.SS "\fBCognitiveNetwork\fP * MembraneChannel::RemoveNeurotransmitter (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 160 of file membranechannel\&.cc\&.
.SS "std::vector< \fBCognitiveNetwork\fP * > MembraneChannel::RemoveNeurotransmitters (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"

.PP
Definition at line 166 of file membranechannel\&.cc\&.
.SS "bool MembraneChannel::ResetParameters (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 20 of file membranechannel\&.cc\&.
.SS "\fBvoid\fP MembraneChannel::SetCounter (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBMembrane\fP\&.
.PP
Definition at line 67 of file membranechannel\&.h\&.
.SS "\fBvoid\fP MembraneChannel::setDisabled (std::chrono::time_point< \fBClock\fP > event_time, bool val)\fC [inline]\fP"

.PP
Definition at line 65 of file membranechannel\&.h\&.
.SS "\fBvoid\fP MembraneChannel::SetEnergy (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP"

.PP
Definition at line 68 of file membranechannel\&.h\&.
.SS "\fBvoid\fP MembraneChannel::SetIons (std::chrono::time_point< \fBClock\fP > event_time, int val)\fC [inline]\fP"

.PP
Definition at line 69 of file membranechannel\&.h\&.
.SS "\fBvoid\fP MembraneChannel::setReceptorBindingState (bool val)\fC [inline]\fP"

.PP
Definition at line 62 of file membranechannel\&.h\&.
.SS "\fBvoid\fP MembraneChannel::setReceptorType (std::chrono::time_point< \fBClock\fP > event_time, int val)\fC [inline]\fP"

.PP
Definition at line 66 of file membranechannel\&.h\&.
.SS "\fBvoid\fP MembraneChannel::toggleDisabled (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 64 of file membranechannel\&.h\&.
.SS "\fBvoid\fP MembraneChannel::toggleReceptorBindingState (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 63 of file membranechannel\&.h\&.
.SS "int MembraneChannel::Update (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 215 of file membranechannel\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBCognitiveNetwork\fP*> MembraneChannel::neurotransmitter_list\fC [protected]\fP"

.PP
Definition at line 102 of file membranechannel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
