.TH "Messages" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Messages
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <messages\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMessages\fP ()"
.br
.ti -1c
.RI "virtual \fB~Messages\fP ()"
.br
.ti -1c
.RI "bool \fBloadFromFile\fP (const \fBstd::string\fP &filename)"
.br
.ti -1c
.RI "unsigned int \fBGetCounter\fP ()"
.br
.ti -1c
.RI "double \fBGetEnergy\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetCounter\fP (unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetEnergy\fP (double \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBCreation\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file messages\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Messages::Messages ()"
Default constructor 
.PP
Definition at line 13 of file messages\&.cpp\&.
.SS "Messages::~Messages ()\fC [virtual]\fP"
Default destructor 
.PP
Definition at line 16 of file messages\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP Messages::Creation ()\fC [inline]\fP"

.PP
Definition at line 43 of file messages\&.hpp\&.
.SS "unsigned int Messages::GetCounter ()\fC [inline]\fP"
Access m_Counter 
.PP
\fBReturns:\fP
.RS 4
The current value of m_Counter 
.RE
.PP

.PP
Definition at line 36 of file messages\&.hpp\&.
.SS "double Messages::GetEnergy ()\fC [inline]\fP"

.PP
Definition at line 37 of file messages\&.hpp\&.
.SS "bool Messages::loadFromFile (const \fBstd::string\fP & filename)\fC [inline]\fP"

.PP
Definition at line 22 of file messages\&.hpp\&.
.SS "\fBvoid\fP Messages::SetCounter (unsigned int val)\fC [inline]\fP"
Set m_Counter 
.PP
\fBParameters:\fP
.RS 4
\fIval\fP New value to set 
.RE
.PP

.PP
Definition at line 41 of file messages\&.hpp\&.
.SS "\fBvoid\fP Messages::SetEnergy (double val)\fC [inline]\fP"

.PP
Definition at line 42 of file messages\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
