.TH "Monomer" 3 "Tue Oct 10 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Monomer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <monomer\&.h>\fP
.PP
Inherits \fBUniverse\fP\&.
.PP
Inherited by \fBPolymer\fP, \fBPolymer\fP, \fBPolymer\fP, \fBPolymer\fP, \fBPolymer\fP, \fBPolymer\fP, \fBPolymer\fP, \fBPolymer\fP, \fBPolymer\fP, and \fBPolymer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMonomer\fP ()"
.br
.ti -1c
.RI "\fBMonomer\fP (unsigned int object_type)"
.br
.ti -1c
.RI "\fBMonomer\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBMonomer\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBUniverse\fP &universe_connector)"
.br
.ti -1c
.RI "virtual \fB~Monomer\fP ()"
.br
.ti -1c
.RI "unsigned int \fBGetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "void \fBSetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)"
.br
.ti -1c
.RI "bool \fBResetParameters\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBAddSolid\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBUpdate\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "void \fBSetCharge\fP (std::chrono::time_point< \fBClock\fP > event_time, int val) final"
.br
.ti -1c
.RI "void \fBSetSpin\fP (std::chrono::time_point< \fBClock\fP > event_time, int val) final"
.br
.ti -1c
.RI "double \fBGetGravitation\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBGetWeak\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBGetWeakElectroweak\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBGetElectromagnetic\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBGetElectromagneticElectroweak\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBGetStrong\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBGetStrongFundamental\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBGetStrongResidual\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBApplyGravitation\fP (std::chrono::time_point< \fBClock\fP > event_time, double val) final"
.br
.ti -1c
.RI "double \fBApplyWeak\fP (std::chrono::time_point< \fBClock\fP > event_time, double val) final"
.br
.ti -1c
.RI "double \fBApplyWeakElectroweak\fP (std::chrono::time_point< \fBClock\fP > event_time, double val) final"
.br
.ti -1c
.RI "double \fBApplyElectromagnetic\fP (std::chrono::time_point< \fBClock\fP > event_time, double val) final"
.br
.ti -1c
.RI "double \fBApplyElectromagneticElectroweak\fP (std::chrono::time_point< \fBClock\fP > event_time, double val) final"
.br
.ti -1c
.RI "double \fBApplyStrong\fP (std::chrono::time_point< \fBClock\fP > event_time, double val) final"
.br
.ti -1c
.RI "double \fBApplyStrongFundamental\fP (std::chrono::time_point< \fBClock\fP > event_time, double val) final"
.br
.ti -1c
.RI "double \fBApplyStrongResidual\fP (std::chrono::time_point< \fBClock\fP > event_time, double val) final"
.br
.ti -1c
.RI "void \fBSetGravitation\fP (std::chrono::time_point< \fBClock\fP > event_time, double val) final"
.br
.ti -1c
.RI "void \fBSetWeak\fP (std::chrono::time_point< \fBClock\fP > event_time, double val) final"
.br
.ti -1c
.RI "void \fBSetWeakElectroweak\fP (std::chrono::time_point< \fBClock\fP > event_time, double val) final"
.br
.ti -1c
.RI "void \fBSetElectromagnetic\fP (std::chrono::time_point< \fBClock\fP > event_time, double val) final"
.br
.ti -1c
.RI "void \fBSetElectromagneticElectroweak\fP (std::chrono::time_point< \fBClock\fP > event_time, double val) final"
.br
.ti -1c
.RI "void \fBSetStrong\fP (std::chrono::time_point< \fBClock\fP > event_time, double val) final"
.br
.ti -1c
.RI "void \fBSetStrongFundamental\fP (std::chrono::time_point< \fBClock\fP > event_time, double val) final"
.br
.ti -1c
.RI "void \fBSetStrongResidual\fP (std::chrono::time_point< \fBClock\fP > event_time, double val) final"
.br
.ti -1c
.RI "void \fBPollElementaryForce\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBMonomer\fP * > \fBsolid_list\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 24 of file monomer\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Monomer::Monomer ()\fC [inline]\fP"

.PP
Definition at line 28 of file monomer\&.h\&.
.SS "Monomer::Monomer (unsigned int object_type)\fC [inline]\fP"

.PP
Definition at line 30 of file monomer\&.h\&.
.SS "Monomer::Monomer (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 32 of file monomer\&.h\&.
.SS "Monomer::Monomer (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBUniverse\fP & universe_connector)\fC [inline]\fP"

.PP
Definition at line 34 of file monomer\&.h\&.
.SS "virtual Monomer::~Monomer ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 48 of file monomer\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "int Monomer::AddSolid (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 75 of file monomer\&.cc\&.
.SS "double Monomer::ApplyElectromagnetic (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 74 of file monomer\&.h\&.
.SS "double Monomer::ApplyElectromagneticElectroweak (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 75 of file monomer\&.h\&.
.SS "double Monomer::ApplyGravitation (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 71 of file monomer\&.h\&.
.SS "double Monomer::ApplyStrong (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 76 of file monomer\&.h\&.
.SS "double Monomer::ApplyStrongFundamental (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 77 of file monomer\&.h\&.
.SS "double Monomer::ApplyStrongResidual (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 78 of file monomer\&.h\&.
.SS "double Monomer::ApplyWeak (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 72 of file monomer\&.h\&.
.SS "double Monomer::ApplyWeakElectroweak (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 73 of file monomer\&.h\&.
.SS "unsigned int Monomer::GetCounter (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 20 of file monomer\&.cc\&.
.SS "double Monomer::GetElectromagnetic (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 65 of file monomer\&.h\&.
.SS "double Monomer::GetElectromagneticElectroweak (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 66 of file monomer\&.h\&.
.SS "double Monomer::GetGravitation (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 62 of file monomer\&.h\&.
.SS "double Monomer::GetStrong (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 67 of file monomer\&.h\&.
.SS "double Monomer::GetStrongFundamental (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 68 of file monomer\&.h\&.
.SS "double Monomer::GetStrongResidual (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 69 of file monomer\&.h\&.
.SS "double Monomer::GetWeak (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 63 of file monomer\&.h\&.
.SS "double Monomer::GetWeakElectroweak (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 64 of file monomer\&.h\&.
.SS "void Monomer::PollElementaryForce (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 89 of file monomer\&.h\&.
.SS "bool Monomer::ResetParameters (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 24 of file monomer\&.cc\&.
.SS "void Monomer::SetCharge (std::chrono::time_point< \fBClock\fP > event_time, int val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 60 of file monomer\&.h\&.
.SS "void Monomer::SetCounter (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)\fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Reimplemented in \fBPolymer\fP\&.
.PP
Definition at line 22 of file monomer\&.cc\&.
.SS "void Monomer::SetElectromagnetic (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 83 of file monomer\&.h\&.
.SS "void Monomer::SetElectromagneticElectroweak (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 84 of file monomer\&.h\&.
.SS "void Monomer::SetGravitation (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 80 of file monomer\&.h\&.
.SS "void Monomer::SetSpin (std::chrono::time_point< \fBClock\fP > event_time, int val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 61 of file monomer\&.h\&.
.SS "void Monomer::SetStrong (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 85 of file monomer\&.h\&.
.SS "void Monomer::SetStrongFundamental (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 86 of file monomer\&.h\&.
.SS "void Monomer::SetStrongResidual (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 87 of file monomer\&.h\&.
.SS "void Monomer::SetWeak (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 81 of file monomer\&.h\&.
.SS "void Monomer::SetWeakElectroweak (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 82 of file monomer\&.h\&.
.SS "int Monomer::Update (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 83 of file monomer\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBMonomer\fP*> Monomer::solid_list\fC [protected]\fP"

.PP
Definition at line 98 of file monomer\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
