.TH "MultiScreen" 3 "Tue Oct 10 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MultiScreen
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiscreen\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMultiScreen\fP ()"
.br
.ti -1c
.RI "virtual \fB~MultiScreen\fP ()"
.br
.ti -1c
.RI "virtual int \fBrunScreen\fP (sf::RenderWindow &app)=0"
.br
.ti -1c
.RI "void \fBcreation\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 24 of file multiscreen\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MultiScreen::MultiScreen ()\fC [inline]\fP"
Default constructor 
.PP
Definition at line 29 of file multiscreen\&.h\&.
.SS "virtual MultiScreen::~MultiScreen ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 31 of file multiscreen\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void MultiScreen::creation ()\fC [inline]\fP"

.PP
Definition at line 35 of file multiscreen\&.h\&.
.SS "virtual int MultiScreen::runScreen (sf::RenderWindow & app)\fC [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
