.TH "MyelinSheath" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MyelinSheath
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <myelinsheath\&.h>\fP
.PP
Inherits \fBCognitiveNetwork\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyelinSheath\fP ()"
.br
.ti -1c
.RI "\fBMyelinSheath\fP (unsigned int object_type)"
.br
.ti -1c
.RI "\fBMyelinSheath\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBMyelinSheath\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBCognitiveNetwork\fP &cognitivenetwork_connector)"
.br
.ti -1c
.RI "virtual \fB~MyelinSheath\fP ()"
.br
.ti -1c
.RI "bool \fBResetParameters\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "unsigned int \fBGetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "double \fBGetEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time, unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP)"
.br
.ti -1c
.RI "int \fBUpdate\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBCognitiveNetwork\fP * > \fBaxonbranch_list\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 16 of file myelinsheath\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MyelinSheath::MyelinSheath ()\fC [inline]\fP"

.PP
Definition at line 19 of file myelinsheath\&.h\&.
.SS "MyelinSheath::MyelinSheath (unsigned int object_type)\fC [inline]\fP"

.PP
Definition at line 21 of file myelinsheath\&.h\&.
.SS "MyelinSheath::MyelinSheath (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 23 of file myelinsheath\&.h\&.
.SS "MyelinSheath::MyelinSheath (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBCognitiveNetwork\fP & cognitivenetwork_connector)\fC [inline]\fP"

.PP
Definition at line 25 of file myelinsheath\&.h\&.
.SS "virtual MyelinSheath::~MyelinSheath ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 34 of file myelinsheath\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "unsigned int MyelinSheath::GetCounter (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 38 of file myelinsheath\&.h\&.
.SS "double MyelinSheath::GetEnergy (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 39 of file myelinsheath\&.h\&.
.SS "bool MyelinSheath::ResetParameters (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 20 of file myelinsheath\&.cc\&.
.SS "\fBvoid\fP MyelinSheath::SetCounter (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 41 of file myelinsheath\&.h\&.
.SS "\fBvoid\fP MyelinSheath::SetEnergy (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP"

.PP
Definition at line 42 of file myelinsheath\&.h\&.
.SS "int MyelinSheath::Update (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 74 of file myelinsheath\&.cc\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBCognitiveNetwork\fP*> MyelinSheath::axonbranch_list\fC [protected]\fP"

.PP
Definition at line 47 of file myelinsheath\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
