.TH "Nachannel" 3 "Sat Apr 29 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Nachannel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nachannel\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNachannel\fP ()"
.br
.ti -1c
.RI "virtual \fB~Nachannel\fP ()"
.br
.ti -1c
.RI "unsigned int \fBGetCounter\fP ()"
.br
.ti -1c
.RI "double \fBGetEnergy\fP ()"
.br
.ti -1c
.RI "void \fBSetCounter\fP (unsigned int val)"
.br
.ti -1c
.RI "void \fBSetEnergy\fP (double val)"
.br
.ti -1c
.RI "void \fBCreation\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file nachannel\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Nachannel::Nachannel ()\fC [inline]\fP"
Default constructor 
.PP
Definition at line 18 of file nachannel\&.h\&.
.SS "virtual Nachannel::~Nachannel ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 20 of file nachannel\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "void Nachannel::Creation ()\fC [inline]\fP"

.PP
Definition at line 31 of file nachannel\&.h\&.
.SS "unsigned int Nachannel::GetCounter ()\fC [inline]\fP"
Access m_Counter 
.PP
\fBReturns:\fP
.RS 4
The current value of m_Counter 
.RE
.PP

.PP
Definition at line 24 of file nachannel\&.h\&.
.SS "double Nachannel::GetEnergy ()\fC [inline]\fP"

.PP
Definition at line 25 of file nachannel\&.h\&.
.SS "void Nachannel::SetCounter (unsigned int val)\fC [inline]\fP"
Set m_Counter 
.PP
\fBParameters:\fP
.RS 4
\fIval\fP New value to Set 
.RE
.PP

.PP
Definition at line 29 of file nachannel\&.h\&.
.SS "void Nachannel::SetEnergy (double val)\fC [inline]\fP"

.PP
Definition at line 30 of file nachannel\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
