.TH "/Users/pbisaacs/Developer/BrainHarmonics/BrainHarmonics/nachannel.h" 3 "Sat Apr 29 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/pbisaacs/Developer/BrainHarmonics/BrainHarmonics/nachannel.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNachannel\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
