.TH "Neurotransmitter" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Neurotransmitter
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <neurotransmitter\&.h>\fP
.PP
Inherits \fBCognitiveNetwork\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNeurotransmitter\fP ()"
.br
.ti -1c
.RI "\fBNeurotransmitter\fP (unsigned int object_type)"
.br
.ti -1c
.RI "\fBNeurotransmitter\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBNeurotransmitter\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBCognitiveNetwork\fP &cognitivenetwork_connector)"
.br
.ti -1c
.RI "virtual \fB~Neurotransmitter\fP ()"
.br
.ti -1c
.RI "unsigned int \fBGetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "double \fBGetEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBGetType\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetType\fP (std::chrono::time_point< \fBClock\fP > event_time, int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time, unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetEnergy\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP)"
.br
.ti -1c
.RI "bool \fBResetParameters\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBUpdate\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 17 of file neurotransmitter\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Neurotransmitter::Neurotransmitter ()\fC [inline]\fP"

.PP
Definition at line 20 of file neurotransmitter\&.h\&.
.SS "Neurotransmitter::Neurotransmitter (unsigned int object_type)\fC [inline]\fP"

.PP
Definition at line 22 of file neurotransmitter\&.h\&.
.SS "Neurotransmitter::Neurotransmitter (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 24 of file neurotransmitter\&.h\&.
.SS "Neurotransmitter::Neurotransmitter (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBCognitiveNetwork\fP & cognitivenetwork_connector)\fC [inline]\fP"

.PP
Definition at line 26 of file neurotransmitter\&.h\&.
.SS "virtual Neurotransmitter::~Neurotransmitter ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 38 of file neurotransmitter\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "unsigned int Neurotransmitter::GetCounter (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 40 of file neurotransmitter\&.h\&.
.SS "double Neurotransmitter::GetEnergy (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 41 of file neurotransmitter\&.h\&.
.SS "int Neurotransmitter::GetType (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 42 of file neurotransmitter\&.h\&.
.SS "bool Neurotransmitter::ResetParameters (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 19 of file neurotransmitter\&.cc\&.
.SS "\fBvoid\fP Neurotransmitter::SetCounter (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 45 of file neurotransmitter\&.h\&.
.SS "\fBvoid\fP Neurotransmitter::SetEnergy (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP"

.PP
Definition at line 46 of file neurotransmitter\&.h\&.
.SS "\fBvoid\fP Neurotransmitter::SetType (std::chrono::time_point< \fBClock\fP > event_time, int val)\fC [inline]\fP"

.PP
Definition at line 44 of file neurotransmitter\&.h\&.
.SS "int Neurotransmitter::Update (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 59 of file neurotransmitter\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
