.TH "node" 3 "Tue Oct 10 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
node
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <node\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBnode\fP (int xp, int yp, int d, int p)"
.br
.ti -1c
.RI "\fB~node\fP ()"
.br
.ti -1c
.RI "int \fBGetxPos\fP () const"
.br
.ti -1c
.RI "int \fBGetyPos\fP () const"
.br
.ti -1c
.RI "int \fBGetLevel\fP () const"
.br
.ti -1c
.RI "int \fBGetPriority\fP () const"
.br
.ti -1c
.RI "void \fBupdatePriority\fP (const int &xDest, const int &yDest)"
.br
.ti -1c
.RI "void \fBnextLevel\fP (const int &i)"
.br
.ti -1c
.RI "const int & \fBestimate\fP (const int &xDest, const int &yDest) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file node\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "node::node (int xp, int yp, int d, int p)\fC [inline]\fP"

.PP
Definition at line 27 of file node\&.h\&.
.SS "node::~node ()\fC [inline]\fP"

.PP
Definition at line 28 of file node\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "const int& node::estimate (const int & xDest, const int & yDest) const\fC [inline]\fP"

.PP
Definition at line 46 of file node\&.h\&.
.SS "int node::GetLevel () const\fC [inline]\fP"

.PP
Definition at line 31 of file node\&.h\&.
.SS "int node::GetPriority () const\fC [inline]\fP"

.PP
Definition at line 32 of file node\&.h\&.
.SS "int node::GetxPos () const\fC [inline]\fP"

.PP
Definition at line 29 of file node\&.h\&.
.SS "int node::GetyPos () const\fC [inline]\fP"

.PP
Definition at line 30 of file node\&.h\&.
.SS "void node::nextLevel (const int & i)\fC [inline]\fP"

.PP
Definition at line 40 of file node\&.h\&.
.SS "void node::updatePriority (const int & xDest, const int & yDest)\fC [inline]\fP"

.PP
Definition at line 34 of file node\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
