.TH "BrainHarmonics/node.h" 3 "Tue Oct 10 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BrainHarmonics/node.h
.SH SYNOPSIS
.br
.PP
\fC#include <math\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBnode\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBROBOTENGINEERING_NODE_H\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ROBOTENGINEERING_NODE_H"
< For Sine, Cosine, Power, Fabs & Sqrt functions 
.PP
Definition at line 12 of file node\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
