.TH "Orbital::s_CounterAdjustment" 3 "Sat Apr 29 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Orbital::s_CounterAdjustment \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <orbital\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBs_CounterAdjustment\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::chrono::time_point< std::chrono::high_resolution_clock > \fBs_CounterBegin\fP"
.br
.ti -1c
.RI "double * \fBs_PointToCounter\fP"
.br
.ti -1c
.RI "double \fBs_Pool\fP"
.br
.ti -1c
.RI "int \fBs_Interval\fP"
.br
.ti -1c
.RI "int \fBs_Shape\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 23 of file orbital\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Orbital::s_CounterAdjustment::s_CounterAdjustment ()\fC [inline]\fP"

.PP
Definition at line 25 of file orbital\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::chrono::time_point<std::chrono::high_resolution_clock> Orbital::s_CounterAdjustment::s_CounterBegin"

.PP
Definition at line 26 of file orbital\&.h\&.
.SS "int Orbital::s_CounterAdjustment::s_Interval"

.PP
Definition at line 29 of file orbital\&.h\&.
.SS "double* Orbital::s_CounterAdjustment::s_PointToCounter"

.PP
Definition at line 27 of file orbital\&.h\&.
.SS "double Orbital::s_CounterAdjustment::s_Pool"

.PP
Definition at line 28 of file orbital\&.h\&.
.SS "int Orbital::s_CounterAdjustment::s_Shape"

.PP
Definition at line 30 of file orbital\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
