.TH "BrainHarmonics/orbital.cc" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BrainHarmonics/orbital.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'neuron\&.h'\fP
.br
\fC#include 'orbital\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
