.TH "Polyhedron" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Polyhedron
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <polyhedron\&.h>\fP
.PP
Inherits \fBSolid\fP\&.
.PP
Inherited by \fBPolygon\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPolyhedron\fP ()"
.br
.ti -1c
.RI "\fBPolyhedron\fP (unsigned int object_type)"
.br
.ti -1c
.RI "\fBPolyhedron\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBPolyhedron\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBSolid\fP &solid_connector)"
.br
.ti -1c
.RI "virtual \fB~Polyhedron\fP ()"
.br
.ti -1c
.RI "bool \fBResetParameters\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "unsigned int \fBGetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetCounter\fP (unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetObjectType\fP (std::chrono::time_point< \fBClock\fP > event_time, unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBPolyhedron\fP * \fBCreatePolygon\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "std::vector< \fBPolyhedron\fP * > \fBCreatePolygons\fP (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"
.br
.ti -1c
.RI "\fBPolyhedron\fP * \fBClonePolygon\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBPolyhedron\fP *clone_object, double perfection_membership)"
.br
.ti -1c
.RI "std::vector< \fBPolyhedron\fP * > \fBClonePolygons\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBPolyhedron\fP *> cloning_list, double perfection_membership)"
.br
.ti -1c
.RI "\fBPolyhedron\fP * \fBDestroyPolygon\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBPolyhedron\fP *destroy_object)"
.br
.ti -1c
.RI "std::vector< \fBPolyhedron\fP * > \fBDestroyPolygons\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBPolyhedron\fP *> destruction_list)"
.br
.ti -1c
.RI "\fBPolyhedron\fP * \fBAddPolygon\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBPolyhedron\fP *add_object)"
.br
.ti -1c
.RI "std::vector< \fBPolyhedron\fP * > \fBAddPolygons\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBPolyhedron\fP *> add_objects)"
.br
.ti -1c
.RI "\fBPolyhedron\fP * \fBRemovePolygon\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "std::vector< \fBPolyhedron\fP * > \fBRemovePolygons\fP (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"
.br
.ti -1c
.RI "\fBPolyhedron\fP * \fBGetPolygon\fP (std::chrono::time_point< \fBClock\fP > event_time, int selector)"
.br
.ti -1c
.RI "std::vector< \fBPolyhedron\fP * > \fBGetPolygons\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBPoint\fP * \fBGetPoint\fP (std::chrono::time_point< \fBClock\fP > event_time, int selector)"
.br
.ti -1c
.RI "std::vector< \fBPoint\fP * > \fBGetPoints\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBGenerateSpherePoints\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "int \fBGenerateCylinderPoints\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBvoid\fP \fBUpdateCycle\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBPoint\fP *> set_of_update_pointers, unsigned int pointer_type)"
.br
.ti -1c
.RI "int \fBUpdate\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBPolyhedron\fP * > \fBpolygon_list\fP"
.br
.ti -1c
.RI "std::vector< \fBPoint\fP * > \fBpoint_list\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBSoma\fP"
.br
.ti -1c
.RI "class \fBMembrane\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 24 of file polyhedron\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Polyhedron::Polyhedron ()\fC [inline]\fP"

.PP
Definition at line 29 of file polyhedron\&.h\&.
.SS "Polyhedron::Polyhedron (unsigned int object_type)\fC [inline]\fP"

.PP
Definition at line 31 of file polyhedron\&.h\&.
.SS "Polyhedron::Polyhedron (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 33 of file polyhedron\&.h\&.
.SS "Polyhedron::Polyhedron (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBSolid\fP & solid_connector)\fC [inline]\fP"

.PP
Definition at line 35 of file polyhedron\&.h\&.
.SS "virtual Polyhedron::~Polyhedron ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 47 of file polyhedron\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBPolyhedron\fP * Polyhedron::AddPolygon (std::chrono::time_point< \fBClock\fP > event_time, \fBPolyhedron\fP * add_object)"

.PP
Definition at line 178 of file polyhedron\&.cc\&.
.SS "std::vector< \fBPolyhedron\fP * > Polyhedron::AddPolygons (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBPolyhedron\fP *> add_objects)"

.PP
Definition at line 189 of file polyhedron\&.cc\&.
.SS "\fBPolyhedron\fP * Polyhedron::ClonePolygon (std::chrono::time_point< \fBClock\fP > event_time, \fBPolyhedron\fP * clone_object, double perfection_membership)"

.PP
Definition at line 163 of file polyhedron\&.cc\&.
.SS "std::vector< \fBPolyhedron\fP * > Polyhedron::ClonePolygons (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBPolyhedron\fP *> cloning_list, double perfection_membership)"

.PP
Definition at line 158 of file polyhedron\&.cc\&.
.SS "\fBPolyhedron\fP * Polyhedron::CreatePolygon (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 126 of file polyhedron\&.cc\&.
.SS "std::vector< \fBPolyhedron\fP * > Polyhedron::CreatePolygons (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"

.PP
Definition at line 137 of file polyhedron\&.cc\&.
.SS "\fBPolyhedron\fP * Polyhedron::DestroyPolygon (std::chrono::time_point< \fBClock\fP > event_time, \fBPolyhedron\fP * destroy_object)"

.PP
Definition at line 173 of file polyhedron\&.cc\&.
.SS "std::vector< \fBPolyhedron\fP * > Polyhedron::DestroyPolygons (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBPolyhedron\fP *> destruction_list)"

.PP
Definition at line 168 of file polyhedron\&.cc\&.
.SS "int Polyhedron::GenerateCylinderPoints (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 325 of file polyhedron\&.cc\&.
.SS "int Polyhedron::GenerateSpherePoints (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 300 of file polyhedron\&.cc\&.
.SS "unsigned int Polyhedron::GetCounter (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 51 of file polyhedron\&.h\&.
.SS "\fBPoint\fP * Polyhedron::GetPoint (std::chrono::time_point< \fBClock\fP > event_time, int selector)"

.PP
Definition at line 232 of file polyhedron\&.cc\&.
.SS "std::vector< \fBPoint\fP * > Polyhedron::GetPoints (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 237 of file polyhedron\&.cc\&.
.SS "\fBPolyhedron\fP * Polyhedron::GetPolygon (std::chrono::time_point< \fBClock\fP > event_time, int selector)"

.PP
Definition at line 222 of file polyhedron\&.cc\&.
.SS "std::vector< \fBPolyhedron\fP * > Polyhedron::GetPolygons (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 227 of file polyhedron\&.cc\&.
.SS "\fBPolyhedron\fP * Polyhedron::RemovePolygon (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 211 of file polyhedron\&.cc\&.
.SS "std::vector< \fBPolyhedron\fP * > Polyhedron::RemovePolygons (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"

.PP
Definition at line 217 of file polyhedron\&.cc\&.
.SS "bool Polyhedron::ResetParameters (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 22 of file polyhedron\&.cc\&.
.SS "\fBvoid\fP Polyhedron::setCounter (unsigned int val)\fC [inline]\fP"

.PP
Definition at line 53 of file polyhedron\&.h\&.
.SS "\fBvoid\fP Polyhedron::SetObjectType (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)"

.PP
Definition at line 117 of file polyhedron\&.cc\&.
.SS "int Polyhedron::Update (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 265 of file polyhedron\&.cc\&.
.SS "\fBvoid\fP Polyhedron::UpdateCycle (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBPoint\fP *> set_of_update_pointers, unsigned int pointer_type)"

.PP
Definition at line 242 of file polyhedron\&.cc\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBMembrane\fP\fC [friend]\fP"

.PP
Definition at line 27 of file polyhedron\&.h\&.
.SS "friend class \fBSoma\fP\fC [friend]\fP"

.PP
Definition at line 26 of file polyhedron\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBPoint\fP*> Polyhedron::point_list\fC [protected]\fP"

.PP
Definition at line 95 of file polyhedron\&.h\&.
.SS "std::vector<\fBPolyhedron\fP*> Polyhedron::polygon_list\fC [protected]\fP"

.PP
Definition at line 94 of file polyhedron\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
