.TH "Polygon" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Polygon
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <polygon\&.h>\fP
.PP
Inherits \fBPolyhedron\fP\&.
.PP
Inherited by \fBQuad\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPolygon\fP ()"
.br
.ti -1c
.RI "\fBPolygon\fP (unsigned int object_type)"
.br
.ti -1c
.RI "\fBPolygon\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBPolygon\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBPolyhedron\fP &polyhedron_connector)"
.br
.ti -1c
.RI "virtual \fB~Polygon\fP ()"
.br
.ti -1c
.RI "bool \fBResetParameters\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "unsigned int \fBSetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time, unsigned int \fBval\fP)"
.br
.ti -1c
.RI "int \fBUpdate\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 24 of file polygon\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Polygon::Polygon ()\fC [inline]\fP"

.PP
Definition at line 27 of file polygon\&.h\&.
.SS "Polygon::Polygon (unsigned int object_type)\fC [inline]\fP"

.PP
Definition at line 29 of file polygon\&.h\&.
.SS "Polygon::Polygon (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 31 of file polygon\&.h\&.
.SS "Polygon::Polygon (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBPolyhedron\fP & polyhedron_connector)\fC [inline]\fP"

.PP
Definition at line 33 of file polygon\&.h\&.
.SS "virtual Polygon::~Polygon ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 45 of file polygon\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Polygon::ResetParameters (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 19 of file polygon\&.cc\&.
.SS "unsigned int Polygon::SetCounter (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 50 of file polygon\&.h\&.
.SS "\fBvoid\fP Polygon::SetCounter (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 52 of file polygon\&.h\&.
.SS "int Polygon::Update (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 58 of file polygon\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
