.TH "Polymer" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Polymer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <carbohydrates\&.h>\fP
.PP
Inherits \fBMonomer\fP, \fBUniverse\fP, \fBMonomer\fP, \fBMonomer\fP, \fBMonomer\fP, \fBMonomer\fP, \fBMonomer\fP, \fBMonomer\fP, \fBMonomer\fP, \fBMonomer\fP, and \fBMonomer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPolymer\fP (\fBMonomer\fP &mm)"
.br
.ti -1c
.RI "virtual \fB~Polymer\fP ()"
.br
.ti -1c
.RI "unsigned int \fBgetCounter\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetCounter\fP (unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcreation\fP ()"
.br
.ti -1c
.RI "\fBPolymer\fP (\fBMonomer\fP &mm)"
.br
.ti -1c
.RI "virtual \fB~Polymer\fP ()"
.br
.ti -1c
.RI "unsigned int \fBgetCounter\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetCounter\fP (unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcreation\fP ()"
.br
.ti -1c
.RI "\fBPolymer\fP (\fBMonomer\fP &mm)"
.br
.ti -1c
.RI "virtual \fB~Polymer\fP ()"
.br
.ti -1c
.RI "unsigned int \fBgetCounter\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetCounter\fP (unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcreation\fP ()"
.br
.ti -1c
.RI "\fBPolymer\fP (\fBMonomer\fP &mm)"
.br
.ti -1c
.RI "virtual \fB~Polymer\fP ()"
.br
.ti -1c
.RI "unsigned int \fBgetCounter\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetCounter\fP (unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcreation\fP ()"
.br
.ti -1c
.RI "\fBPolymer\fP (\fBMonomer\fP &mm)"
.br
.ti -1c
.RI "virtual \fB~Polymer\fP ()"
.br
.ti -1c
.RI "unsigned int \fBgetCounter\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetCounter\fP (unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcreation\fP ()"
.br
.ti -1c
.RI "\fBPolymer\fP (\fBMonomer\fP &mm)"
.br
.ti -1c
.RI "virtual \fB~Polymer\fP ()"
.br
.ti -1c
.RI "unsigned int \fBgetCounter\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetCounter\fP (unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcreation\fP ()"
.br
.ti -1c
.RI "\fBPolymer\fP (\fBMonomer\fP &mm)"
.br
.ti -1c
.RI "virtual \fB~Polymer\fP ()"
.br
.ti -1c
.RI "unsigned int \fBgetCounter\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetCounter\fP (unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcreation\fP ()"
.br
.ti -1c
.RI "\fBPolymer\fP (\fBMonomer\fP &mm)"
.br
.ti -1c
.RI "virtual \fB~Polymer\fP ()"
.br
.ti -1c
.RI "unsigned int \fBgetCounter\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetCounter\fP (unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcreation\fP ()"
.br
.ti -1c
.RI "\fBPolymer\fP (\fBMonomer\fP &mm)"
.br
.ti -1c
.RI "virtual \fB~Polymer\fP ()"
.br
.ti -1c
.RI "unsigned int \fBgetCounter\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetCounter\fP (unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcreation\fP ()"
.br
.ti -1c
.RI "\fBPolymer\fP ()"
.br
.ti -1c
.RI "\fBPolymer\fP (unsigned int object_type)"
.br
.ti -1c
.RI "\fBPolymer\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBPolymer\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBUniverse\fP &universe_connector)"
.br
.ti -1c
.RI "virtual \fB~Polymer\fP ()"
.br
.ti -1c
.RI "bool \fBResetParameters\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "unsigned int \fBGetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time, unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetPolymerLabel\fP (\fBstd::string\fP \fBval\fP)"
.br
.ti -1c
.RI "\fBstd::string\fP \fBGetPolymerLabel\fP ()"
.br
.ti -1c
.RI "int \fBUpdate\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBPolymer\fP (\fBMonomer\fP &mm)"
.br
.ti -1c
.RI "virtual \fB~Polymer\fP ()"
.br
.ti -1c
.RI "unsigned int \fBgetCounter\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetCounter\fP (unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcreation\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 24 of file carbohydrates\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Polymer::Polymer (\fBMonomer\fP & mm)\fC [inline]\fP"
Default constructor 
.PP
Definition at line 29 of file carbohydrates\&.h\&.
.SS "virtual Polymer::~Polymer ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 34 of file carbohydrates\&.h\&.
.SS "Polymer::Polymer (\fBMonomer\fP & mm)\fC [inline]\fP"
Default constructor 
.PP
Definition at line 29 of file cellmembrane\&.h\&.
.SS "virtual Polymer::~Polymer ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 34 of file cellmembrane\&.h\&.
.SS "Polymer::Polymer (\fBMonomer\fP & mm)\fC [inline]\fP"
Default constructor 
.PP
Definition at line 29 of file combinationmolecules\&.h\&.
.SS "virtual Polymer::~Polymer ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 34 of file combinationmolecules\&.h\&.
.SS "Polymer::Polymer (\fBMonomer\fP & mm)\fC [inline]\fP"
Default constructor 
.PP
Definition at line 29 of file cytoplasm\&.h\&.
.SS "virtual Polymer::~Polymer ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 34 of file cytoplasm\&.h\&.
.SS "Polymer::Polymer (\fBMonomer\fP & mm)\fC [inline]\fP"
Default constructor 
.PP
Definition at line 29 of file golgiapparatus\&.h\&.
.SS "virtual Polymer::~Polymer ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 34 of file golgiapparatus\&.h\&.
.SS "Polymer::Polymer (\fBMonomer\fP & mm)\fC [inline]\fP"
Default constructor 
.PP
Definition at line 29 of file lipids\&.h\&.
.SS "virtual Polymer::~Polymer ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 34 of file lipids\&.h\&.
.SS "Polymer::Polymer (\fBMonomer\fP & mm)\fC [inline]\fP"
Default constructor 
.PP
Definition at line 29 of file mitochondria\&.h\&.
.SS "virtual Polymer::~Polymer ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 34 of file mitochondria\&.h\&.
.SS "Polymer::Polymer (\fBMonomer\fP & mm)\fC [inline]\fP"
Default constructor 
.PP
Definition at line 29 of file nucleicacids\&.h\&.
.SS "virtual Polymer::~Polymer ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 34 of file nucleicacids\&.h\&.
.SS "Polymer::Polymer (\fBMonomer\fP & mm)\fC [inline]\fP"
Default constructor 
.PP
Definition at line 29 of file nucleus\&.h\&.
.SS "virtual Polymer::~Polymer ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 34 of file nucleus\&.h\&.
.SS "Polymer::Polymer ()\fC [inline]\fP"

.PP
Definition at line 28 of file polymer\&.h\&.
.SS "Polymer::Polymer (unsigned int object_type)\fC [inline]\fP"

.PP
Definition at line 30 of file polymer\&.h\&.
.SS "Polymer::Polymer (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 32 of file polymer\&.h\&.
.SS "Polymer::Polymer (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBUniverse\fP & universe_connector)\fC [inline]\fP"

.PP
Definition at line 34 of file polymer\&.h\&.
.SS "virtual Polymer::~Polymer ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 47 of file polymer\&.h\&.
.SS "Polymer::Polymer (\fBMonomer\fP & mm)\fC [inline]\fP"
Default constructor 
.PP
Definition at line 29 of file proteins\&.h\&.
.SS "virtual Polymer::~Polymer ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 34 of file proteins\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP Polymer::creation ()\fC [inline]\fP"

.PP
Definition at line 49 of file carbohydrates\&.h\&.
.SS "\fBvoid\fP Polymer::creation ()\fC [inline]\fP"

.PP
Definition at line 49 of file combinationmolecules\&.h\&.
.SS "\fBvoid\fP Polymer::creation ()\fC [inline]\fP"

.PP
Definition at line 49 of file lipids\&.h\&.
.SS "\fBvoid\fP Polymer::creation ()\fC [inline]\fP"

.PP
Definition at line 49 of file proteins\&.h\&.
.SS "\fBvoid\fP Polymer::creation ()\fC [inline]\fP"

.PP
Definition at line 49 of file mitochondria\&.h\&.
.SS "\fBvoid\fP Polymer::creation ()\fC [inline]\fP"

.PP
Definition at line 49 of file cellmembrane\&.h\&.
.SS "\fBvoid\fP Polymer::creation ()\fC [inline]\fP"

.PP
Definition at line 49 of file cytoplasm\&.h\&.
.SS "\fBvoid\fP Polymer::creation ()\fC [inline]\fP"

.PP
Definition at line 49 of file nucleicacids\&.h\&.
.SS "\fBvoid\fP Polymer::creation ()\fC [inline]\fP"

.PP
Definition at line 49 of file nucleus\&.h\&.
.SS "\fBvoid\fP Polymer::creation ()\fC [inline]\fP"

.PP
Definition at line 49 of file golgiapparatus\&.h\&.
.SS "unsigned int Polymer::getCounter ()\fC [inline]\fP"

.PP
Definition at line 36 of file lipids\&.h\&.
.SS "unsigned int Polymer::getCounter ()\fC [inline]\fP"

.PP
Definition at line 36 of file proteins\&.h\&.
.SS "unsigned int Polymer::getCounter ()\fC [inline]\fP"

.PP
Definition at line 36 of file cellmembrane\&.h\&.
.SS "unsigned int Polymer::getCounter ()\fC [inline]\fP"

.PP
Definition at line 36 of file mitochondria\&.h\&.
.SS "unsigned int Polymer::getCounter ()\fC [inline]\fP"

.PP
Definition at line 36 of file cytoplasm\&.h\&.
.SS "unsigned int Polymer::getCounter ()\fC [inline]\fP"

.PP
Definition at line 36 of file nucleicacids\&.h\&.
.SS "unsigned int Polymer::getCounter ()\fC [inline]\fP"

.PP
Definition at line 36 of file carbohydrates\&.h\&.
.SS "unsigned int Polymer::getCounter ()\fC [inline]\fP"

.PP
Definition at line 36 of file nucleus\&.h\&.
.SS "unsigned int Polymer::getCounter ()\fC [inline]\fP"

.PP
Definition at line 36 of file golgiapparatus\&.h\&.
.SS "unsigned int Polymer::getCounter ()\fC [inline]\fP"

.PP
Definition at line 36 of file combinationmolecules\&.h\&.
.SS "unsigned int Polymer::GetCounter (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 51 of file polymer\&.h\&.
.SS "\fBstd::string\fP Polymer::GetPolymerLabel ()\fC [inline]\fP"

.PP
Definition at line 57 of file polymer\&.h\&.
.SS "bool Polymer::ResetParameters (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 19 of file polymer\&.cc\&.
.SS "\fBvoid\fP Polymer::setCounter (unsigned int val)\fC [inline]\fP"

.PP
Definition at line 38 of file combinationmolecules\&.h\&.
.SS "\fBvoid\fP Polymer::setCounter (unsigned int val)\fC [inline]\fP"

.PP
Definition at line 38 of file cellmembrane\&.h\&.
.SS "\fBvoid\fP Polymer::setCounter (unsigned int val)\fC [inline]\fP"

.PP
Definition at line 38 of file proteins\&.h\&.
.SS "\fBvoid\fP Polymer::setCounter (unsigned int val)\fC [inline]\fP"

.PP
Definition at line 38 of file cytoplasm\&.h\&.
.SS "\fBvoid\fP Polymer::setCounter (unsigned int val)\fC [inline]\fP"

.PP
Definition at line 38 of file lipids\&.h\&.
.SS "\fBvoid\fP Polymer::setCounter (unsigned int val)\fC [inline]\fP"

.PP
Definition at line 38 of file nucleus\&.h\&.
.SS "\fBvoid\fP Polymer::setCounter (unsigned int val)\fC [inline]\fP"

.PP
Definition at line 38 of file nucleicacids\&.h\&.
.SS "\fBvoid\fP Polymer::setCounter (unsigned int val)\fC [inline]\fP"

.PP
Definition at line 38 of file carbohydrates\&.h\&.
.SS "\fBvoid\fP Polymer::setCounter (unsigned int val)\fC [inline]\fP"

.PP
Definition at line 38 of file golgiapparatus\&.h\&.
.SS "\fBvoid\fP Polymer::setCounter (unsigned int val)\fC [inline]\fP"

.PP
Definition at line 38 of file mitochondria\&.h\&.
.SS "\fBvoid\fP Polymer::SetCounter (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBMonomer\fP\&.
.PP
Definition at line 53 of file polymer\&.h\&.
.SS "\fBvoid\fP Polymer::SetPolymerLabel (\fBstd::string\fP val)\fC [inline]\fP"

.PP
Definition at line 55 of file polymer\&.h\&.
.SS "int Polymer::Update (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 58 of file polymer\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
