.TH "PriorityQueue< T, Number >" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PriorityQueue< T, Number >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef pair< Number, T > \fBPQElement\fP"
.br
.ti -1c
.RI "typedef pair< Number, T > \fBPQElement\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBempty\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBput\fP (T item, Number priority)"
.br
.ti -1c
.RI "T \fBget\fP ()"
.br
.ti -1c
.RI "bool \fBempty\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBput\fP (T item, Number priority)"
.br
.ti -1c
.RI "T \fBget\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "priority_queue< \fBPQElement\fP, vector< \fBPQElement\fP >, std::greater< \fBPQElement\fP > > \fBelements\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename T, typename Number = int>
.br
struct PriorityQueue< T, Number >"

.PP
Definition at line 190 of file implementation orig\&.cpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<typename T, typename Number = int> typedef pair<Number, T> \fBPriorityQueue\fP< T, Number >::\fBPQElement\fP"

.PP
Definition at line 191 of file implementation orig\&.cpp\&.
.SS "template<typename T, typename Number = int> typedef pair<Number, T> \fBPriorityQueue\fP< T, Number >::\fBPQElement\fP"

.PP
Definition at line 197 of file search\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "template<typename T, typename Number = int> bool \fBPriorityQueue\fP< T, Number >::empty ()\fC [inline]\fP"

.PP
Definition at line 195 of file implementation orig\&.cpp\&.
.SS "template<typename T, typename Number = int> bool \fBPriorityQueue\fP< T, Number >::empty ()\fC [inline]\fP"

.PP
Definition at line 201 of file search\&.cpp\&.
.SS "template<typename T, typename Number = int> T \fBPriorityQueue\fP< T, Number >::get ()\fC [inline]\fP"

.PP
Definition at line 201 of file implementation orig\&.cpp\&.
.SS "template<typename T, typename Number = int> T \fBPriorityQueue\fP< T, Number >::get ()\fC [inline]\fP"

.PP
Definition at line 207 of file search\&.cpp\&.
.SS "template<typename T, typename Number = int> \fBvoid\fP \fBPriorityQueue\fP< T, Number >::put (T item, Number priority)\fC [inline]\fP"

.PP
Definition at line 197 of file implementation orig\&.cpp\&.
.SS "template<typename T, typename Number = int> \fBvoid\fP \fBPriorityQueue\fP< T, Number >::put (T item, Number priority)\fC [inline]\fP"

.PP
Definition at line 203 of file search\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "template<typename T, typename Number = int> priority_queue< \fBPQElement\fP, vector< \fBPQElement\fP >, std::greater< \fBPQElement\fP > > \fBPriorityQueue\fP< T, Number >::elements"

.PP
Definition at line 193 of file implementation orig\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
