.TH "py_cmake.py" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
py_cmake.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBpy_cmake\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
