.TH "py_cmake" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
py_cmake
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBloader\fP = jinja2\&.FileSystemLoader(searchpath='{}'\&.\fBformat\fP(os\&.getcwd()))"
.br
.ti -1c
.RI "\fBstring\fP \fBfname\fP = 'vanilla_exec_lib'"
.br
.ti -1c
.RI "\fBenv\fP = jinja2\&.Environment(\fBloader\fP= \fBloader\fP)"
.br
.ti -1c
.RI "\fBtemplate\fP = env\&.get_template(\fBfname\fP)"
.br
.ti -1c
.RI "list \fBcpp_files\fP = [ele for ele \fBin\fP os\&.listdir() if '\&.cpp' in ele]"
.br
.RI "now do the regular expression looking through the present directory for the cpp files "
.ti -1c
.RI "list \fBprefixes\fP = [ele\&.split('\&.')[0] for ele \fBin\fP \fBcpp_files\fP]"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "list py_cmake\&.cpp_files = [ele for ele \fBin\fP os\&.listdir() if '\&.cpp' in ele]"

.PP
now do the regular expression looking through the present directory for the cpp files 
.PP
Definition at line 15 of file py_cmake\&.py\&.
.SS "py_cmake\&.env = jinja2\&.Environment(\fBloader\fP= \fBloader\fP)"

.PP
Definition at line 9 of file py_cmake\&.py\&.
.SS "\fBstring\fP py_cmake\&.fname = 'vanilla_exec_lib'"

.PP
Definition at line 4 of file py_cmake\&.py\&.
.SS "py_cmake\&.loader = jinja2\&.FileSystemLoader(searchpath='{}'\&.\fBformat\fP(os\&.getcwd()))"

.PP
Definition at line 3 of file py_cmake\&.py\&.
.SS "list py_cmake\&.prefixes = [ele\&.split('\&.')[0] for ele \fBin\fP \fBcpp_files\fP]"

.PP
Definition at line 16 of file py_cmake\&.py\&.
.SS "py_cmake\&.template = env\&.get_template(\fBfname\fP)"

.PP
Definition at line 11 of file py_cmake\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
