.TH "pycompute" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pycompute
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmultiply\fP (\fBa\fP, \fBb\fP)"
.br
.ti -1c
.RI "def \fBmlkmeans\fP (\fBa\fP, \fBb\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def pycompute\&.mlkmeans ( a,  b)"

.PP
Definition at line 10 of file pycompute\&.py\&.
.SS "def pycompute\&.multiply ( a,  b)"

.PP
Definition at line 3 of file pycompute\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
