.TH "/Users/pbisaacs/Developer/BrainHarmonics/BrainHarmonics/resourcepath.cc" 3 "Sat Apr 29 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/pbisaacs/Developer/BrainHarmonics/BrainHarmonics/resourcepath.cc \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ResourcePath\&.h'\fP
.br
\fC#import <Foundation/Foundation\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSFML_RESOURCE_PATH_CC\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "std::string \fBresourcePath\fP (void)"
.br
.RI "\fIReturn the path to the resource folder\&. \fP"
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SFML_RESOURCE_PATH_CC"

.PP
Definition at line 27 of file resourcepath\&.cc\&.
.SH "Function Documentation"
.PP 
.SS "std::string resourcePath (void)"

.PP
Return the path to the resource folder\&. 
.PP
\fBReturns:\fP
.RS 4
The path to the resource folder associate with the main bundle or an empty string is there is no bundle\&. 
.RE
.PP

.PP
Definition at line 36 of file resourcepath\&.cc\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
