.TH "BrainHarmonics/screenlist.hpp" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BrainHarmonics/screenlist.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'screen_0\&.hpp'\fP
.br
\fC#include 'screen_1\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
