.TH "BrainHarmonics/screenlist.cpp" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BrainHarmonics/screenlist.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'screenlist\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
