.TH "Screen_1" 3 "Sat Apr 29 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Screen_1 \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMultiScreen\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScreen_1\fP ()"
.br
.ti -1c
.RI "virtual \fB~Screen_1\fP ()"
.br
.ti -1c
.RI "void \fBcreation\fP ()"
.br
.ti -1c
.RI "virtual int \fBrunScreen\fP (sf::RenderWindow &app)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 904 of file main\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Screen_1::Screen_1 ()"
Default constructor 
.PP
Definition at line 919 of file main\&.cc\&.
.SS "virtual Screen_1::~Screen_1 ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 910 of file main\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void Screen_1::creation ()"

.PP
Definition at line 923 of file main\&.cc\&.
.SS "int Screen_1::runScreen (sf::RenderWindow & app)\fC [virtual]\fP"

.PP
Implements \fBMultiScreen\fP\&.
.PP
Definition at line 925 of file main\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
