.TH "Screen_0" 3 "Sat Apr 29 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Screen_0 \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMultiScreen\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScreen_0\fP ()"
.br
.ti -1c
.RI "virtual \fB~Screen_0\fP ()"
.br
.ti -1c
.RI "void \fBcreation\fP ()"
.br
.ti -1c
.RI "virtual int \fBrunScreen\fP (sf::RenderWindow &app)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 807 of file main\&.cc\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Screen_0::Screen_0 ()"
Default constructor 
.PP
Definition at line 822 of file main\&.cc\&.
.SS "virtual Screen_0::~Screen_0 ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 813 of file main\&.cc\&.
.SH "Member Function Documentation"
.PP 
.SS "void Screen_0::creation ()"

.PP
Definition at line 826 of file main\&.cc\&.
.SS "int Screen_0::runScreen (sf::RenderWindow & app)\fC [virtual]\fP"

.PP
Implements \fBMultiScreen\fP\&.
.PP
Definition at line 828 of file main\&.cc\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
