.TH "opengl/common/shader.hpp" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
opengl/common/shader.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'common\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBGLuint\fP \fBLoadShaders\fP (const char *vertex_file_path, const char *fragment_file_path, const char *tcs_file_path, const char *tes_file_path)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBGLuint\fP LoadShaders (const char * vertex_file_path, const char * fragment_file_path, const char * tcs_file_path, const char * tes_file_path)"

.PP
Definition at line 49 of file shader\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
