.TH "BrainHarmonics/CMakeFiles/CheckTypeSize/SIZEOF_VOID_PTR.c" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BrainHarmonics/CMakeFiles/CheckTypeSize/SIZEOF_VOID_PTR.c
.SH SYNOPSIS
.br
.PP
\fC#include <sys/types\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSIZE\fP   (sizeof(\fBvoid\fP *))"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SIZE   (sizeof(\fBvoid\fP *))"

.PP
Definition at line 23 of file SIZEOF_VOID_PTR\&.c\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 39 of file SIZEOF_VOID_PTR\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
