.TH "Sniffex::sniff_ip" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sniffex::sniff_ip
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sniffex\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "u_char \fBip_vhl\fP"
.br
.ti -1c
.RI "u_char \fBip_tos\fP"
.br
.ti -1c
.RI "u_short \fBip_len\fP"
.br
.ti -1c
.RI "u_short \fBip_id\fP"
.br
.ti -1c
.RI "u_short \fBip_off\fP"
.br
.ti -1c
.RI "u_char \fBip_ttl\fP"
.br
.ti -1c
.RI "u_char \fBip_p\fP"
.br
.ti -1c
.RI "u_short \fBip_sum\fP"
.br
.ti -1c
.RI "struct in_addr ip_src \fBip_dst\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 244 of file sniffex\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "struct in_addr ip_src Sniffex::sniff_ip::ip_dst"

.PP
Definition at line 257 of file sniffex\&.h\&.
.SS "u_short Sniffex::sniff_ip::ip_id"

.PP
Definition at line 248 of file sniffex\&.h\&.
.SS "u_short Sniffex::sniff_ip::ip_len"

.PP
Definition at line 247 of file sniffex\&.h\&.
.SS "u_short Sniffex::sniff_ip::ip_off"

.PP
Definition at line 249 of file sniffex\&.h\&.
.SS "u_char Sniffex::sniff_ip::ip_p"

.PP
Definition at line 255 of file sniffex\&.h\&.
.SS "u_short Sniffex::sniff_ip::ip_sum"

.PP
Definition at line 256 of file sniffex\&.h\&.
.SS "u_char Sniffex::sniff_ip::ip_tos"

.PP
Definition at line 246 of file sniffex\&.h\&.
.SS "u_char Sniffex::sniff_ip::ip_ttl"

.PP
Definition at line 254 of file sniffex\&.h\&.
.SS "u_char Sniffex::sniff_ip::ip_vhl"

.PP
Definition at line 245 of file sniffex\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
