.TH "sniff_ip" 3 "Sat Apr 29 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sniff_ip \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sniffex\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "u_char \fBip_vhl\fP"
.br
.ti -1c
.RI "u_char \fBip_tos\fP"
.br
.ti -1c
.RI "u_short \fBip_len\fP"
.br
.ti -1c
.RI "u_short \fBip_id\fP"
.br
.ti -1c
.RI "u_short \fBip_off\fP"
.br
.ti -1c
.RI "u_char \fBip_ttl\fP"
.br
.ti -1c
.RI "u_char \fBip_p\fP"
.br
.ti -1c
.RI "u_short \fBip_sum\fP"
.br
.ti -1c
.RI "struct in_addr ip_src \fBip_dst\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 240 of file sniffex\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "struct in_addr ip_src sniff_ip::ip_dst"

.PP
Definition at line 253 of file sniffex\&.h\&.
.SS "u_short sniff_ip::ip_id"

.PP
Definition at line 244 of file sniffex\&.h\&.
.SS "u_short sniff_ip::ip_len"

.PP
Definition at line 243 of file sniffex\&.h\&.
.SS "u_short sniff_ip::ip_off"

.PP
Definition at line 245 of file sniffex\&.h\&.
.SS "u_char sniff_ip::ip_p"

.PP
Definition at line 251 of file sniffex\&.h\&.
.SS "u_short sniff_ip::ip_sum"

.PP
Definition at line 252 of file sniffex\&.h\&.
.SS "u_char sniff_ip::ip_tos"

.PP
Definition at line 242 of file sniffex\&.h\&.
.SS "u_char sniff_ip::ip_ttl"

.PP
Definition at line 250 of file sniffex\&.h\&.
.SS "u_char sniff_ip::ip_vhl"

.PP
Definition at line 241 of file sniffex\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
