.TH "sniff_tcp" 3 "Sat Apr 29 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sniff_tcp \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sniffex\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "u_short \fBth_sport\fP"
.br
.ti -1c
.RI "u_short \fBth_dport\fP"
.br
.ti -1c
.RI "\fBtcp_seq\fP \fBth_seq\fP"
.br
.ti -1c
.RI "\fBtcp_seq\fP \fBth_ack\fP"
.br
.ti -1c
.RI "u_char \fBth_offx2\fP"
.br
.ti -1c
.RI "u_char \fBth_flags\fP"
.br
.ti -1c
.RI "u_short \fBth_win\fP"
.br
.ti -1c
.RI "u_short \fBth_sum\fP"
.br
.ti -1c
.RI "u_short \fBth_urp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 261 of file sniffex\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBtcp_seq\fP sniff_tcp::th_ack"

.PP
Definition at line 265 of file sniffex\&.h\&.
.SS "u_short sniff_tcp::th_dport"

.PP
Definition at line 263 of file sniffex\&.h\&.
.SS "u_char sniff_tcp::th_flags"

.PP
Definition at line 268 of file sniffex\&.h\&.
.SS "u_char sniff_tcp::th_offx2"

.PP
Definition at line 266 of file sniffex\&.h\&.
.SS "\fBtcp_seq\fP sniff_tcp::th_seq"

.PP
Definition at line 264 of file sniffex\&.h\&.
.SS "u_short sniff_tcp::th_sport"

.PP
Definition at line 262 of file sniffex\&.h\&.
.SS "u_short sniff_tcp::th_sum"

.PP
Definition at line 279 of file sniffex\&.h\&.
.SS "u_short sniff_tcp::th_urp"

.PP
Definition at line 280 of file sniffex\&.h\&.
.SS "u_short sniff_tcp::th_win"

.PP
Definition at line 278 of file sniffex\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
