.TH "Sniffex::sniff_ethernet" 3 "Tue Oct 10 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Sniffex::sniff_ethernet
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sniffex\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "u_char \fBether_dhost\fP [\fBETHER_ADDR_LEN\fP]"
.br
.ti -1c
.RI "u_char \fBether_shost\fP [\fBETHER_ADDR_LEN\fP]"
.br
.ti -1c
.RI "u_short \fBether_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 237 of file sniffex\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "u_char Sniffex::sniff_ethernet::ether_dhost[\fBETHER_ADDR_LEN\fP]"

.PP
Definition at line 238 of file sniffex\&.h\&.
.SS "u_char Sniffex::sniff_ethernet::ether_shost[\fBETHER_ADDR_LEN\fP]"

.PP
Definition at line 239 of file sniffex\&.h\&.
.SS "u_short Sniffex::sniff_ethernet::ether_type"

.PP
Definition at line 240 of file sniffex\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
