.TH "sniff_ethernet" 3 "Sat Apr 29 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sniff_ethernet \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sniffex\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "u_char \fBether_dhost\fP [\fBETHER_ADDR_LEN\fP]"
.br
.ti -1c
.RI "u_char \fBether_shost\fP [\fBETHER_ADDR_LEN\fP]"
.br
.ti -1c
.RI "u_short \fBether_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 233 of file sniffex\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "u_char sniff_ethernet::ether_dhost[\fBETHER_ADDR_LEN\fP]"

.PP
Definition at line 234 of file sniffex\&.h\&.
.SS "u_char sniff_ethernet::ether_shost[\fBETHER_ADDR_LEN\fP]"

.PP
Definition at line 235 of file sniffex\&.h\&.
.SS "u_short sniff_ethernet::ether_type"

.PP
Definition at line 236 of file sniffex\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
