.TH "BrainHarmonics/solid.cc" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BrainHarmonics/solid.cc
.SH SYNOPSIS
.br
.PP
\fC#include 'solid\&.h'\fP
.br
\fC#include 'polyhedron\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
