.TH "Solid" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Solid
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <solid\&.h>\fP
.PP
Inherits \fBUniverse\fP\&.
.PP
Inherited by \fBPolyhedron\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSolid\fP ()"
.br
.ti -1c
.RI "\fBSolid\fP (unsigned int object_type)"
.br
.ti -1c
.RI "\fBSolid\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBSolid\fP (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBUniverse\fP &universe_connector)"
.br
.ti -1c
.RI "virtual \fB~Solid\fP ()"
.br
.ti -1c
.RI "bool \fBResetParameters\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "unsigned int \fBGetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetCounter\fP (std::chrono::time_point< \fBClock\fP > event_time, unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetObjectType\fP (std::chrono::time_point< \fBClock\fP > event_time, unsigned int \fBval\fP)"
.br
.ti -1c
.RI "\fBSolid\fP * \fBCreatePolyhedron\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "std::vector< \fBSolid\fP * > \fBCreatePolyhedrons\fP (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"
.br
.ti -1c
.RI "\fBSolid\fP * \fBClonePolyhedron\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBSolid\fP *clone_object, double perfection_membership)"
.br
.ti -1c
.RI "std::vector< \fBSolid\fP * > \fBClonePolyhedrons\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBSolid\fP *> cloning_list, double perfection_membership)"
.br
.ti -1c
.RI "\fBSolid\fP * \fBDestroyPolyhedron\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBSolid\fP *destroy_object)"
.br
.ti -1c
.RI "std::vector< \fBSolid\fP * > \fBDestroyPolyhedrons\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBSolid\fP *> destruction_list)"
.br
.ti -1c
.RI "\fBSolid\fP * \fBAddPolyhedron\fP (std::chrono::time_point< \fBClock\fP > event_time, \fBSolid\fP *add_object)"
.br
.ti -1c
.RI "std::vector< \fBSolid\fP * > \fBAddPolyhedrons\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBSolid\fP *> add_objects)"
.br
.ti -1c
.RI "\fBSolid\fP * \fBRemovePolyhedron\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "std::vector< \fBSolid\fP * > \fBRemovePolyhedrons\fP (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"
.br
.ti -1c
.RI "\fBSolid\fP * \fBGetPolyhedron\fP (std::chrono::time_point< \fBClock\fP > event_time, int selector)"
.br
.ti -1c
.RI "std::vector< \fBSolid\fP * > \fBGetPolyhedrons\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBvoid\fP \fBGluePolyhedrons\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBvoid\fP \fBUpdateCycle\fP (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBSolid\fP *> set_of_update_pointers, unsigned int pointer_type)"
.br
.ti -1c
.RI "int \fBUpdate\fP (std::chrono::time_point< \fBClock\fP > event_time)"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetCharge\fP (std::chrono::time_point< \fBClock\fP > event_time, int \fBval\fP) final"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetSpin\fP (std::chrono::time_point< \fBClock\fP > event_time, int \fBval\fP) final"
.br
.ti -1c
.RI "double \fBGetGravitation\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBGetWeak\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBGetWeakElectroweak\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBGetElectromagnetic\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBGetElectromagneticElectroweak\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBGetStrong\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBGetStrongFundamental\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBGetStrongResidual\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.ti -1c
.RI "double \fBApplyGravitation\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "double \fBApplyWeak\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "double \fBApplyWeakElectroweak\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "double \fBApplyElectromagnetic\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "double \fBApplyElectromagneticElectroweak\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "double \fBApplyStrong\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "double \fBApplyStrongFundamental\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "double \fBApplyStrongResidual\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetGravitation\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetWeak\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetWeakElectroweak\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetElectromagnetic\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetElectromagneticElectroweak\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetStrong\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetStrongFundamental\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "\fBvoid\fP \fBSetStrongResidual\fP (std::chrono::time_point< \fBClock\fP > event_time, double \fBval\fP) final"
.br
.ti -1c
.RI "\fBvoid\fP \fBPollElementaryForce\fP (std::chrono::time_point< \fBClock\fP > event_time) final"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBSolid\fP * > \fBpolyhedron_list\fP"
.br
.ti -1c
.RI "std::vector< unsigned int > \fBpoly_type_list\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBCognitiveNetwork\fP"
.br
.ti -1c
.RI "class \fBNeuron\fP"
.br
.ti -1c
.RI "class \fBSoma\fP"
.br
.ti -1c
.RI "class \fBMembrane\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 23 of file solid\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Solid::Solid ()\fC [inline]\fP"

.PP
Definition at line 31 of file solid\&.h\&.
.SS "Solid::Solid (unsigned int object_type)\fC [inline]\fP"

.PP
Definition at line 33 of file solid\&.h\&.
.SS "Solid::Solid (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP"

.PP
Definition at line 35 of file solid\&.h\&.
.SS "Solid::Solid (unsigned int object_type, std::chrono::time_point< \fBClock\fP > event_time, \fBUniverse\fP & universe_connector)\fC [inline]\fP"

.PP
Definition at line 37 of file solid\&.h\&.
.SS "virtual Solid::~Solid ()\fC [inline]\fP, \fC [virtual]\fP"
Default destructor 
.PP
Definition at line 50 of file solid\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSolid\fP * Solid::AddPolyhedron (std::chrono::time_point< \fBClock\fP > event_time, \fBSolid\fP * add_object)"

.PP
Definition at line 162 of file solid\&.cc\&.
.SS "std::vector< \fBSolid\fP * > Solid::AddPolyhedrons (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBSolid\fP *> add_objects)"

.PP
Definition at line 173 of file solid\&.cc\&.
.SS "double Solid::ApplyElectromagnetic (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 104 of file solid\&.h\&.
.SS "double Solid::ApplyElectromagneticElectroweak (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 105 of file solid\&.h\&.
.SS "double Solid::ApplyGravitation (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 101 of file solid\&.h\&.
.SS "double Solid::ApplyStrong (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 106 of file solid\&.h\&.
.SS "double Solid::ApplyStrongFundamental (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 107 of file solid\&.h\&.
.SS "double Solid::ApplyStrongResidual (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 108 of file solid\&.h\&.
.SS "double Solid::ApplyWeak (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 102 of file solid\&.h\&.
.SS "double Solid::ApplyWeakElectroweak (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 103 of file solid\&.h\&.
.SS "\fBSolid\fP * Solid::ClonePolyhedron (std::chrono::time_point< \fBClock\fP > event_time, \fBSolid\fP * clone_object, double perfection_membership)"

.PP
Definition at line 147 of file solid\&.cc\&.
.SS "std::vector< \fBSolid\fP * > Solid::ClonePolyhedrons (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBSolid\fP *> cloning_list, double perfection_membership)"

.PP
Definition at line 142 of file solid\&.cc\&.
.SS "\fBSolid\fP * Solid::CreatePolyhedron (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 109 of file solid\&.cc\&.
.SS "std::vector< \fBSolid\fP * > Solid::CreatePolyhedrons (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"

.PP
Definition at line 120 of file solid\&.cc\&.
.SS "\fBSolid\fP * Solid::DestroyPolyhedron (std::chrono::time_point< \fBClock\fP > event_time, \fBSolid\fP * destroy_object)"

.PP
Definition at line 157 of file solid\&.cc\&.
.SS "std::vector< \fBSolid\fP * > Solid::DestroyPolyhedrons (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBSolid\fP *> destruction_list)"

.PP
Definition at line 152 of file solid\&.cc\&.
.SS "unsigned int Solid::GetCounter (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 96 of file solid\&.cc\&.
.SS "double Solid::GetElectromagnetic (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 95 of file solid\&.h\&.
.SS "double Solid::GetElectromagneticElectroweak (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 96 of file solid\&.h\&.
.SS "double Solid::GetGravitation (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 92 of file solid\&.h\&.
.SS "\fBSolid\fP * Solid::GetPolyhedron (std::chrono::time_point< \fBClock\fP > event_time, int selector)"

.PP
Definition at line 206 of file solid\&.cc\&.
.SS "std::vector< \fBSolid\fP * > Solid::GetPolyhedrons (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 211 of file solid\&.cc\&.
.SS "double Solid::GetStrong (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 97 of file solid\&.h\&.
.SS "double Solid::GetStrongFundamental (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 98 of file solid\&.h\&.
.SS "double Solid::GetStrongResidual (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 99 of file solid\&.h\&.
.SS "double Solid::GetWeak (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 93 of file solid\&.h\&.
.SS "double Solid::GetWeakElectroweak (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 94 of file solid\&.h\&.
.SS "\fBvoid\fP Solid::GluePolyhedrons (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 216 of file solid\&.cc\&.
.SS "\fBvoid\fP Solid::PollElementaryForce (std::chrono::time_point< \fBClock\fP > event_time)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 119 of file solid\&.h\&.
.SS "\fBSolid\fP * Solid::RemovePolyhedron (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 195 of file solid\&.cc\&.
.SS "std::vector< \fBSolid\fP * > Solid::RemovePolyhedrons (std::chrono::time_point< \fBClock\fP > event_time, int quantity)"

.PP
Definition at line 201 of file solid\&.cc\&.
.SS "bool Solid::ResetParameters (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 20 of file solid\&.cc\&.
.SS "\fBvoid\fP Solid::SetCharge (std::chrono::time_point< \fBClock\fP > event_time, int val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 90 of file solid\&.h\&.
.SS "\fBvoid\fP Solid::SetCounter (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)\fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 98 of file solid\&.cc\&.
.SS "\fBvoid\fP Solid::SetElectromagnetic (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 113 of file solid\&.h\&.
.SS "\fBvoid\fP Solid::SetElectromagneticElectroweak (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 114 of file solid\&.h\&.
.SS "\fBvoid\fP Solid::SetGravitation (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 110 of file solid\&.h\&.
.SS "\fBvoid\fP Solid::SetObjectType (std::chrono::time_point< \fBClock\fP > event_time, unsigned int val)"

.PP
Definition at line 100 of file solid\&.cc\&.
.SS "\fBvoid\fP Solid::SetSpin (std::chrono::time_point< \fBClock\fP > event_time, int val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 91 of file solid\&.h\&.
.SS "\fBvoid\fP Solid::SetStrong (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 115 of file solid\&.h\&.
.SS "\fBvoid\fP Solid::SetStrongFundamental (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 116 of file solid\&.h\&.
.SS "\fBvoid\fP Solid::SetStrongResidual (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 117 of file solid\&.h\&.
.SS "\fBvoid\fP Solid::SetWeak (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 111 of file solid\&.h\&.
.SS "\fBvoid\fP Solid::SetWeakElectroweak (std::chrono::time_point< \fBClock\fP > event_time, double val)\fC [inline]\fP, \fC [final]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBUniverse\fP\&.
.PP
Definition at line 112 of file solid\&.h\&.
.SS "int Solid::Update (std::chrono::time_point< \fBClock\fP > event_time)"

.PP
Definition at line 244 of file solid\&.cc\&.
.SS "\fBvoid\fP Solid::UpdateCycle (std::chrono::time_point< \fBClock\fP > event_time, std::vector< \fBSolid\fP *> set_of_update_pointers, unsigned int pointer_type)"

.PP
Definition at line 221 of file solid\&.cc\&.
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBCognitiveNetwork\fP\fC [friend]\fP"

.PP
Definition at line 25 of file solid\&.h\&.
.SS "friend class \fBMembrane\fP\fC [friend]\fP"

.PP
Definition at line 28 of file solid\&.h\&.
.SS "friend class \fBNeuron\fP\fC [friend]\fP"

.PP
Definition at line 26 of file solid\&.h\&.
.SS "friend class \fBSoma\fP\fC [friend]\fP"

.PP
Definition at line 27 of file solid\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "std::vector<unsigned int> Solid::poly_type_list\fC [protected]\fP"

.PP
Definition at line 129 of file solid\&.h\&.
.SS "std::vector<\fBSolid\fP*> Solid::polyhedron_list\fC [protected]\fP"

.PP
Definition at line 128 of file solid\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
