.TH "Soma::ObjectConnection" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Soma::ObjectConnection
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <soma\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBobject_one_type\fP"
.br
.ti -1c
.RI "int \fBobject_one\fP"
.br
.ti -1c
.RI "int \fBobject_two_type\fP"
.br
.ti -1c
.RI "int \fBobject_two\fP"
.br
.ti -1c
.RI "double \fBobject_connection_strength\fP"
.br
.ti -1c
.RI "double \fBobject_connection_modifier\fP"
.br
.ti -1c
.RI "double \fBobject_two_position\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 131 of file soma\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double Soma::ObjectConnection::object_connection_modifier"

.PP
Definition at line 138 of file soma\&.h\&.
.SS "double Soma::ObjectConnection::object_connection_strength"

.PP
Definition at line 137 of file soma\&.h\&.
.SS "int Soma::ObjectConnection::object_one"

.PP
Definition at line 134 of file soma\&.h\&.
.SS "int Soma::ObjectConnection::object_one_type"

.PP
Definition at line 133 of file soma\&.h\&.
.SS "int Soma::ObjectConnection::object_two"

.PP
Definition at line 136 of file soma\&.h\&.
.SS "double Soma::ObjectConnection::object_two_position"

.PP
Definition at line 139 of file soma\&.h\&.
.SS "int Soma::ObjectConnection::object_two_type"

.PP
Definition at line 135 of file soma\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
