.TH "SquareGrid" 3 "Tue Oct 10 2017" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SquareGrid
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBGridWithWeights\fP, and \fBGridWithWeights\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef tuple< int, int > \fBLocation\fP"
.br
.ti -1c
.RI "typedef tuple< int, int > \fBLocation\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSquareGrid\fP (int width_, int height_)"
.br
.ti -1c
.RI "bool \fBin_bounds\fP (\fBLocation\fP id)"
.br
.ti -1c
.RI "bool \fBpassable\fP (\fBLocation\fP id)"
.br
.ti -1c
.RI "vector< \fBLocation\fP > \fBneighbors\fP (\fBLocation\fP id)"
.br
.ti -1c
.RI "\fBSquareGrid\fP (int width_, int height_)"
.br
.ti -1c
.RI "bool \fBin_bounds\fP (\fBLocation\fP id)"
.br
.ti -1c
.RI "bool \fBpassable\fP (\fBLocation\fP id)"
.br
.ti -1c
.RI "vector< \fBLocation\fP > \fBneighbors\fP (\fBLocation\fP id)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "unordered_set< \fBLocation\fP > \fBwalls\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static array< \fBLocation\fP, 4 > \fBDIRS\fP {\fBLocation\fP{1, 0}, \fBLocation\fP{0, \-1}, \fBLocation\fP{\-1, 0}, \fBLocation\fP{0, 1}}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 104 of file implementation orig\&.cpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "typedef tuple<int,int> \fBSquareGrid::Location\fP"

.PP
Definition at line 105 of file implementation orig\&.cpp\&.
.SS "typedef tuple<int,int> \fBSquareGrid::Location\fP"

.PP
Definition at line 111 of file search\&.cpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SquareGrid::SquareGrid (int width_, int height_)\fC [inline]\fP"

.PP
Definition at line 111 of file implementation orig\&.cpp\&.
.SS "SquareGrid::SquareGrid (int width_, int height_)\fC [inline]\fP"

.PP
Definition at line 117 of file search\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SquareGrid::in_bounds (\fBLocation\fP id)\fC [inline]\fP"

.PP
Definition at line 114 of file implementation orig\&.cpp\&.
.SS "bool SquareGrid::in_bounds (\fBLocation\fP id)\fC [inline]\fP"

.PP
Definition at line 120 of file search\&.cpp\&.
.SS "vector<\fBLocation\fP> SquareGrid::neighbors (\fBLocation\fP id)\fC [inline]\fP"

.PP
Definition at line 124 of file implementation orig\&.cpp\&.
.SS "vector<\fBLocation\fP> SquareGrid::neighbors (\fBLocation\fP id)\fC [inline]\fP"

.PP
Definition at line 130 of file search\&.cpp\&.
.SS "bool SquareGrid::passable (\fBLocation\fP id)\fC [inline]\fP"

.PP
Definition at line 120 of file implementation orig\&.cpp\&.
.SS "bool SquareGrid::passable (\fBLocation\fP id)\fC [inline]\fP"

.PP
Definition at line 126 of file search\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "array< \fBSquareGrid::Location\fP, 4 > SquareGrid::DIRS {\fBLocation\fP{1, 0}, \fBLocation\fP{0, \-1}, \fBLocation\fP{\-1, 0}, \fBLocation\fP{0, 1}}\fC [static]\fP"

.PP
Definition at line 106 of file implementation orig\&.cpp\&.
.SS "int SquareGrid::height"

.PP
Definition at line 108 of file implementation orig\&.cpp\&.
.SS "unordered_set< \fBLocation\fP > SquareGrid::walls"

.PP
Definition at line 109 of file implementation orig\&.cpp\&.
.SS "int SquareGrid::width"

.PP
Definition at line 108 of file implementation orig\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
