.TH "transition_text.cpp" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
transition_text.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <glad/glad\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <GLFW/glfw3\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'common/shader\&.hpp'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 9 of file transition_text\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
