.TH "triangles.cpp" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
triangles.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <glad/glad\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <GLFW/glfw3\&.h>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBVertex\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBGLfloat\fP \fBgfloat\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBmakeTriangle\fP (vector< \fBVertex\fP > vct)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmakeTriangles\fP (vector< vector< \fBVertex\fP >> vct)"
.br
.ti -1c
.RI "\fBgfloat\fP \fBrandCeil\fP (float ceil)"
.br
.ti -1c
.RI "\fBvoid\fP \fBtrianglesSet\fP (int number, int \fBheight\fP, int \fBwidth\fP)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "vector< vector< \fBVertex\fP > > \fBall_v\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBGLfloat\fP \fBgfloat\fP"

.PP
Definition at line 13 of file triangles\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Definition at line 85 of file triangles\&.cpp\&.
.SS "\fBvoid\fP makeTriangle (vector< \fBVertex\fP > vct)"

.PP
Definition at line 26 of file triangles\&.cpp\&.
.SS "\fBvoid\fP makeTriangles (vector< vector< \fBVertex\fP >> vct)"

.PP
Definition at line 39 of file triangles\&.cpp\&.
.SS "\fBgfloat\fP randCeil (float ceil)"

.PP
Definition at line 50 of file triangles\&.cpp\&.
.SS "\fBvoid\fP trianglesSet (int number, int height, int width)"

.PP
Definition at line 65 of file triangles\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "vector<vector<\fBVertex\fP> > all_v"

.PP
Definition at line 20 of file triangles\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
