.TH "Vertex" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vertex
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBgfloat\fP \fBx\fP"
.br
.ti -1c
.RI "\fBgfloat\fP \fBy\fP"
.br
.ti -1c
.RI "\fBgfloat\fP \fBz\fP"
.br
.ti -1c
.RI "\fBgfloat\fP \fBr\fP"
.br
.ti -1c
.RI "\fBgfloat\fP \fBg\fP"
.br
.ti -1c
.RI "\fBgfloat\fP \fBb\fP"
.br
.ti -1c
.RI "\fBgfloat\fP \fBa\fP"
.br
.ti -1c
.RI "\fBGLfloat\fP \fBx\fP"
.br
.ti -1c
.RI "\fBGLfloat\fP \fBy\fP"
.br
.ti -1c
.RI "\fBGLfloat\fP \fBz\fP"
.br
.ti -1c
.RI "\fBGLfloat\fP \fBr\fP"
.br
.ti -1c
.RI "\fBGLfloat\fP \fBg\fP"
.br
.ti -1c
.RI "\fBGLfloat\fP \fBb\fP"
.br
.ti -1c
.RI "\fBGLfloat\fP \fBa\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file triangles\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBGLfloat\fP Vertex::a"

.PP
Definition at line 17 of file triangles\&.cpp\&.
.SS "\fBGLfloat\fP Vertex::a"

.PP
Definition at line 50 of file wave\&.cpp\&.
.SS "\fBGLfloat\fP Vertex::b"

.PP
Definition at line 17 of file triangles\&.cpp\&.
.SS "\fBGLfloat\fP Vertex::b"

.PP
Definition at line 50 of file wave\&.cpp\&.
.SS "\fBGLfloat\fP Vertex::g"

.PP
Definition at line 17 of file triangles\&.cpp\&.
.SS "\fBGLfloat\fP Vertex::g"

.PP
Definition at line 50 of file wave\&.cpp\&.
.SS "\fBGLfloat\fP Vertex::r"

.PP
Definition at line 17 of file triangles\&.cpp\&.
.SS "\fBGLfloat\fP Vertex::r"

.PP
Definition at line 50 of file wave\&.cpp\&.
.SS "\fBGLfloat\fP Vertex::x"

.PP
Definition at line 16 of file triangles\&.cpp\&.
.SS "\fBGLfloat\fP Vertex::x"

.PP
Definition at line 49 of file wave\&.cpp\&.
.SS "\fBGLfloat\fP Vertex::y"

.PP
Definition at line 16 of file triangles\&.cpp\&.
.SS "\fBGLfloat\fP Vertex::y"

.PP
Definition at line 49 of file wave\&.cpp\&.
.SS "\fBGLfloat\fP Vertex::z"

.PP
Definition at line 16 of file triangles\&.cpp\&.
.SS "\fBGLfloat\fP Vertex::z"

.PP
Definition at line 49 of file wave\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
