.TH "wave.cpp" 3 "Mon Apr 20 2020" "Version 0.1" "BrainHarmonics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wave.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <glad/glad\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <GLFW/glfw3\&.h>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <linmath\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBVertex\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_DELTA_T\fP   0\&.01"
.br
.ti -1c
.RI "#define \fBANIMATION_SPEED\fP   10\&.0"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBGLfloat\fP \fBgfloat\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBmakeTriangle\fP (vector< \fBVertex\fP > vct)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmakeTriangles\fP (vector< vector< \fBVertex\fP >> vct)"
.br
.ti -1c
.RI "\fBgfloat\fP \fBrandCeil\fP (float ceil)"
.br
.ti -1c
.RI "\fBvoid\fP \fBtrianglesSet\fP (int number, int \fBheight\fP, int \fBwidth\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBkey_callback\fP (GLFWwindow *\fBwindow\fP, int \fBkey\fP, int scancode, int action, int mods)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmouse_button_callback\fP (GLFWwindow *\fBwindow\fP, int button, int action, int mods)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcursor_position_callback\fP (GLFWwindow *\fBwindow\fP, double \fBx\fP, double \fBy\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBscroll_callback\fP (GLFWwindow *\fBwindow\fP, double \fBx\fP, double \fBy\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBframebuffer_size_callback\fP (GLFWwindow *\fBwindow\fP, int \fBwidth\fP, int \fBheight\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdraw_scene\fP (GLFWwindow *\fBwindow\fP, int \fBheight\fP, int \fBwidth\fP)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBGLfloat\fP \fBalpha\fP = 210\&.\fBf\fP"
.br
.ti -1c
.RI "\fBGLfloat\fP \fBbeta\fP = \-70\&.\fBf\fP"
.br
.ti -1c
.RI "\fBGLfloat\fP \fBzoom\fP = 2\&.\fBf\fP"
.br
.ti -1c
.RI "double \fBcursorX\fP"
.br
.ti -1c
.RI "double \fBcursorY\fP"
.br
.ti -1c
.RI "vector< vector< \fBVertex\fP > > \fBall_v\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ANIMATION_SPEED   10\&.0"

.PP
Definition at line 37 of file wave\&.cpp\&.
.SS "#define MAX_DELTA_T   0\&.01"

.PP
Definition at line 34 of file wave\&.cpp\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBGLfloat\fP \fBgfloat\fP"

.PP
Definition at line 45 of file wave\&.cpp\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP cursor_position_callback (GLFWwindow * window, double x, double y)"

.PP
Definition at line 195 of file wave\&.cpp\&.
.SS "\fBvoid\fP draw_scene (GLFWwindow * window, int height, int width)"

.PP
Definition at line 245 of file wave\&.cpp\&.
.SS "\fBvoid\fP framebuffer_size_callback (GLFWwindow * window, int width, int height)"

.PP
Definition at line 224 of file wave\&.cpp\&.
.SS "\fBvoid\fP key_callback (GLFWwindow * window, int key, int scancode, int action, int mods)"

.PP
Definition at line 134 of file wave\&.cpp\&.
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 271 of file wave\&.cpp\&.
.SS "\fBvoid\fP makeTriangle (vector< \fBVertex\fP > vct)"

.PP
Definition at line 58 of file wave\&.cpp\&.
.SS "\fBvoid\fP makeTriangles (vector< vector< \fBVertex\fP >> vct)"

.PP
Definition at line 72 of file wave\&.cpp\&.
.SS "\fBvoid\fP mouse_button_callback (GLFWwindow * window, int button, int action, int mods)"

.PP
Definition at line 176 of file wave\&.cpp\&.
.SS "\fBgfloat\fP randCeil (float ceil)"

.PP
Definition at line 85 of file wave\&.cpp\&.
.SS "\fBvoid\fP scroll_callback (GLFWwindow * window, double x, double y)"

.PP
Definition at line 212 of file wave\&.cpp\&.
.SS "\fBvoid\fP trianglesSet (int number, int height, int width)"

.PP
Definition at line 97 of file wave\&.cpp\&.
.SH "Variable Documentation"
.PP 
.SS "vector<vector<\fBVertex\fP> > all_v"

.PP
Definition at line 53 of file wave\&.cpp\&.
.SS "\fBGLfloat\fP \fBalpha\fP = 210\&.\fBf\fP"

.PP
Definition at line 39 of file wave\&.cpp\&.
.SS "\fBGLfloat\fP beta = \-70\&.\fBf\fP"

.PP
Definition at line 39 of file wave\&.cpp\&.
.SS "double cursorX"

.PP
Definition at line 42 of file wave\&.cpp\&.
.SS "double cursorY"

.PP
Definition at line 43 of file wave\&.cpp\&.
.SS "\fBGLfloat\fP zoom = 2\&.\fBf\fP"

.PP
Definition at line 40 of file wave\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for BrainHarmonics from the source code\&.
