BrainHarmonics.cc
DEFAULTBIASES
< For array in CRC-32 call < For handling strings < For byte handling in CRC-32 < For reading files < Formatting output to console < For output to console < For open and closed maps in A* < For Sine, Cosine, Power, Fabs & Sqrt functions < For CRC-32 < For assigning priority queue in A* < For stringstream input from console < For handling strings < For thread handling < To use vectors, which automatically handle resizing, as arrays to keep track of instances
LOWPOWERBIASES
DEBUG_PROGRAM
< Neuron container for other neuron components < Synapse, area of stimulus transmission/reception < Dendrite, pre-Soma component of a neuron < Dendrite branch, division/join of dendrites < Soma, component of a neuron < Axon Hillock, component of Soma < Axon, connected to Axon Hillock < Axon branch, division/join of Axon < Axon synaptic cleft, output area of neuron < Synaptic vesicle, container of neurotransmitters
INVALID_SOCKET
SOCKET_ERROR
SOCKET_PORT
SOCKET_ADDRESS
GRAVITY
vtkSmartPointer<vtkRenderWindow> render_window
vtkSmartPointer<vtkRenderWindowInteractor> render_window_interactor
vtkSmartPointer<vtkPoints> define_points
Referenced by UpdateAllCommand::Execute.
std::vector<vtkSmartPointer<vtkCellArray> > define_cellarrays
Referenced by UpdateAllCommand::Execute.
std::vector<vtkSmartPointer<vtkPolyData> > define_polydata
Referenced by UpdateAllCommand::Execute.
std::vector<vtkSmartPointer<vtkSurfaceReconstructionFilter> > define_surfaces
Referenced by UpdateAllCommand::Execute.
std::vector<vtkSmartPointer<vtkContourFilter> > define_contourfilters
Referenced by UpdateAllCommand::Execute.
std::vector<vtkSmartPointer<vtkReverseSense> > define_reversals
Referenced by UpdateAllCommand::Execute.
std::vector<vtkSmartPointer<vtkPolyDataMapper> > define_datamappers
std::vector<vtkSmartPointer<vtkPolyDataMapper2D> > define_datamappers2D
std::vector<vtkSmartPointer<vtkActor> > define_actors
std::vector<vtkSmartPointer<vtkActor2D> > define_actors2D
std::vector<vtkSmartPointer<vtkTextActor> > define_textactors
std::vector<vtkSmartPointer<vtkRenderer> > define_renderers
int static_points_counter
int static_polygons_counter
int static_polydata_counter
Referenced by UpdateAllCommand::Execute.
int static_cellarrays_counter
Referenced by UpdateAllCommand::Execute.
int static_surfaces_counter
Referenced by UpdateAllCommand::Execute.
int static_contourfilter_counter
Referenced by UpdateAllCommand::Execute.
int static_reversals_counter
Referenced by UpdateAllCommand::Execute.
int static_datamappers_counter
Referenced by UpdateAllCommand::Execute.
int static_datamappers2D_counter
int static_actors_counter
Referenced by UpdateAllCommand::Execute.
int static_actors2D_counter
int static_renderers_counter
Referenced by UpdateAllCommand::Execute.
int dynamic_points_counter
int dynamic_polygons_counter
int dynamic_polydata_counter
Referenced by UpdateAllCommand::Execute.
int dynamic_cellarrays_counter
int dynamic_surfaces_counter
Referenced by UpdateAllCommand::Execute.
int dynamic_contourfilter_counter
Referenced by UpdateAllCommand::Execute.
int dynamic_reversals_counter
Referenced by UpdateAllCommand::Execute.
int dynamic_datamappers_counter
int dynamic_datamappers2D_counter
int dynamic_actors_counter
int dynamic_actors2D_counter
int dynamic_renderers_counter
std::vector<Universe*> universe_list
< Python interpreter < Top of the tree, begin with Universe class < Add Dimensions for spatial identification < Materials are a combination of Matter < Materials can be formed into multiDimensional shapes < Fundamental spatial description < Interim function describing time before inclusion as Dimension Top of the tree, begin with Universe class
Referenced by UpdateAllCommand::Execute.
struct caer_dynapse_info dynapse_info
Referenced by ClearDynapse.
VTK_MODULE_INIT(vtkRenderingOpenGL2)
VTK_MODULE_INIT(vtkRenderingFreeType)
VTK_MODULE_INIT(vtkInteractionStyle)
vtkSmartPointer< vtkPolyData > TransformBack(vtkSmartPointer< vtkPoints > pt, vtkSmartPointer< vtkPolyData > pd)
static std::atomic_bool globalShutdown(false)
static void globalShutdownSignalHandler(int signal)
bool mshandling(std::vector< std::string > *m_messages, bool m_response, int m_ok, int m_fail)
References DEBUG_PROGRAM.
std::vector<Universe*> CreateUniverse(std::chrono::time_point< Clock > event_time, std::vector< Universe *> *toAddto)
References Universe::SetEnergy, Universe::Update.
bool CompareSwapElementaryParticle(std::chrono::time_point< Clock > event_time, std::vector< ElementaryParticle *> &origin, int l_origin_Swap, int l_origin_Candidate1, int l_origin_Candidate2)
int DistanceBetweenNodes(std::chrono::time_point< Clock > event_time, std::vector< Point > *nodesQuery, std::vector< int > *nodes_list, int nodesDimensions, double desired_distance)
References RAD2DEG, DEG2RAD.
bool compare_swapSynapse(std::chrono::time_point< Clock > event_time, std::vector< Synapse *> origin, int l_origin_Swap, int l_origin_Candidate1, int l_origin_Candidate2)
bool analyseStream(std::chrono::time_point< Clock > event_time, CognitiveNetwork *cognitive_network, std::vector< Neuron *> neuron_list, std::vector< Point *> aPoint, int start_point, int end_point, int stepPoint, int neural_sequence)
void ClearDimensionSelection(std::vector< int > *dimension_list)
void SelectDimension(const int PossibleDimensions[10], std::vector< int > *dimension_list, int whichDimension)
Referenced by SelectMultiDimensions.
void SelectMultiDimensions(const int PossibleDimensions[10], std::vector< int > *dimension_list, int how_manyDimensions)
References SelectDimension.
bool ClearDynapse(caerDeviceHandle *usb_handle)
References dynapse_info, DEFAULTBIASES.
void exitCB()
Referenced by init.
int init(int argc, const char *argv[])
References exitCB.
Referenced by main.
void init_numpy()
int main(int argc, const char *argv[])
References init.