Polyhedron
friend class Soma
friend class Membrane
std::vector<Polyhedron*> Polyhedron::polygon_list
Referenced by ResetParameters, CreatePolygon, CreatePolygons, AddPolygon, AddPolygons, GetPolygon, GetPolygons.
std::vector<Point*> Polyhedron::point_list
Referenced by ResetParameters, GetPoint, GetPoints, Update, GenerateSpherePoints, GenerateCylinderPoints.
unsigned int Polyhedron::polyhedronCounter
Member variable "polyhedronCounter".
unsigned int Polyhedron::polyhedron_type
bool Polyhedron::object_disabled
bool Polyhedron::object_initialised
std::chrono::time_point<Clock> Polyhedron::previous_event_time
std::chrono::time_point<Clock> Polyhedron::time_object_created
int Polyhedron::duration_since_last_event
int Polyhedron::polygon_pool
int Polyhedron::point_pool
Polyhedron::Polyhedron()
Polyhedron::Polyhedron(unsigned int object_type)
Polyhedron::Polyhedron(unsigned int object_type, std::chrono::time_point< Clock > event_time)
Polyhedron::Polyhedron(unsigned int object_type, std::chrono::time_point< Clock > event_time, Solid &solid_connector)
References ResetParameters, Universe::Creation.
virtual Polyhedron::~Polyhedron()
bool Polyhedron::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::TheTimeNow, TYPE_SOLID_POLYHEDRON_SOMA_GEN1, polygon_list, point_list, Universe::object_energy, GenerateSpherePoints, TYPE_SOLID_POLYHEDRON_MEMBRANE_GEN1, TYPE_SOLID_POLYHEDRON_SOMA_AXONHILLOCK_GEN1, TYPE_SOLID_POLYHEDRON_SOMA_AXONHILLOCK_AXON_GEN1, TYPE_SOLID_POLYHEDRON_SOMA_AXONHILLOCK_AXON_AXONBRANCH_GEN1, TYPE_SOLID_POLYHEDRON_SOMA_AXONHILLOCK_AXON_AXONBRANCH_AXONBOUTON_GEN1, TYPE_SOLID_POLYHEDRON_SOMA_DENDRITE_GEN1, GenerateCylinderPoints, TYPE_SOLID_POLYHEDRON_SOMA_DENDRITE_DENDRITEBRANCH_GEN1, TYPE_SOLID_POLYHEDRON_SOMA_DENDRITE_DENDRITEBRANCH_DENDRITECLEFT_GEN1.
Referenced by SetObjectType, Update, Polyhedron.
unsigned int Polyhedron::GetCounter(std::chrono::time_point< Clock > event_time)
void Polyhedron::setCounter(unsigned int val)
void Polyhedron::SetObjectType(std::chrono::time_point< Clock > event_time, unsigned int val)
References ResetParameters.
Referenced by Solid::ResetParameters.
Polyhedron * Polyhedron::CreatePolygon(std::chrono::time_point< Clock > event_time)
References polygon_list.
Referenced by CreatePolygons.
std::vector< Polyhedron * > Polyhedron::CreatePolygons(std::chrono::time_point< Clock > event_time, int quantity)
References polygon_list, CreatePolygon.
Polyhedron * Polyhedron::ClonePolygon(std::chrono::time_point< Clock > event_time, Polyhedron *clone_object, double perfection_membership)
std::vector< Polyhedron * > Polyhedron::ClonePolygons(std::chrono::time_point< Clock > event_time, std::vector< Polyhedron *> cloning_list, double perfection_membership)
Polyhedron * Polyhedron::DestroyPolygon(std::chrono::time_point< Clock > event_time, Polyhedron *destroy_object)
std::vector< Polyhedron * > Polyhedron::DestroyPolygons(std::chrono::time_point< Clock > event_time, std::vector< Polyhedron *> destruction_list)
Polyhedron * Polyhedron::AddPolygon(std::chrono::time_point< Clock > event_time, Polyhedron *add_object)
References polygon_list.
Referenced by AddPolygons.
std::vector< Polyhedron * > Polyhedron::AddPolygons(std::chrono::time_point< Clock > event_time, std::vector< Polyhedron *> add_objects)
References polygon_list, AddPolygon.
Polyhedron * Polyhedron::RemovePolygon(std::chrono::time_point< Clock > event_time)
std::vector< Polyhedron * > Polyhedron::RemovePolygons(std::chrono::time_point< Clock > event_time, int quantity)
Polyhedron * Polyhedron::GetPolygon(std::chrono::time_point< Clock > event_time, int selector)
References polygon_list.
std::vector< Polyhedron * > Polyhedron::GetPolygons(std::chrono::time_point< Clock > event_time)
References polygon_list.
Point * Polyhedron::GetPoint(std::chrono::time_point< Clock > event_time, int selector)
References point_list.
std::vector< Point * > Polyhedron::GetPoints(std::chrono::time_point< Clock > event_time)
References point_list.
Referenced by UpdateAllCommand::Execute.
int Polyhedron::GenerateSpherePoints(std::chrono::time_point< Clock > event_time)
References Universe::AddPoint, Point::SetPointPosition, point_list.
Referenced by ResetParameters.
int Polyhedron::GenerateCylinderPoints(std::chrono::time_point< Clock > event_time)
References Universe::AddPoint, Point::SetPointPosition, point_list.
Referenced by ResetParameters.
void Polyhedron::UpdateCycle(std::chrono::time_point< Clock > event_time, std::vector< Point *> set_of_update_pointers, unsigned int pointer_type)
References Point::Update.
Referenced by Update.
int Polyhedron::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters, UpdateCycle, point_list, Universe::object_energy.