Quad
int Quad::quadQuadID
double Quad::quadQuadX1
Member variable "quadQuadX1".
double Quad::quadQuadY1
Member variable "quadQuadY1".
double Quad::quadQuadX2
Member variable "quadQuadX2".
double Quad::quadQuadY2
Member variable "quadQuadY2".
double Quad::quadQuadX3
Member variable "quadQuadX3".
double Quad::quadQuadY3
Member variable "quadQuadY3".
double Quad::quadQuadX4
Member variable "quadQuadX4".
double Quad::quadQuadY4
Member variable "quadQuadY4".
double Quad::quadQuadTTL
int Quad::quadQuadCounter
int Quad::quad_type
bool Quad::object_disabled
bool Quad::object_initialised
std::chrono::time_point<Clock> Quad::time_object_created
std::chrono::time_point<Clock> Quad::previous_event_time
int Quad::duration_since_last_event
Quad::Quad()
Quad::Quad(unsigned int object_type)
Quad::Quad(unsigned int object_type, std::chrono::time_point< Clock > event_time)
Quad::Quad(unsigned int object_type, std::chrono::time_point< Clock > event_time, Polygon &polygon_connector)
References ResetParameters, Universe::Creation.
virtual Quad::~Quad()
Default destructor
References ResetParameters.
bool Quad::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::TheTimeNow, Universe::object_energy.
Referenced by Update, Quad, ~Quad.
int Quad::GetQuadID(std::chrono::time_point< Clock > event_time) const
double Quad::GetQuadX1(std::chrono::time_point< Clock > event_time) const
double Quad::GetQuadY1(std::chrono::time_point< Clock > event_time) const
double Quad::GetQuadX2(std::chrono::time_point< Clock > event_time) const
double Quad::GetQuadY2(std::chrono::time_point< Clock > event_time) const
double Quad::GetQuadX3(std::chrono::time_point< Clock > event_time) const
double Quad::GetQuadY3(std::chrono::time_point< Clock > event_time) const
double Quad::GetQuadX4(std::chrono::time_point< Clock > event_time) const
double Quad::GetQuadY4(std::chrono::time_point< Clock > event_time) const
double Quad::GetQuadTTL(std::chrono::time_point< Clock > event_time) const
int Quad::GetQuadCounter(std::chrono::time_point< Clock > event_time) const
bool Quad::GetInQuad(std::chrono::time_point< Clock > event_time, double X1, double Y1, double X2, double Y2, double X3, double Y3, double X4, double Y4, double Threshold)
void Quad::SetQuadID(std::chrono::time_point< Clock > event_time, int val)
void Quad::SetQuadX1(std::chrono::time_point< Clock > event_time, double val)
void Quad::SetQuadY1(std::chrono::time_point< Clock > event_time, double val)
void Quad::SetQuadX2(std::chrono::time_point< Clock > event_time, double val)
void Quad::SetQuadY2(std::chrono::time_point< Clock > event_time, double val)
void Quad::SetQuadX3(std::chrono::time_point< Clock > event_time, double val)
void Quad::SetQuadY3(std::chrono::time_point< Clock > event_time, double val)
void Quad::SetQuadX4(std::chrono::time_point< Clock > event_time, double val)
void Quad::SetQuadY4(std::chrono::time_point< Clock > event_time, double val)
void Quad::SetQuadTTL(std::chrono::time_point< Clock > event_time, double val)
void Quad::SetQuadCounter(std::chrono::time_point< Clock > event_time, int val)
References Update.
int Quad::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters, Universe::object_energy.
Referenced by SetQuadCounter.