Dendrite
std::vector<Dendrite*> Dendrite::dendritebranch_list
Referenced by CreateDendriteBranch, CreateDendriteBranches, AddDendriteBranch, AddDendriteBranches, GetDendriteBranch, GetDendriteBranches, Growth.
int Dendrite::m_NeuronType
int Dendrite::dendrite_type
bool Dendrite::object_disabled
bool Dendrite::object_initialised
int Dendrite::m_addStatus
std::chrono::time_point<Clock> Dendrite::time_object_created
std::chrono::time_point<Clock> Dendrite::previous_event_time
int Dendrite::dendritebranch_pool
int Dendrite::duration_since_last_event
double Dendrite::m_Volume
double Dendrite::m_SurfaceArea
double Dendrite::m_Length
double Dendrite::object_size
double Dendrite::m_dendriteLength
Member variable "m_dendriteLength".
double Dendrite::m_dendriteDiameterStart
Member variable "m_dendriteDiameterStart".
double Dendrite::m_dendriteDiameterEnd
Member variable "m_dendriteDiameterEnd".
double Dendrite::m_membraneResistance
double Dendrite::m_membraneCapacitance
double Dendrite::m_internalResistance
unsigned int Dendrite::m_Counter
Member variable "m_Counter".
double Dendrite::object_energy
Member variable "object_energy".
double Dendrite::object_energyInc
double Dendrite::object_energyDec
double Dendrite::object_energyLeak
double Dendrite::object_energy_threshold
double Dendrite::m_TimeDilation
double Dendrite::m_TimeThreshold
Dendrite::Dendrite()
Dendrite::Dendrite(unsigned int object_type)
Dendrite::Dendrite(unsigned int object_type, std::chrono::time_point< Clock > event_time)
Dendrite::Dendrite(unsigned int object_type, std::chrono::time_point< Clock > event_time, Soma &soma_connector)
References ResetParameters, Universe::Creation.
virtual Dendrite::~Dendrite()
Default destructor
unsigned int Dendrite::GetCounter(std::chrono::time_point< Clock > event_time)
double Dendrite::GetEnergy(std::chrono::time_point< Clock > event_time)
double Dendrite::GetDendriteLength(std::chrono::time_point< Clock > event_time)
double Dendrite::GetDendriteDiameterStart(std::chrono::time_point< Clock > event_time)
double Dendrite::GetDendriteDiameterEnd(std::chrono::time_point< Clock > event_time)
double Dendrite::GetMembraneResistance(std::chrono::time_point< Clock > event_time)
double Dendrite::GetMembraneCapacitance(std::chrono::time_point< Clock > event_time)
double Dendrite::GetInternalResistance(std::chrono::time_point< Clock > event_time)
double Dendrite::GetPropagationVelocity(std::chrono::time_point< Clock > event_time)
void Dendrite::setDendriteLength(std::chrono::time_point< Clock > event_time, double val)
void Dendrite::setDendriteDiameterStart(std::chrono::time_point< Clock > event_time, double val)
void Dendrite::setDendriteDiameterEnd(std::chrono::time_point< Clock > event_time, double val)
void Dendrite::setMembraneResistance(std::chrono::time_point< Clock > event_time, double val)
void Dendrite::setMembraneCapacitance(std::chrono::time_point< Clock > event_time, double val)
void Dendrite::setInternalResistance(std::chrono::time_point< Clock > event_time, double val)
void Dendrite::SetCounter(std::chrono::time_point< Clock > event_time, unsigned int val)
void Dendrite::SetEnergy(std::chrono::time_point< Clock > event_time, double val)
References ResetParameters, CreateDendriteBranch, CreateDendriteBranches, CloneDendriteBranch, CloneDendriteBranches, DestroyDendriteBranch, DestroyDendriteBranches, AddDendriteBranch, AddDendriteBranches, RemoveDendriteBranch, RemoveDendriteBranches, GetDendriteBranch, GetDendriteBranches, Growth, Update.
bool Dendrite::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::TheTimeNow.
Referenced by Update, Dendrite, SetEnergy.
Dendrite * Dendrite::CreateDendriteBranch(std::chrono::time_point< Clock > event_time)
References dendritebranch_list.
Referenced by CreateDendriteBranches, Growth, SetEnergy.
std::vector< Dendrite * > Dendrite::CreateDendriteBranches(std::chrono::time_point< Clock > event_time, int quantity)
References dendritebranch_list, CreateDendriteBranch.
Referenced by SetEnergy.
Dendrite * Dendrite::CloneDendriteBranch(std::chrono::time_point< Clock > event_time, Dendrite *clone_object, double perfection_membership)
Referenced by SetEnergy.
std::vector< Dendrite * > Dendrite::CloneDendriteBranches(std::chrono::time_point< Clock > event_time, std::vector< Dendrite *> cloning_list, double perfection_membership)
Referenced by SetEnergy.
Dendrite * Dendrite::DestroyDendriteBranch(std::chrono::time_point< Clock > event_time, Dendrite *destroy_object)
Referenced by SetEnergy.
std::vector< Dendrite * > Dendrite::DestroyDendriteBranches(std::chrono::time_point< Clock > event_time, std::vector< Dendrite *> destruction_list)
Referenced by SetEnergy.
Dendrite * Dendrite::AddDendriteBranch(std::chrono::time_point< Clock > event_time, Dendrite *add_object)
References dendritebranch_list.
Referenced by AddDendriteBranches, SetEnergy.
std::vector< Dendrite * > Dendrite::AddDendriteBranches(std::chrono::time_point< Clock > event_time, std::vector< Dendrite *> add_objects)
References dendritebranch_list, AddDendriteBranch.
Referenced by SetEnergy.
Dendrite * Dendrite::RemoveDendriteBranch(std::chrono::time_point< Clock > event_time)
Referenced by SetEnergy.
std::vector< Dendrite * > Dendrite::RemoveDendriteBranches(std::chrono::time_point< Clock > event_time, int quantity)
Referenced by SetEnergy.
Dendrite * Dendrite::GetDendriteBranch(std::chrono::time_point< Clock > event_time, int selector)
References dendritebranch_list.
Referenced by SetEnergy.
std::vector< Dendrite * > Dendrite::GetDendriteBranches(std::chrono::time_point< Clock > event_time)
References dendritebranch_list.
Referenced by SetEnergy.
int Dendrite::Growth(std::chrono::time_point< Clock > event_time)
References CreateDendriteBranch, Soma::SetObjectType, TYPE_NEURON_PYRAMIDAL_SOMA_DENDRITE_DENDRITEBRANCH_GEN1, dendritebranch_list.
Referenced by Update, SetEnergy.
int Dendrite::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters, Neuron::visualisation_list, Solid::CreatePolyhedron, Solid::SetObjectType, TYPE_SOLID_POLYHEDRON_SOMA_DENDRITE_GEN1, Growth.
Referenced by SetEnergy.