Monomer
std::vector<Monomer*> Monomer::solid_list
unsigned int Monomer::monomer_counter
Member variable "monomer_counter".
int Monomer::monomer_type
bool Monomer::object_initialised
bool Monomer::object_disabled
int Monomer::duration_since_last_event
std::chrono::time_point<Clock> Monomer::time_object_created
std::chrono::time_point<Clock> Monomer::previous_event_time
Monomer::Monomer()
Monomer::Monomer(unsigned int object_type)
Monomer::Monomer(unsigned int object_type, std::chrono::time_point< Clock > event_time)
Monomer::Monomer(unsigned int object_type, std::chrono::time_point< Clock > event_time, Universe &universe_connector)
References ResetParameters, Universe::Creation.
virtual Monomer::~Monomer()
Default destructor
References GetCounter, SetCounter, ResetParameters, AddSolid, Update.
unsigned int Monomer::GetCounter(std::chrono::time_point< Clock > event_time)
Referenced by ~Monomer.
void Monomer::SetCounter(std::chrono::time_point< Clock > event_time, unsigned int val)
Referenced by ~Monomer.
bool Monomer::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::TheTimeNow, Universe::object_energy, Universe::object_energy_threshold, Universe::object_size.
Referenced by Update, Monomer, ~Monomer.
int Monomer::AddSolid(std::chrono::time_point< Clock > event_time)
Referenced by ~Monomer.
int Monomer::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters, Universe::object_energy.
Referenced by ~Monomer.
void Monomer::SetCharge(std::chrono::time_point< Clock > event_time, int val) final
void Monomer::SetSpin(std::chrono::time_point< Clock > event_time, int val) final
double Monomer::GetGravitation(std::chrono::time_point< Clock > event_time) final
double Monomer::GetWeak(std::chrono::time_point< Clock > event_time) final
double Monomer::GetWeakElectroweak(std::chrono::time_point< Clock > event_time) final
double Monomer::GetElectromagnetic(std::chrono::time_point< Clock > event_time) final
double Monomer::GetElectromagneticElectroweak(std::chrono::time_point< Clock > event_time) final
double Monomer::GetStrong(std::chrono::time_point< Clock > event_time) final
double Monomer::GetStrongFundamental(std::chrono::time_point< Clock > event_time) final
double Monomer::GetStrongResidual(std::chrono::time_point< Clock > event_time) final
double Monomer::ApplyGravitation(std::chrono::time_point< Clock > event_time, double val) final
double Monomer::ApplyWeak(std::chrono::time_point< Clock > event_time, double val) final
double Monomer::ApplyWeakElectroweak(std::chrono::time_point< Clock > event_time, double val) final
double Monomer::ApplyElectromagnetic(std::chrono::time_point< Clock > event_time, double val) final
double Monomer::ApplyElectromagneticElectroweak(std::chrono::time_point< Clock > event_time, double val) final
double Monomer::ApplyStrong(std::chrono::time_point< Clock > event_time, double val) final
double Monomer::ApplyStrongFundamental(std::chrono::time_point< Clock > event_time, double val) final
double Monomer::ApplyStrongResidual(std::chrono::time_point< Clock > event_time, double val) final
void Monomer::SetGravitation(std::chrono::time_point< Clock > event_time, double val) final
void Monomer::SetWeak(std::chrono::time_point< Clock > event_time, double val) final
void Monomer::SetWeakElectroweak(std::chrono::time_point< Clock > event_time, double val) final
void Monomer::SetElectromagnetic(std::chrono::time_point< Clock > event_time, double val) final
void Monomer::SetElectromagneticElectroweak(std::chrono::time_point< Clock > event_time, double val) final
void Monomer::SetStrong(std::chrono::time_point< Clock > event_time, double val) final
void Monomer::SetStrongFundamental(std::chrono::time_point< Clock > event_time, double val) final
void Monomer::SetStrongResidual(std::chrono::time_point< Clock > event_time, double val) final
void Monomer::PollElementaryForce(std::chrono::time_point< Clock > event_time) final