SynapticVesicle
std::vector<CognitiveNetwork*> SynapticVesicle::neurotransmitter_list
Referenced by CreateNeurotransmitter, CreateNeurotransmitters, AddNeurotransmitter, AddNeurotransmitters, GetNeurotransmitter, GetNeurotransmitters, Update.
int SynapticVesicle::m_NeuronType
int SynapticVesicle::neurotransmitter_pool
int SynapticVesicle::synapticvesicle_type
int SynapticVesicle::m_addStatus
bool SynapticVesicle::object_disabled
bool SynapticVesicle::object_initialised
int SynapticVesicle::m_ReleaseState
std::chrono::time_point<Clock> SynapticVesicle::time_object_created
std::chrono::time_point<Clock> SynapticVesicle::previous_event_time
int SynapticVesicle::duration_since_last_event
double SynapticVesicle::m_Volume
double SynapticVesicle::m_SurfaceArea
unsigned int SynapticVesicle::m_Counter
Member variable "m_Counter".
double SynapticVesicle::object_energy
Member variable "object_energy".
double SynapticVesicle::m_axonlength
double SynapticVesicle::m_TimeDilation
double SynapticVesicle::m_TimeThreshold
SynapticVesicle::SynapticVesicle()
SynapticVesicle::SynapticVesicle(unsigned int object_type)
SynapticVesicle::SynapticVesicle(unsigned int object_type, std::chrono::time_point< Clock > event_time)
SynapticVesicle::SynapticVesicle(unsigned int object_type, std::chrono::time_point< Clock > event_time, AxonBouton &axonbouton_connector)
References ResetParameters, Universe::Creation.
virtual SynapticVesicle::~SynapticVesicle()
Default destructor
unsigned int SynapticVesicle::GetCounter(std::chrono::time_point< Clock > event_time)
double SynapticVesicle::GetEnergy(std::chrono::time_point< Clock > event_time)
int SynapticVesicle::GetReleaseState(std::chrono::time_point< Clock > event_time)
void SynapticVesicle::SetCounter(std::chrono::time_point< Clock > event_time, unsigned int val)
void SynapticVesicle::SetEnergy(std::chrono::time_point< Clock > event_time, double val)
References ResetParameters, CreateNeurotransmitter, CreateNeurotransmitters, CloneNeurotransmitter, CloneNeurotransmitters, DestroyNeurotransmitter, DestroyNeurotransmitters, AddNeurotransmitter, AddNeurotransmitters, RemoveNeurotransmitter, RemoveNeurotransmitters, GetNeurotransmitter, GetNeurotransmitters, GrowthSurface, GrowthVolume, ReleaseNeurotransmitters, Update.
bool SynapticVesicle::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::TheTimeNow.
Referenced by Update, SynapticVesicle, SetEnergy.
CognitiveNetwork * SynapticVesicle::CreateNeurotransmitter(std::chrono::time_point< Clock > event_time)
References neurotransmitter_list.
Referenced by CreateNeurotransmitters, SetEnergy.
std::vector< CognitiveNetwork * > SynapticVesicle::CreateNeurotransmitters(std::chrono::time_point< Clock > event_time, int quantity)
References neurotransmitter_list, CreateNeurotransmitter.
Referenced by SetEnergy.
CognitiveNetwork * SynapticVesicle::CloneNeurotransmitter(std::chrono::time_point< Clock > event_time, CognitiveNetwork *clone_object, double perfection_membership)
Referenced by SetEnergy.
std::vector< CognitiveNetwork * > SynapticVesicle::CloneNeurotransmitters(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> cloning_list, double perfection_membership)
Referenced by SetEnergy.
CognitiveNetwork * SynapticVesicle::DestroyNeurotransmitter(std::chrono::time_point< Clock > event_time, CognitiveNetwork *destroy_object)
Referenced by SetEnergy.
std::vector< CognitiveNetwork * > SynapticVesicle::DestroyNeurotransmitters(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> destruction_list)
Referenced by SetEnergy.
CognitiveNetwork * SynapticVesicle::AddNeurotransmitter(std::chrono::time_point< Clock > event_time, CognitiveNetwork *add_object)
References neurotransmitter_list.
Referenced by AddNeurotransmitters, SetEnergy.
std::vector< CognitiveNetwork * > SynapticVesicle::AddNeurotransmitters(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> add_objects)
References neurotransmitter_list, AddNeurotransmitter.
Referenced by SetEnergy.
CognitiveNetwork * SynapticVesicle::RemoveNeurotransmitter(std::chrono::time_point< Clock > event_time)
Referenced by SetEnergy.
std::vector< CognitiveNetwork * > SynapticVesicle::RemoveNeurotransmitters(std::chrono::time_point< Clock > event_time, int quantity)
Referenced by SetEnergy.
CognitiveNetwork * SynapticVesicle::GetNeurotransmitter(std::chrono::time_point< Clock > event_time, int selector)
References neurotransmitter_list.
Referenced by SetEnergy.
std::vector< CognitiveNetwork * > SynapticVesicle::GetNeurotransmitters(std::chrono::time_point< Clock > event_time)
References neurotransmitter_list.
Referenced by SetEnergy.
int SynapticVesicle::GrowthSurface(std::chrono::time_point< Clock > event_time, double surf_change)
Referenced by GrowthVolume, SetEnergy.
int SynapticVesicle::GrowthVolume(std::chrono::time_point< Clock > event_time, double vol_change)
References GrowthSurface.
Referenced by SetEnergy.
void SynapticVesicle::ReleaseNeurotransmitters(std::chrono::time_point< Clock > event_time)
Referenced by SetEnergy.
int SynapticVesicle::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters, neurotransmitter_list.
Referenced by SetEnergy.