Screen_0
bool Screen_0::m_onScreen
Member variable "m_onScreen".
Screen_0::Screen_0()
Default constructor
virtual Screen_0::~Screen_0()
Default destructor
References creation, runScreen.
void Screen_0::creation()
Referenced by ~Screen_0, Screen_1::~Screen_1, main.
int Screen_0::runScreen(sf::RenderWindow &app)
Referenced by ~Screen_0, Screen_1::~Screen_1.