DendriteCleft
std::vector<DendriteCleft*> DendriteCleft::neuroreceptor_list
Referenced by CreateNeuroreceptor, CreateNeuroreceptors, AddNeuroreceptor, AddNeuroreceptors, GetNeuroreceptor, GetNeuroreceptors, Update.
int DendriteCleft::dendritecleft_type
int DendriteCleft::m_addStatus
int DendriteCleft::neuroreceptor_pool
std::chrono::time_point<Clock> DendriteCleft::previous_event_time
std::chrono::time_point<Clock> DendriteCleft::time_object_created
bool DendriteCleft::object_disabled
bool DendriteCleft::object_initialised
int DendriteCleft::duration_since_last_event
double DendriteCleft::m_Volume
double DendriteCleft::m_SurfaceArea
double DendriteCleft::m_Length
double DendriteCleft::object_size
Member variable "object_size" Area of cleft (assumed to be circular due to pressure equalisation)
double DendriteCleft::m_dendriteLength
Member variable "m_dendriteLength".
double DendriteCleft::m_dendriteDiameterStart
Member variable "m_dendriteDiameterStart".
double DendriteCleft::m_dendriteDiameterEnd
Member variable "m_dendriteDiameterEnd".
double DendriteCleft::m_membraneResistance
double DendriteCleft::m_membraneCapacitance
double DendriteCleft::m_internalResistance
unsigned int DendriteCleft::m_Counter
Member variable "m_Counter".
double DendriteCleft::object_energy
Member variable "object_energy".
double DendriteCleft::object_energyInc
double DendriteCleft::object_energyDec
double DendriteCleft::object_energyLeak
double DendriteCleft::object_energy_threshold
double DendriteCleft::m_TimeDilation
double DendriteCleft::m_TimeThreshold
DendriteCleft::DendriteCleft()
DendriteCleft::DendriteCleft(unsigned int object_type)
DendriteCleft::DendriteCleft(unsigned int object_type, std::chrono::time_point< Clock > event_time)
DendriteCleft::DendriteCleft(unsigned int object_type, std::chrono::time_point< Clock > event_time, DendriteBranch &dendritebranch_connector)
References ResetParameters, Universe::Creation.
virtual DendriteCleft::~DendriteCleft()
Default destructor
unsigned int DendriteCleft::GetCounter(std::chrono::time_point< Clock > event_time)
double DendriteCleft::GetEnergy(std::chrono::time_point< Clock > event_time)
void DendriteCleft::SetCounter(std::chrono::time_point< Clock > event_time, unsigned int val)
void DendriteCleft::SetEnergy(std::chrono::time_point< Clock > event_time, double val)
References ResetParameters, CreateNeuroreceptor, CreateNeuroreceptors, CloneNeuroreceptor, CloneNeuroreceptors, DestroyNeuroreceptor, DestroyNeuroreceptors, AddNeuroreceptor, AddNeuroreceptors, RemoveNeuroreceptor, RemoveNeuroreceptors, GetNeuroreceptor, GetNeuroreceptors, GrowthSurface, GrowthVolume, Update.
bool DendriteCleft::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::TheTimeNow.
Referenced by Update, DendriteCleft, SetEnergy.
DendriteCleft * DendriteCleft::CreateNeuroreceptor(std::chrono::time_point< Clock > event_time)
References neuroreceptor_list.
Referenced by CreateNeuroreceptors, SetEnergy.
std::vector< DendriteCleft * > DendriteCleft::CreateNeuroreceptors(std::chrono::time_point< Clock > event_time, int quantity)
References neuroreceptor_list, CreateNeuroreceptor.
Referenced by SetEnergy.
DendriteCleft * DendriteCleft::CloneNeuroreceptor(std::chrono::time_point< Clock > event_time, DendriteCleft *clone_object, double perfection_membership)
Referenced by SetEnergy.
std::vector< DendriteCleft * > DendriteCleft::CloneNeuroreceptors(std::chrono::time_point< Clock > event_time, std::vector< DendriteCleft *> cloning_list, double perfection_membership)
Referenced by SetEnergy.
DendriteCleft * DendriteCleft::DestroyNeuroreceptor(std::chrono::time_point< Clock > event_time, DendriteCleft *destroy_object)
Referenced by SetEnergy.
std::vector< DendriteCleft * > DendriteCleft::DestroyNeuroreceptors(std::chrono::time_point< Clock > event_time, std::vector< DendriteCleft *> destruction_list)
Referenced by SetEnergy.
DendriteCleft * DendriteCleft::AddNeuroreceptor(std::chrono::time_point< Clock > event_time, DendriteCleft *add_object)
References neuroreceptor_list.
Referenced by AddNeuroreceptors, SetEnergy.
std::vector< DendriteCleft * > DendriteCleft::AddNeuroreceptors(std::chrono::time_point< Clock > event_time, std::vector< DendriteCleft *> add_objects)
References neuroreceptor_list, AddNeuroreceptor.
Referenced by SetEnergy.
DendriteCleft * DendriteCleft::RemoveNeuroreceptor(std::chrono::time_point< Clock > event_time)
Referenced by SetEnergy.
std::vector< DendriteCleft * > DendriteCleft::RemoveNeuroreceptors(std::chrono::time_point< Clock > event_time, int quantity)
Referenced by SetEnergy.
DendriteCleft * DendriteCleft::GetNeuroreceptor(std::chrono::time_point< Clock > event_time, int selector)
References neuroreceptor_list.
Referenced by SetEnergy.
std::vector< DendriteCleft * > DendriteCleft::GetNeuroreceptors(std::chrono::time_point< Clock > event_time)
References neuroreceptor_list.
Referenced by SetEnergy.
int DendriteCleft::GrowthSurface(std::chrono::time_point< Clock > event_time, double surf_change)
Referenced by GrowthVolume, SetEnergy.
int DendriteCleft::GrowthVolume(std::chrono::time_point< Clock > event_time, double vol_change)
References GrowthSurface.
Referenced by SetEnergy.
int DendriteCleft::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters, Neuron::visualisation_list, Solid::CreatePolyhedron, Solid::SetObjectType, TYPE_SOLID_POLYHEDRON_SOMA_DENDRITE_DENDRITEBRANCH_DENDRITECLEFT_GEN1, neuroreceptor_list.
Referenced by SetEnergy.