Law
unsigned int Law::m_Counter
Member variable "m_Counter".
int Law::law_type
std::chrono::time_point<Clock> Law::time_object_created
std::chrono::time_point<Clock> Law::previous_event_time
bool Law::object_disabled
bool Law::object_initialised
int Law::duration_since_last_event
Law::Law()
Law::Law(unsigned int object_type)
Law::Law(unsigned int object_type, std::chrono::time_point< Clock > event_time)
Law::Law(unsigned int object_type, std::chrono::time_point< Clock > event_time, Universe &universe_connector)
References ResetParameters, Universe::Creation.
virtual Law::~Law()
Default destructor
References ResetParameters, GetCounter, SetCounter, Update.
bool Law::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::TheTimeNow, Universe::object_energy, Universe::object_energy_threshold, Universe::object_size.
Referenced by Update, Law, ~Law.
unsigned int Law::GetCounter(std::chrono::time_point< Clock > event_time)
Referenced by ~Law.
void Law::SetCounter(std::chrono::time_point< Clock > event_time, unsigned int val)
Referenced by ~Law.
int Law::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters, Universe::object_energy.
Referenced by ~Law.
void Law::SetCharge(std::chrono::time_point< Clock > event_time, int val) final
void Law::SetSpin(std::chrono::time_point< Clock > event_time, int val) final
double Law::GetGravitation(std::chrono::time_point< Clock > event_time) final
double Law::GetWeak(std::chrono::time_point< Clock > event_time) final
double Law::GetWeakElectroweak(std::chrono::time_point< Clock > event_time) final
double Law::GetElectromagnetic(std::chrono::time_point< Clock > event_time) final
double Law::GetElectromagneticElectroweak(std::chrono::time_point< Clock > event_time) final
double Law::GetStrong(std::chrono::time_point< Clock > event_time) final
double Law::GetStrongFundamental(std::chrono::time_point< Clock > event_time) final
double Law::GetStrongResidual(std::chrono::time_point< Clock > event_time) final
double Law::ApplyGravitation(std::chrono::time_point< Clock > event_time, double val) final
double Law::ApplyWeak(std::chrono::time_point< Clock > event_time, double val) final
double Law::ApplyWeakElectroweak(std::chrono::time_point< Clock > event_time, double val) final
double Law::ApplyElectromagnetic(std::chrono::time_point< Clock > event_time, double val) final
double Law::ApplyElectromagneticElectroweak(std::chrono::time_point< Clock > event_time, double val) final
double Law::ApplyStrong(std::chrono::time_point< Clock > event_time, double val) final
double Law::ApplyStrongFundamental(std::chrono::time_point< Clock > event_time, double val) final
double Law::ApplyStrongResidual(std::chrono::time_point< Clock > event_time, double val) final
void Law::SetGravitation(std::chrono::time_point< Clock > event_time, double val) final
void Law::SetWeak(std::chrono::time_point< Clock > event_time, double val) final
void Law::SetWeakElectroweak(std::chrono::time_point< Clock > event_time, double val) final
void Law::SetElectromagnetic(std::chrono::time_point< Clock > event_time, double val) final
void Law::SetElectromagneticElectroweak(std::chrono::time_point< Clock > event_time, double val) final
void Law::SetStrong(std::chrono::time_point< Clock > event_time, double val) final
void Law::SetStrongFundamental(std::chrono::time_point< Clock > event_time, double val) final
void Law::SetStrongResidual(std::chrono::time_point< Clock > event_time, double val) final
void Law::PollElementaryForce(std::chrono::time_point< Clock > event_time) final