Solid
friend class CognitiveNetwork
friend class Neuron
friend class Soma
friend class Membrane
std::vector<Solid*> Solid::polyhedron_list
Referenced by ResetParameters, CreatePolyhedron, CreatePolyhedrons, AddPolyhedron, AddPolyhedrons, GetPolyhedron, GetPolyhedrons, Update.
std::vector<unsigned int> Solid::poly_type_list
Referenced by ResetParameters.
unsigned int Solid::m_Counter
Member variable "m_Counter".
unsigned int Solid::solid_type
bool Solid::object_disabled
bool Solid::object_initialised
std::chrono::time_point<Clock> Solid::time_object_created
std::chrono::time_point<Clock> Solid::previous_event_time
int Solid::duration_since_last_event
int Solid::polyhedron_pool
Solid::Solid()
Solid::Solid(unsigned int object_type)
Solid::Solid(unsigned int object_type, std::chrono::time_point< Clock > event_time)
Solid::Solid(unsigned int object_type, std::chrono::time_point< Clock > event_time, Universe &universe_connector)
References ResetParameters, Universe::Creation.
virtual Solid::~Solid()
Default destructor
bool Solid::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::time_dimension_pointer, Universe::AddDimension, Universe::SetObjectType, Universe::TheTimeNow, poly_type_list, polyhedron_list, TYPE_SOLID_NEURON_GEN1, Universe::object_energy, TYPE_SOLID_POLYHEDRON_SOMA_GEN1, TYPE_SOLID_POLYHEDRON_MEMBRANE_GEN1, TYPE_SOLID_POLYHEDRON_SOMA_AXONHILLOCK_GEN1, TYPE_SOLID_POLYHEDRON_SOMA_AXONHILLOCK_AXON_GEN1, TYPE_SOLID_POLYHEDRON_SOMA_AXONHILLOCK_AXON_AXONBRANCH_GEN1, TYPE_SOLID_POLYHEDRON_SOMA_AXONHILLOCK_AXON_AXONBRANCH_AXONBOUTON_GEN1, TYPE_SOLID_POLYHEDRON_SOMA_DENDRITE_GEN1, TYPE_SOLID_POLYHEDRON_SOMA_DENDRITE_DENDRITEBRANCH_GEN1, TYPE_SOLID_POLYHEDRON_SOMA_DENDRITE_DENDRITEBRANCH_DENDRITECLEFT_GEN1, CreatePolyhedron, Polyhedron::SetObjectType.
Referenced by SetObjectType, Update, Solid.
unsigned int Solid::GetCounter(std::chrono::time_point< Clock > event_time)
void Solid::SetCounter(std::chrono::time_point< Clock > event_time, unsigned int val)
void Solid::SetObjectType(std::chrono::time_point< Clock > event_time, unsigned int val)
References ResetParameters.
Referenced by Axon::Update, AxonBouton::Update, AxonBranch::Update, AxonHillock::Update, Dendrite::Update, DendriteBranch::Update, DendriteCleft::Update, Membrane::Update, Neuron::Update, Soma::Update.
Solid * Solid::CreatePolyhedron(std::chrono::time_point< Clock > event_time)
References polyhedron_list.
Referenced by Axon::Update, AxonBouton::Update, AxonBranch::Update, AxonHillock::Update, Dendrite::Update, DendriteBranch::Update, DendriteCleft::Update, Membrane::Update, ResetParameters, CreatePolyhedrons.
std::vector< Solid * > Solid::CreatePolyhedrons(std::chrono::time_point< Clock > event_time, int quantity)
References polyhedron_list, CreatePolyhedron.
Solid * Solid::ClonePolyhedron(std::chrono::time_point< Clock > event_time, Solid *clone_object, double perfection_membership)
std::vector< Solid * > Solid::ClonePolyhedrons(std::chrono::time_point< Clock > event_time, std::vector< Solid *> cloning_list, double perfection_membership)
Solid * Solid::DestroyPolyhedron(std::chrono::time_point< Clock > event_time, Solid *destroy_object)
std::vector< Solid * > Solid::DestroyPolyhedrons(std::chrono::time_point< Clock > event_time, std::vector< Solid *> destruction_list)
Solid * Solid::AddPolyhedron(std::chrono::time_point< Clock > event_time, Solid *add_object)
References polyhedron_list.
Referenced by AddPolyhedrons.
std::vector< Solid * > Solid::AddPolyhedrons(std::chrono::time_point< Clock > event_time, std::vector< Solid *> add_objects)
References polyhedron_list, AddPolyhedron.
Solid * Solid::RemovePolyhedron(std::chrono::time_point< Clock > event_time)
std::vector< Solid * > Solid::RemovePolyhedrons(std::chrono::time_point< Clock > event_time, int quantity)
Solid * Solid::GetPolyhedron(std::chrono::time_point< Clock > event_time, int selector)
References polyhedron_list.
std::vector< Solid * > Solid::GetPolyhedrons(std::chrono::time_point< Clock > event_time)
References polyhedron_list.
void Solid::GluePolyhedrons(std::chrono::time_point< Clock > event_time)
void Solid::UpdateCycle(std::chrono::time_point< Clock > event_time, std::vector< Solid *> set_of_update_pointers, unsigned int pointer_type)
References Update.
Referenced by Update.
int Solid::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters, UpdateCycle, polyhedron_list, Universe::object_energy.
Referenced by UpdateCycle.
void Solid::SetCharge(std::chrono::time_point< Clock > event_time, int val) final
void Solid::SetSpin(std::chrono::time_point< Clock > event_time, int val) final
double Solid::GetGravitation(std::chrono::time_point< Clock > event_time) final
double Solid::GetWeak(std::chrono::time_point< Clock > event_time) final
double Solid::GetWeakElectroweak(std::chrono::time_point< Clock > event_time) final
double Solid::GetElectromagnetic(std::chrono::time_point< Clock > event_time) final
double Solid::GetElectromagneticElectroweak(std::chrono::time_point< Clock > event_time) final
double Solid::GetStrong(std::chrono::time_point< Clock > event_time) final
double Solid::GetStrongFundamental(std::chrono::time_point< Clock > event_time) final
double Solid::GetStrongResidual(std::chrono::time_point< Clock > event_time) final
double Solid::ApplyGravitation(std::chrono::time_point< Clock > event_time, double val) final
double Solid::ApplyWeak(std::chrono::time_point< Clock > event_time, double val) final
double Solid::ApplyWeakElectroweak(std::chrono::time_point< Clock > event_time, double val) final
double Solid::ApplyElectromagnetic(std::chrono::time_point< Clock > event_time, double val) final
double Solid::ApplyElectromagneticElectroweak(std::chrono::time_point< Clock > event_time, double val) final
double Solid::ApplyStrong(std::chrono::time_point< Clock > event_time, double val) final
double Solid::ApplyStrongFundamental(std::chrono::time_point< Clock > event_time, double val) final
double Solid::ApplyStrongResidual(std::chrono::time_point< Clock > event_time, double val) final
void Solid::SetGravitation(std::chrono::time_point< Clock > event_time, double val) final
void Solid::SetWeak(std::chrono::time_point< Clock > event_time, double val) final
void Solid::SetWeakElectroweak(std::chrono::time_point< Clock > event_time, double val) final
void Solid::SetElectromagnetic(std::chrono::time_point< Clock > event_time, double val) final
void Solid::SetElectromagneticElectroweak(std::chrono::time_point< Clock > event_time, double val) final
void Solid::SetStrong(std::chrono::time_point< Clock > event_time, double val) final
void Solid::SetStrongFundamental(std::chrono::time_point< Clock > event_time, double val) final
void Solid::SetStrongResidual(std::chrono::time_point< Clock > event_time, double val) final
void Solid::PollElementaryForce(std::chrono::time_point< Clock > event_time) final