Synapse
std::vector<CognitiveNetwork*> Synapse::neurotransmitter_list
Referenced by CreateNeurotransmitter, CreateNeurotransmitters, AddNeurotransmitter, AddNeurotransmitters, GetNeurotransmitter, GetNeurotransmitters.
int Synapse::synapse_type
double Synapse::object_size
double Synapse::object_energy
double Synapse::object_energy_threshold
int Synapse::m_NeuronType
int Synapse::neurotransmitter_pool
int Synapse::m_Tag
int Synapse::m_addStatus
int Synapse::m_TauCyclesAdd
int Synapse::m_TauCyclesDecay
int Synapse::m_ChargeType
int Synapse::m_DischargeType
bool Synapse::object_disabled
std::chrono::time_point<Clock> Synapse::time_object_created
std::chrono::time_point<Clock> Synapse::previous_event_time
int Synapse::duration_since_last_event
double Synapse::m_Volume
double Synapse::m_SurfaceArea
unsigned int Synapse::m_Counter
Member variable "m_Counter".
double Synapse::m_axonlength
double Synapse::m_TimeDilation
double Synapse::m_TimeThreshold
bool Synapse::object_initialised
double Synapse::m_ReduceBy
double Synapse::m_ReducedBy
std::vector<s_BindList> Synapse::m_BindList
int Synapse::synapseCounter
Member variable "synapseCounter".
int Synapse::synapseDemand
double Synapse::minimumDistance
std::vector<NearbyNeuron> Synapse::neuronList
std::vector<NearbyNeuron>::iterator Synapse::it
Synapse::Synapse()
Synapse::Synapse(unsigned int object_type)
Synapse::Synapse(unsigned int object_type, std::chrono::time_point< Clock > event_time)
Synapse::Synapse(unsigned int object_type, std::chrono::time_point< Clock > event_time, CognitiveNetwork &cognitivenetwork_connector)
References ResetParameters, Universe::Creation.
virtual Synapse::~Synapse()
Default destructor
double Synapse::GetEnergy(std::chrono::time_point< Clock > event_time)
int Synapse::GetTauCyclesAdd(std::chrono::time_point< Clock > event_time)
int Synapse::GetTauCyclesDecay(std::chrono::time_point< Clock > event_time)
int Synapse::GetChargeType(std::chrono::time_point< Clock > event_time)
int Synapse::GetDischargeType(std::chrono::time_point< Clock > event_time)
int Synapse::GetSynapseDeviceTag(std::chrono::time_point< Clock > event_time)
void Synapse::SetCounter(std::chrono::time_point< Clock > event_time, unsigned int val)
void Synapse::SetEnergy(std::chrono::time_point< Clock > event_time, double val)
void Synapse::SetTauCyclesAdd(std::chrono::time_point< Clock > event_time, int val)
void Synapse::SetTauCyclesDecay(std::chrono::time_point< Clock > event_time, int val)
void Synapse::SetChargeType(std::chrono::time_point< Clock > event_time, int val)
void Synapse::SetDischargeType(std::chrono::time_point< Clock > event_time, int val)
void Synapse::SetSynapseDeviceTag(std::chrono::time_point< Clock > event_time, int val)
bool Synapse::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::TheTimeNow.
Referenced by Update, Synapse.
CognitiveNetwork * Synapse::CreateNeurotransmitter(std::chrono::time_point< Clock > event_time)
References neurotransmitter_list.
Referenced by CreateNeurotransmitters, SendTransmitterSpike.
std::vector< CognitiveNetwork * > Synapse::CreateNeurotransmitters(std::chrono::time_point< Clock > event_time, int quantity)
References neurotransmitter_list, CreateNeurotransmitter.
CognitiveNetwork * Synapse::CloneNeurotransmitter(std::chrono::time_point< Clock > event_time, CognitiveNetwork *clone_object, double perfection_membership)
std::vector< CognitiveNetwork * > Synapse::CloneNeurotransmitters(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> cloning_list, double perfection_membership)
CognitiveNetwork * Synapse::DestroyNeurotransmitter(std::chrono::time_point< Clock > event_time, CognitiveNetwork *destroy_object)
std::vector< CognitiveNetwork * > Synapse::DestroyNeurotransmitters(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> destruction_list)
CognitiveNetwork * Synapse::AddNeurotransmitter(std::chrono::time_point< Clock > event_time, CognitiveNetwork *add_object)
References neurotransmitter_list.
Referenced by AddNeurotransmitters.
std::vector< CognitiveNetwork * > Synapse::AddNeurotransmitters(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> add_objects)
References neurotransmitter_list, AddNeurotransmitter.
CognitiveNetwork * Synapse::RemoveNeurotransmitter(std::chrono::time_point< Clock > event_time)
std::vector< CognitiveNetwork * > Synapse::RemoveNeurotransmitters(std::chrono::time_point< Clock > event_time, int quantity)
CognitiveNetwork * Synapse::GetNeurotransmitter(std::chrono::time_point< Clock > event_time, int selector)
References neurotransmitter_list.
std::vector< CognitiveNetwork * > Synapse::GetNeurotransmitters(std::chrono::time_point< Clock > event_time)
References neurotransmitter_list.
int Synapse::GetDemand(std::chrono::time_point< Clock > event_time)
double Synapse::GetDistance(std::chrono::time_point< Clock > event_time, int val)
int Synapse::GetAllocatedSynapse(std::chrono::time_point< Clock > event_time)
double Synapse::GetMinimumDistance(std::chrono::time_point< Clock > event_time)
void Synapse::GetSynapseList(std::chrono::time_point< Clock > event_time)
void Synapse::SetDemand(std::chrono::time_point< Clock > event_time, int val)
void Synapse::SetNeuron(std::chrono::time_point< Clock > event_time, int val)
void Synapse::SendBareSpike(std::chrono::time_point< Clock > event_time)
Referenced by SendTransmitterSpike.
void Synapse::SendTransmitterSpike(std::chrono::time_point< Clock > event_time)
References CreateNeurotransmitter, SendBareSpike.
int Synapse::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters.