Spike
double Spike::m_attackBegin
double Spike::m_attackLength
double Spike::m_attackPeak
double Spike::m_sustain
double Spike::m_sustainLength
double Spike::m_refactoryBegin
double Spike::m_refactoryLength
double Spike::m_refactoryEnd
double Spike::m_spikeHeight
double Spike::m_spikeHeightReset
double Spike::m_spikeLoop
double Spike::object_energy
int Spike::spike_type
bool Spike::object_disabled
bool Spike::object_initialised
std::chrono::time_point<Clock> Spike::time_object_created
std::chrono::time_point<Clock> Spike::previous_event_time
int Spike::duration_since_last_event
Spike::Spike()
Spike::Spike(unsigned int object_type)
Spike::Spike(unsigned int object_type, std::chrono::time_point< Clock > event_time)
Spike::Spike(unsigned int object_type, std::chrono::time_point< Clock > event_time, CognitiveNetwork &cognitivenetwork_connector)
References ResetParameters, Universe::Creation.
virtual Spike::~Spike()
bool Spike::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::TheTimeNow.
Referenced by Update, Spike.
double Spike::GetSpikeHeightReset(std::chrono::time_point< Clock > event_time)
void Spike::SetSpikeHeightReset(std::chrono::time_point< Clock > event_time, double val)
void Spike::spikeReset(std::chrono::time_point< Clock > event_time)
Referenced by pollSpike.
double Spike::pollSpike(std::chrono::time_point< Clock > event_time)
References spikeReset.
int Spike::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters.