CompositeForceParticle
std::vector<CompositeForceParticle*> CompositeForceParticle::elementary_particle_list
Referenced by Update.
std::vector<CompositeForceParticle*> CompositeForceParticle::elementary_force_list
Referenced by Update.
unsigned int CompositeForceParticle::composite_forceparticle_counter
Member variable "composite_force_counter".
int CompositeForceParticle::composite_forceparticle_type
int CompositeForceParticle::duration_since_last_event
double CompositeForceParticle::composite_forceparticle_gravitation
double CompositeForceParticle::composite_forceparticle_weak
double CompositeForceParticle::composite_forceparticle_weak_electroweak
double CompositeForceParticle::composite_forceparticle_electromagnetic
double CompositeForceParticle::composite_forceparticle_electromagnetic_electroweak
double CompositeForceParticle::composite_forceparticle_strong
double CompositeForceParticle::composite_forceparticle_strong_fundamental
double CompositeForceParticle::composite_forceparticle_strong_residual
std::chrono::time_point<Clock> CompositeForceParticle::time_object_created
std::chrono::time_point<Clock> CompositeForceParticle::previous_event_time
bool CompositeForceParticle::object_disabled
bool CompositeForceParticle::object_initialised
CompositeForceParticle::CompositeForceParticle()
CompositeForceParticle::CompositeForceParticle(unsigned int object_type)
CompositeForceParticle::CompositeForceParticle(unsigned int object_type, std::chrono::time_point< Clock > event_time)
CompositeForceParticle::CompositeForceParticle(unsigned int object_type, std::chrono::time_point< Clock > event_time, Universe &universe_connector)
References ResetParameters, Universe::Creation, Universe::time_dimension_pointer, Universe::AddDimension, Universe::SetObjectType.
virtual CompositeForceParticle::~CompositeForceParticle()
Default destructor
unsigned int CompositeForceParticle::GetCounter(std::chrono::time_point< Clock > event_time)
Access composite_force_counter The current value of composite_force_counter
double CompositeForceParticle::GetGravitation(std::chrono::time_point< Clock > event_time)
double CompositeForceParticle::GetWeak(std::chrono::time_point< Clock > event_time)
double CompositeForceParticle::GetWeakElectroweak(std::chrono::time_point< Clock > event_time)
double CompositeForceParticle::GetElectromagnetic(std::chrono::time_point< Clock > event_time)
double CompositeForceParticle::GetElectromagneticElectroweak(std::chrono::time_point< Clock > event_time)
double CompositeForceParticle::GetStrong(std::chrono::time_point< Clock > event_time)
double CompositeForceParticle::GetStrongFundamental(std::chrono::time_point< Clock > event_time)
double CompositeForceParticle::GetStrongResidual(std::chrono::time_point< Clock > event_time)
double CompositeForceParticle::ApplyGravitation(std::chrono::time_point< Clock > event_time, double val)
double CompositeForceParticle::ApplyWeak(std::chrono::time_point< Clock > event_time, double val)
double CompositeForceParticle::ApplyWeakElectroweak(std::chrono::time_point< Clock > event_time, double val)
double CompositeForceParticle::ApplyElectromagnetic(std::chrono::time_point< Clock > event_time, double val)
double CompositeForceParticle::ApplyElectromagneticElectroweak(std::chrono::time_point< Clock > event_time, double val)
double CompositeForceParticle::ApplyStrong(std::chrono::time_point< Clock > event_time, double val)
double CompositeForceParticle::ApplyStrongFundamental(std::chrono::time_point< Clock > event_time, double val)
double CompositeForceParticle::ApplyStrongResidual(std::chrono::time_point< Clock > event_time, double val)
void CompositeForceParticle::SetCounter(std::chrono::time_point< Clock > event_time, unsigned int val)
void CompositeForceParticle::SetGravitation(std::chrono::time_point< Clock > event_time, double val)
void CompositeForceParticle::SetWeak(std::chrono::time_point< Clock > event_time, double val)
void CompositeForceParticle::SetWeakElectroweak(std::chrono::time_point< Clock > event_time, double val)
void CompositeForceParticle::SetElectromagnetic(std::chrono::time_point< Clock > event_time, double val)
void CompositeForceParticle::SetElectromagneticElectroweak(std::chrono::time_point< Clock > event_time, double val)
void CompositeForceParticle::SetStrong(std::chrono::time_point< Clock > event_time, double val)
void CompositeForceParticle::SetStrongFundamental(std::chrono::time_point< Clock > event_time, double val)
void CompositeForceParticle::SetStrongResidual(std::chrono::time_point< Clock > event_time, double val)
References ResetParameters, CreateElementaryParticle, CreateElementaryParticles, CloneElementaryParticle, CloneElementaryParticles, DestroyElementaryParticle, DestroyElementaryParticles, AddElementaryParticle, AddElementaryParticles, RemoveElementaryParticle, RemoveElementaryParticles, GetElementaryParticle, GetElementaryParticles, CreateElementaryForce, CreateElementaryForces, CloneElementaryForce, CloneElementaryForces, DestroyElementaryForce, DestroyElementaryForces, AddElementaryForce, AddElementaryForces, RemoveElementaryForce, RemoveElementaryForces, GetElementaryForce, GetElementaryForces, UpdateCycle, Update.
bool CompositeForceParticle::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::TheTimeNow.
Referenced by Update, CompositeForceParticle, SetStrongResidual.
CompositeForceParticle* CompositeForceParticle::CreateElementaryParticle(std::chrono::time_point< Clock > event_time)
Referenced by SetStrongResidual.
std::vector<CompositeForceParticle*> CompositeForceParticle::CreateElementaryParticles(std::chrono::time_point< Clock > event_time, int quantity)
Referenced by SetStrongResidual.
CompositeForceParticle* CompositeForceParticle::CloneElementaryParticle(std::chrono::time_point< Clock > event_time, CompositeForceParticle *clone_object, double perfection_membership)
Referenced by SetStrongResidual.
std::vector<CompositeForceParticle*> CompositeForceParticle::CloneElementaryParticles(std::chrono::time_point< Clock > event_time, std::vector< CompositeForceParticle *> cloning_list, double perfection_membership)
Referenced by SetStrongResidual.
CompositeForceParticle* CompositeForceParticle::DestroyElementaryParticle(std::chrono::time_point< Clock > event_time, CompositeForceParticle *destroy_object)
Referenced by SetStrongResidual.
std::vector<CompositeForceParticle*> CompositeForceParticle::DestroyElementaryParticles(std::chrono::time_point< Clock > event_time, std::vector< CompositeForceParticle *> destruction_list)
Referenced by SetStrongResidual.
CompositeForceParticle* CompositeForceParticle::AddElementaryParticle(std::chrono::time_point< Clock > event_time, CompositeForceParticle *add_object)
Referenced by SetStrongResidual.
std::vector<CompositeForceParticle*> CompositeForceParticle::AddElementaryParticles(std::chrono::time_point< Clock > event_time, std::vector< CompositeForceParticle *> add_objects)
Referenced by SetStrongResidual.
CompositeForceParticle* CompositeForceParticle::RemoveElementaryParticle(std::chrono::time_point< Clock > event_time)
Referenced by SetStrongResidual.
std::vector<CompositeForceParticle*> CompositeForceParticle::RemoveElementaryParticles(std::chrono::time_point< Clock > event_time, int quantity)
Referenced by SetStrongResidual.
CompositeForceParticle* CompositeForceParticle::GetElementaryParticle(std::chrono::time_point< Clock > event_time, int selector)
Referenced by SetStrongResidual.
std::vector<CompositeForceParticle*> CompositeForceParticle::GetElementaryParticles(std::chrono::time_point< Clock > event_time)
Referenced by SetStrongResidual.
CompositeForceParticle* CompositeForceParticle::CreateElementaryForce(std::chrono::time_point< Clock > event_time)
Referenced by SetStrongResidual.
std::vector<CompositeForceParticle*> CompositeForceParticle::CreateElementaryForces(std::chrono::time_point< Clock > event_time, int quantity)
Referenced by SetStrongResidual.
CompositeForceParticle* CompositeForceParticle::CloneElementaryForce(std::chrono::time_point< Clock > event_time, CompositeForceParticle *clone_object, double perfection_membership)
Referenced by SetStrongResidual.
std::vector<CompositeForceParticle*> CompositeForceParticle::CloneElementaryForces(std::chrono::time_point< Clock > event_time, std::vector< CompositeForceParticle *> cloning_list, double perfection_membership)
Referenced by SetStrongResidual.
CompositeForceParticle* CompositeForceParticle::DestroyElementaryForce(std::chrono::time_point< Clock > event_time, CompositeForceParticle *destroy_object)
Referenced by SetStrongResidual.
std::vector<CompositeForceParticle*> CompositeForceParticle::DestroyElementaryForces(std::chrono::time_point< Clock > event_time, std::vector< CompositeForceParticle *> destruction_list)
Referenced by SetStrongResidual.
CompositeForceParticle* CompositeForceParticle::AddElementaryForce(std::chrono::time_point< Clock > event_time, CompositeForceParticle *add_object)
Referenced by SetStrongResidual.
std::vector<CompositeForceParticle*> CompositeForceParticle::AddElementaryForces(std::chrono::time_point< Clock > event_time, std::vector< CompositeForceParticle *> add_objects)
Referenced by SetStrongResidual.
CompositeForceParticle* CompositeForceParticle::RemoveElementaryForce(std::chrono::time_point< Clock > event_time)
Referenced by SetStrongResidual.
std::vector<CompositeForceParticle*> CompositeForceParticle::RemoveElementaryForces(std::chrono::time_point< Clock > event_time, int quantity)
Referenced by SetStrongResidual.
CompositeForceParticle* CompositeForceParticle::GetElementaryForce(std::chrono::time_point< Clock > event_time, int selector)
Referenced by SetStrongResidual.
std::vector<CompositeForceParticle*> CompositeForceParticle::GetElementaryForces(std::chrono::time_point< Clock > event_time)
Referenced by SetStrongResidual.
void CompositeForceParticle::UpdateCycle(std::chrono::time_point< Clock > event_time, std::vector< CompositeForceParticle *> set_of_update_pointers, unsigned int pointer_type)
References Update.
Referenced by Update, SetStrongResidual.
int CompositeForceParticle::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters, UpdateCycle, elementary_particle_list, elementary_force_list, Universe::object_energy.
Referenced by UpdateCycle, SetStrongResidual.