Orbital
friend class Neuron
std::vector<CognitiveNetwork*> Orbital::neuron_list
Referenced by AddToNeuronList, AddNeuron, GetNeurons, Update.
unsigned int Orbital::m_Counter
Member variable "m_Counter".
double Orbital::object_energy
int Orbital::orbital_type
int Orbital::m_Tau
double Orbital::m_Position
double Orbital::m_Phase
int Orbital::m_Duration
int Orbital::m_InternalClock
std::chrono::time_point<Clock> Orbital::m_OldClock
std::chrono::time_point<Clock> Orbital::time_object_created
std::chrono::time_point<Clock> Orbital::previous_event_time
int Orbital::duration_since_last_event
bool Orbital::object_disabled
bool Orbital::object_initialised
Orbital::Orbital()
Orbital::Orbital(unsigned int object_type)
Orbital::Orbital(unsigned int object_type, std::chrono::time_point< Clock > event_time)
Orbital::Orbital(unsigned int object_type, std::chrono::time_point< Clock > event_time, CognitiveNetwork &cognitivenetwork_connector)
References ResetParameters, Universe::Creation.
virtual Orbital::~Orbital()
unsigned int Orbital::GetCounter(std::chrono::time_point< Clock > event_time)
double Orbital::GetEnergy(std::chrono::time_point< Clock > event_time)
double Orbital::GetPosition(std::chrono::time_point< Clock > event_time)
double Orbital::GetPhase(std::chrono::time_point< Clock > event_time)
double Orbital::GetTau(std::chrono::time_point< Clock > event_time)
void Orbital::SetPosition(std::chrono::time_point< Clock > event_time, double val)
void Orbital::SetPhase(std::chrono::time_point< Clock > event_time, double val)
void Orbital::SetTau(std::chrono::time_point< Clock > event_time, double val)
void Orbital::SetCounter(std::chrono::time_point< Clock > event_time, unsigned int val)
void Orbital::SetEnergy(std::chrono::time_point< Clock > event_time, double val)
References SetObjectType, ResetParameters, AddToNeuronList, AddNeuron, GetNeurons, CalcPosition, UpdateCycle, Update.
void Orbital::SetObjectType(std::chrono::time_point< Clock > event_time, int object_type)
References ResetParameters.
Referenced by SetEnergy.
bool Orbital::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::time_dimension_pointer, Universe::AddDimension, Universe::SetObjectType, Universe::TheTimeNow.
Referenced by SetObjectType, Update, Orbital, SetEnergy.
std::vector< CognitiveNetwork * > Orbital::AddToNeuronList(CognitiveNetwork *neuron_pointer)
References neuron_list.
Referenced by AddNeuron, SetEnergy.
std::vector< CognitiveNetwork * > Orbital::AddNeuron(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> list_to_add)
References AddToNeuronList, neuron_list.
Referenced by SetEnergy.
std::vector< CognitiveNetwork * > Orbital::GetNeurons(std::chrono::time_point< Clock > event_time)
References neuron_list.
Referenced by SetEnergy.
void Orbital::CalcPosition(std::chrono::time_point< Clock > event_time, double Duration)
References TWORAD.
Referenced by Update, SetEnergy.
void Orbital::UpdateCycle(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> set_of_update_pointers, unsigned int pointer_type)
References CognitiveNetwork::Update.
Referenced by Update, SetEnergy.
int Orbital::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters, UpdateCycle, neuron_list, CalcPosition.
Referenced by SetEnergy.