Universe
friend Universe::Dimension
bool Universe::object_initialised
int Universe::duration_since_last_event
int Universe::default_object_type
int Universe::test_subject_one
int Universe::test_subject_two
int Universe::universe_type
Member variable "universe_type".
double Universe::universe_energy
Member variable "universe_energy".
double Universe::scaled_time
Member variable "scaled_time".
std::chrono::time_point<Clock> Universe::time_object_created
Member variable "time_object_created".
std::chrono::time_point<Clock> Universe::object_expiration
Member variable "object_expiration".
std::chrono::time_point<Clock> Universe::previous_event_time
std::chrono::nanoseconds Universe::object_lifespan
Member variable "object_lifespan".
double Universe::object_energy
Referenced by CompositeForceParticle::Update, ElementaryForce::Update, ElementaryParticle::Update, Law::ResetParameters, Law::Update, Line::ResetParameters, Line::Update, Matter::ResetParameters, Matter::Update, Membrane::ResetParameters, Membrane::Growth, Membrane::Update, Monomer::ResetParameters, Monomer::Update, Point::ResetParameters, Point::Update, Polygon::ResetParameters, Polygon::Update, Polyhedron::ResetParameters, Polyhedron::Update, Polymer::ResetParameters, Polymer::Update, Quad::ResetParameters, Quad::Update, Solid::ResetParameters, Solid::Update, IsDead, Update.
double Universe::object_energy_threshold
Referenced by Law::ResetParameters, Line::ResetParameters, Matter::ResetParameters, Membrane::ResetParameters, Membrane::Growth, Membrane::Update, Monomer::ResetParameters, Point::ResetParameters, Soma::GetEnergyThreshold, Soma::SetEnergyThreshold.
int Universe::object_size
Referenced by Law::ResetParameters, Line::ResetParameters, Matter::ResetParameters, Membrane::ResetParameters, Membrane::Growth, Membrane::Update, Monomer::ResetParameters, Point::ResetParameters.
Universe* Universe::time_dimension_pointer
Referenced by AppTimer::AppTimer, Axon::Update, AxonBouton::Update, AxonBranch::Update, AxonHillock::Update, CognitiveNetwork::ResetParameters, CognitiveOutput::ResetParameters, CompositeForceParticle::CompositeForceParticle, ElementaryForce::ElementaryForce, ElementaryParticle::ElementaryParticle, Matter::Matter, Membrane::ResetParameters, Neuron::ResetParameters, Orbital::ResetParameters, Point::Point, Solid::ResetParameters, Soma::ResetParameters, Update.
std::vector<Universe*> Universe::cognitive_network_list
Referenced by AddCognitiveNetworks, GetCognitiveNetworks, GetCognitiveNetwork, Update, ~Universe.
std::vector<Universe*> Universe::composite_forceparticle_list
Referenced by AddCompositeForceParticles, GetCompositeForceParticles, GetCompositeForceParticle, Update, ~Universe.
std::vector<Universe*> Universe::dimension_list
Referenced by AddDimensions, GetDimensions, GetDimension, ~Universe.
std::vector<Universe*> Universe::elementary_force_list
Referenced by AddElementaryForces, GetElementaryForces, GetElementaryForce, Update, ~Universe.
std::vector<Universe*> Universe::elementary_particle_list
Referenced by AddElementaryParticles, GetElementaryParticles, GetElementaryParticle, Update, ~Universe.
std::vector<Universe*> Universe::matter_list
Referenced by AddMatters, GetMatters, GetMatter, Update, ~Universe.
std::vector<Universe*> Universe::monomer_list
Referenced by AddMonomers, GetMonomers, GetMonomer, Update, ~Universe.
std::vector<Universe*> Universe::polymer_list
Referenced by AddPolymers, GetPolymers, GetPolymer, Update, ~Universe.
std::vector<Universe*> Universe::solid_list
Referenced by AddSolids, GetSolids, GetSolid, Update, ~Universe.
std::vector<Universe*> Universe::point_list
Referenced by AddPoints, GetPoints, GetPoint, Update, ~Universe.
Universe::Universe()
Universe::Universe(int interim_object_type)
Universe::Universe(std::chrono::time_point< Clock > event_time, int object_type)
References Creation, ResetParameters.
virtual Universe::~Universe()
References point_list, solid_list, matter_list, composite_forceparticle_list, elementary_force_list, elementary_particle_list, polymer_list, monomer_list, cognitive_network_list, dimension_list, GetEnergy, SetEnergy, UseEnergy, ReturnEnergy, Creation, SetObjectType, ResetParameters, TheTimeNow, TheCalculatedTimeNow, SetLifespan, ExtendLife, IsDead, AddDimensions, AddDimension, GetDimensions, GetDimension, AddElementaryParticles, AddElementaryParticle, GetElementaryParticles, GetElementaryParticle, AddElementaryForces, AddElementaryForce, GetElementaryForces, GetElementaryForce, AddCompositeForceParticles, AddCompositeForceParticle, GetCompositeForceParticles, GetCompositeForceParticle, AddMatters, AddMatter, GetMatters, GetMatter, AddMonomers, AddMonomer, GetMonomers, GetMonomer, AddPolymers, AddPolymer, GetPolymers, GetPolymer, AddSolids, AddSolid, GetSolids, GetSolid, AddCognitiveNetworks, AddCognitiveNetwork, GetCognitiveNetworks, GetCognitiveNetwork, AddPoints, AddPoint, GetPoints, GetPoint, UpdateCycle, Update, AddTemporalAdjustment, AdjustCounters, SetCharge, SetSpin, GetGravitation, GetWeak, GetWeakElectroweak, GetElectromagnetic, GetElectromagneticElectroweak, GetStrong, GetStrongFundamental, GetStrongResidual, ApplyGravitation, ApplyWeak, ApplyWeakElectroweak, ApplyElectromagnetic, ApplyElectromagneticElectroweak, ApplyStrong, ApplyStrongFundamental, ApplyStrongResidual, SetCounter, SetGravitation, SetWeak, SetWeakElectroweak, SetElectromagnetic, SetElectromagneticElectroweak, SetStrong, SetStrongFundamental, SetStrongResidual, PollElementaryForce.
double Universe::GetEnergy(std::chrono::time_point< Clock > event_time)
Referenced by Update, ~Universe.
void Universe::SetEnergy(std::chrono::time_point< Clock > event_time, double energy_transfer)
Referenced by CreateUniverse, ~Universe.
double Universe::UseEnergy(std::chrono::time_point< Clock > event_time, double energy_transfer)
Referenced by ~Universe.
double Universe::ReturnEnergy(std::chrono::time_point< Clock > event_time, double energy_transfer)
Referenced by ~Universe.
void Universe::Creation(std::chrono::time_point< Clock > event_time, std::string object_title, int object_type)
Referenced by AppTimer::AppTimer, Axon::Axon, AxonBouton::AxonBouton, AxonBranch::AxonBranch, AxonHillock::AxonHillock, CognitiveInput::CognitiveInput, CognitiveNetwork::CognitiveNetwork, CognitiveOutput::CognitiveOutput, CompositeForceParticle::CompositeForceParticle, Dendrite::Dendrite, DendriteBranch::DendriteBranch, DendriteCleft::DendriteCleft, ElementaryForce::ElementaryForce, ElementaryParticle::ElementaryParticle, InterneuronSpace::InterneuronSpace, Law::Law, Line::Line, Matter::Matter, Membrane::Membrane, MembraneChannel::MembraneChannel, Monomer::Monomer, Neuron::Neuron, Neuroreceptor::Neuroreceptor, Neurotransmitter::Neurotransmitter, Orbital::Orbital, Point::Point, Polygon::Polygon, Polyhedron::Polyhedron, Polymer::Polymer, Quad::Quad, Solid::Solid, Soma::Soma, Spike::Spike, Synapse::Synapse, SynapticVesicle::SynapticVesicle, Universe, ~Universe.
void Universe::SetObjectType(std::chrono::time_point< Clock > event_time, int object_type)
References ResetParameters.
Referenced by AppTimer::AppTimer, Axon::Update, AxonBouton::Update, AxonBranch::Update, AxonHillock::Update, CognitiveNetwork::ResetParameters, CognitiveOutput::ResetParameters, CompositeForceParticle::CompositeForceParticle, ElementaryForce::ElementaryForce, ElementaryParticle::ElementaryParticle, Matter::Matter, Membrane::ResetParameters, Neuron::ResetParameters, Orbital::ResetParameters, Point::Point, Solid::ResetParameters, Soma::ResetParameters, Update, ~Universe.
bool Universe::ResetParameters(std::chrono::time_point< Clock > event_time)
References TheTimeNow, SetLifespan.
Referenced by AppTimer::AppTimer, SetObjectType, Update, Universe, ~Universe.
std::chrono::time_point< std::chrono::high_resolution_clock > Universe::TheTimeNow()
References TheCalculatedTimeNow.
Referenced by Axon::ResetParameters, AxonBouton::ResetParameters, AxonBranch::ResetParameters, AxonHillock::ResetParameters, CognitiveInput::ResetParameters, CognitiveNetwork::ResetParameters, CognitiveOutput::ResetParameters, CompositeForceParticle::ResetParameters, Dendrite::ResetParameters, DendriteBranch::ResetParameters, DendriteCleft::ResetParameters, Dimension::TheTimeNow, ElementaryForce::ResetParameters, ElementaryParticle::ResetParameters, InterneuronSpace::ResetParameters, Law::ResetParameters, Line::ResetParameters, Matter::ResetParameters, Membrane::ResetParameters, MembraneChannel::ResetParameters, Monomer::ResetParameters, MyelinSheath::ResetParameters, Neuron::ResetParameters, Neuroreceptor::ResetParameters, Neurotransmitter::ResetParameters, Orbital::ResetParameters, Point::ResetParameters, Polygon::ResetParameters, Polyhedron::ResetParameters, Polymer::ResetParameters, Quad::ResetParameters, Solid::ResetParameters, Soma::ResetParameters, Spike::ResetParameters, Synapse::ResetParameters, SynapticVesicle::ResetParameters, ResetParameters, ExtendLife, IsDead, ~Universe.
std::chrono::time_point< std::chrono::high_resolution_clock > Universe::TheCalculatedTimeNow(std::chrono::time_point< std::chrono::high_resolution_clock > time_object_created_time, std::chrono::time_point< Clock > event_time, double calculated_scaled_time)
Referenced by Dimension::TheTimeNow, TheTimeNow, ~Universe.
void Universe::SetLifespan(std::chrono::time_point< Clock > event_time, std::chrono::nanoseconds life_time)
Referenced by ResetParameters, ~Universe.
void Universe::ExtendLife(std::chrono::time_point< Clock > event_time, std::chrono::nanoseconds life_time)
References IsDead, TheTimeNow.
Referenced by ~Universe.
bool Universe::IsDead(std::chrono::time_point< Clock > event_time)
References TheTimeNow, object_energy.
Referenced by ExtendLife, Update, ~Universe.
std::vector< Universe * > Universe::AddDimensions(std::chrono::time_point< Clock > event_time, int quantity)
References dimension_list.
Referenced by AddDimension, ~Universe.
Universe * Universe::AddDimension(std::chrono::time_point< Clock > event_time)
References AddDimensions.
Referenced by AppTimer::AppTimer, Axon::Update, AxonBouton::Update, AxonBranch::Update, AxonHillock::Update, CognitiveNetwork::ResetParameters, CognitiveOutput::ResetParameters, CompositeForceParticle::CompositeForceParticle, ElementaryForce::ElementaryForce, ElementaryParticle::ElementaryParticle, Matter::Matter, Membrane::ResetParameters, Neuron::ResetParameters, Orbital::ResetParameters, Point::Point, Solid::ResetParameters, Soma::ResetParameters, Update, ~Universe.
std::vector< Universe * > Universe::GetDimensions(std::chrono::time_point< Clock > event_time)
References dimension_list.
Referenced by ~Universe.
Universe * Universe::GetDimension(std::chrono::time_point< Clock > event_time, int selector)
References dimension_list.
Referenced by ~Universe.
std::vector< Universe * > Universe::AddElementaryParticles(std::chrono::time_point< Clock > event_time, int quantity)
References elementary_particle_list.
Referenced by AddElementaryParticle, ~Universe.
Universe * Universe::AddElementaryParticle(std::chrono::time_point< Clock > event_time)
References AddElementaryParticles.
Referenced by ~Universe.
std::vector< Universe * > Universe::GetElementaryParticles(std::chrono::time_point< Clock > event_time)
References elementary_particle_list.
Referenced by ~Universe.
Universe * Universe::GetElementaryParticle(std::chrono::time_point< Clock > event_time, int selector)
References elementary_particle_list.
Referenced by ~Universe.
std::vector< Universe * > Universe::AddElementaryForces(std::chrono::time_point< Clock > event_time, int quantity)
References elementary_force_list.
Referenced by AddElementaryForce, ~Universe.
Universe * Universe::AddElementaryForce(std::chrono::time_point< Clock > event_time)
References AddElementaryForces.
Referenced by ~Universe.
std::vector< Universe * > Universe::GetElementaryForces(std::chrono::time_point< Clock > event_time)
References elementary_force_list.
Referenced by ~Universe.
Universe * Universe::GetElementaryForce(std::chrono::time_point< Clock > event_time, int selector)
References elementary_force_list.
Referenced by ~Universe.
std::vector< Universe * > Universe::AddCompositeForceParticles(std::chrono::time_point< Clock > event_time, int quantity)
References composite_forceparticle_list.
Referenced by AddCompositeForceParticle, ~Universe.
Universe * Universe::AddCompositeForceParticle(std::chrono::time_point< Clock > event_time)
References AddCompositeForceParticles.
Referenced by ~Universe.
std::vector< Universe * > Universe::GetCompositeForceParticles(std::chrono::time_point< Clock > event_time)
References composite_forceparticle_list.
Referenced by ~Universe.
Universe * Universe::GetCompositeForceParticle(std::chrono::time_point< Clock > event_time, int selector)
References composite_forceparticle_list.
Referenced by ~Universe.
std::vector< Universe * > Universe::AddMatters(std::chrono::time_point< Clock > event_time, int quantity)
References matter_list.
Referenced by AddMatter, ~Universe.
Universe * Universe::AddMatter(std::chrono::time_point< Clock > event_time)
References AddMatters.
Referenced by ~Universe.
std::vector< Universe * > Universe::GetMatters(std::chrono::time_point< Clock > event_time)
References matter_list.
Referenced by ~Universe.
Universe * Universe::GetMatter(std::chrono::time_point< Clock > event_time, int selector)
References matter_list.
Referenced by ~Universe.
std::vector< Universe * > Universe::AddMonomers(std::chrono::time_point< Clock > event_time, int quantity)
References monomer_list.
Referenced by AddMonomer, ~Universe.
Universe * Universe::AddMonomer(std::chrono::time_point< Clock > event_time)
References AddMonomers.
Referenced by ~Universe.
std::vector< Universe * > Universe::GetMonomers(std::chrono::time_point< Clock > event_time)
References monomer_list.
Referenced by ~Universe.
Universe * Universe::GetMonomer(std::chrono::time_point< Clock > event_time, int selector)
References monomer_list.
Referenced by ~Universe.
std::vector< Universe * > Universe::AddPolymers(std::chrono::time_point< Clock > event_time, int quantity)
References polymer_list.
Referenced by AddPolymer, ~Universe.
Universe * Universe::AddPolymer(std::chrono::time_point< Clock > event_time)
References AddPolymers.
Referenced by ~Universe.
std::vector< Universe * > Universe::GetPolymers(std::chrono::time_point< Clock > event_time)
References polymer_list.
Referenced by ~Universe.
Universe * Universe::GetPolymer(std::chrono::time_point< Clock > event_time, int selector)
References polymer_list.
Referenced by ~Universe.
std::vector< Universe * > Universe::AddSolids(std::chrono::time_point< Clock > event_time, int quantity)
References solid_list.
Referenced by AddSolid, ~Universe.
Universe * Universe::AddSolid(std::chrono::time_point< Clock > event_time)
References AddSolids.
Referenced by Neuron::Update, ~Universe.
std::vector< Universe * > Universe::GetSolids(std::chrono::time_point< Clock > event_time)
References solid_list.
Referenced by ~Universe.
Universe * Universe::GetSolid(std::chrono::time_point< Clock > event_time, int selector)
References solid_list.
Referenced by ~Universe.
std::vector< Universe * > Universe::AddCognitiveNetworks(std::chrono::time_point< Clock > event_time, int quantity)
References cognitive_network_list.
Referenced by AddCognitiveNetwork, ~Universe.
Universe * Universe::AddCognitiveNetwork(std::chrono::time_point< Clock > event_time)
References AddCognitiveNetworks.
Referenced by ~Universe.
std::vector< Universe * > Universe::GetCognitiveNetworks(std::chrono::time_point< Clock > event_time)
References cognitive_network_list.
Referenced by ~Universe.
Universe * Universe::GetCognitiveNetwork(std::chrono::time_point< Clock > event_time, int selector)
References cognitive_network_list.
Referenced by ~Universe.
std::vector< Universe * > Universe::AddPoints(std::chrono::time_point< Clock > event_time, int quantity)
References point_list.
Referenced by AddPoint, ~Universe.
Universe * Universe::AddPoint(std::chrono::time_point< Clock > event_time)
References AddPoints.
Referenced by Polyhedron::GenerateSpherePoints, Polyhedron::GenerateCylinderPoints, ~Universe.
std::vector< Universe * > Universe::GetPoints(std::chrono::time_point< Clock > event_time)
References point_list.
Referenced by ~Universe.
Universe * Universe::GetPoint(std::chrono::time_point< Clock > event_time, int selector)
References point_list.
Referenced by ~Universe.
void Universe::UpdateCycle(std::chrono::time_point< Clock > event_time, std::vector< Universe *> set_of_update_pointers, unsigned int pointer_type)
References Update.
Referenced by Update, ~Universe.
int Universe::Update(std::chrono::time_point< Clock > event_time)
References time_dimension_pointer, AddDimension, SetObjectType, ResetParameters, UpdateCycle, cognitive_network_list, composite_forceparticle_list, elementary_force_list, elementary_particle_list, matter_list, monomer_list, polymer_list, solid_list, point_list, object_energy, GetEnergy, IsDead.
Referenced by CreateUniverse, Neuron::UpdateCycle2, UpdateCycle, ~Universe.
void Universe::AddTemporalAdjustment(std::chrono::time_point< Clock > event_time, double *point_to_counter, double pool, int interval, int shape)
Referenced by ~Universe.
void Universe::AdjustCounters(std::chrono::time_point< std::chrono::high_resolution_clock > currentTime)
Referenced by Line::Update, Neurotransmitter::Update, ~Universe.
void Universe::SetCharge(std::chrono::time_point< Clock > event_time, int val)
Referenced by ~Universe.
void Universe::SetSpin(std::chrono::time_point< Clock > event_time, int val)
Referenced by ~Universe.
double Universe::GetGravitation(std::chrono::time_point< Clock > event_time)
Referenced by ~Universe.
double Universe::GetWeak(std::chrono::time_point< Clock > event_time)
Referenced by ~Universe.
double Universe::GetWeakElectroweak(std::chrono::time_point< Clock > event_time)
Referenced by ~Universe.
double Universe::GetElectromagnetic(std::chrono::time_point< Clock > event_time)
Referenced by ~Universe.
double Universe::GetElectromagneticElectroweak(std::chrono::time_point< Clock > event_time)
Referenced by ~Universe.
double Universe::GetStrong(std::chrono::time_point< Clock > event_time)
Referenced by ~Universe.
double Universe::GetStrongFundamental(std::chrono::time_point< Clock > event_time)
Referenced by ~Universe.
double Universe::GetStrongResidual(std::chrono::time_point< Clock > event_time)
Referenced by ~Universe.
double Universe::ApplyGravitation(std::chrono::time_point< Clock > event_time, double val)
Referenced by ~Universe.
double Universe::ApplyWeak(std::chrono::time_point< Clock > event_time, double val)
Referenced by ~Universe.
double Universe::ApplyWeakElectroweak(std::chrono::time_point< Clock > event_time, double val)
Referenced by ~Universe.
double Universe::ApplyElectromagnetic(std::chrono::time_point< Clock > event_time, double val)
Referenced by ~Universe.
double Universe::ApplyElectromagneticElectroweak(std::chrono::time_point< Clock > event_time, double val)
Referenced by ~Universe.
double Universe::ApplyStrong(std::chrono::time_point< Clock > event_time, double val)
Referenced by ~Universe.
double Universe::ApplyStrongFundamental(std::chrono::time_point< Clock > event_time, double val)
Referenced by ~Universe.
double Universe::ApplyStrongResidual(std::chrono::time_point< Clock > event_time, double val)
Referenced by ~Universe.
void Universe::SetCounter(std::chrono::time_point< Clock > event_time, unsigned int val)
Referenced by ~Universe.
void Universe::SetGravitation(std::chrono::time_point< Clock > event_time, double val)
Referenced by ~Universe.
void Universe::SetWeak(std::chrono::time_point< Clock > event_time, double val)
Referenced by ~Universe.
void Universe::SetWeakElectroweak(std::chrono::time_point< Clock > event_time, double val)
Referenced by ~Universe.
void Universe::SetElectromagnetic(std::chrono::time_point< Clock > event_time, double val)
Referenced by ~Universe.
void Universe::SetElectromagneticElectroweak(std::chrono::time_point< Clock > event_time, double val)
Referenced by ~Universe.
void Universe::SetStrong(std::chrono::time_point< Clock > event_time, double val)
Referenced by ~Universe.
void Universe::SetStrongFundamental(std::chrono::time_point< Clock > event_time, double val)
Referenced by ~Universe.
void Universe::SetStrongResidual(std::chrono::time_point< Clock > event_time, double val)
Referenced by ~Universe.
void Universe::PollElementaryForce(std::chrono::time_point< Clock > event_time)
Referenced by ~Universe.