MembraneChannel
std::vector<CognitiveNetwork*> MembraneChannel::neurotransmitter_list
Referenced by CreateNeurotransmitter, CreateNeurotransmitters, AddNeurotransmitter, AddNeurotransmitters, GetNeurotransmitter, GetNeurotransmitters.
int MembraneChannel::m_NeuronType
int MembraneChannel::membranechannel_type
int MembraneChannel::neurotransmitter_pool
int MembraneChannel::m_addStatus
std::chrono::time_point<Clock> MembraneChannel::previous_event_time
std::chrono::time_point<Clock> MembraneChannel::time_object_created
int MembraneChannel::duration_since_last_event
double MembraneChannel::m_Volume
double MembraneChannel::m_SurfaceArea
unsigned int MembraneChannel::m_Counter
Member variable "m_Counter".
double MembraneChannel::object_energy
Member variable "object_energy".
double MembraneChannel::object_energy_threshold
double MembraneChannel::m_TimeDilation
double MembraneChannel::m_TimeThreshold
double MembraneChannel::m_Length
bool MembraneChannel::object_initialised
bool MembraneChannel::object_disabled
double MembraneChannel::object_size
double MembraneChannel::object_energyFull
int MembraneChannel::m_Ions
bool MembraneChannel::m_boundReceptor
Member variable "m_boundReceptor".
int MembraneChannel::m_typeReceptor
Member variable "m_typeReceptor".
MembraneChannel::MembraneChannel()
MembraneChannel::MembraneChannel(unsigned int object_type)
MembraneChannel::MembraneChannel(unsigned int object_type, std::chrono::time_point< Clock > event_time)
MembraneChannel::MembraneChannel(unsigned int object_type, std::chrono::time_point< Clock > event_time, Membrane &membrane_connector)
References Universe::Creation.
virtual MembraneChannel::~MembraneChannel()
Default destructor
unsigned int MembraneChannel::GetCounter(std::chrono::time_point< Clock > event_time)
double MembraneChannel::GetEnergy(std::chrono::time_point< Clock > event_time)
bool MembraneChannel::GetReceptorBindingState(std::chrono::time_point< Clock > event_time)
Referenced by Update.
int MembraneChannel::GetReceptorType(std::chrono::time_point< Clock > event_time)
bool MembraneChannel::GetDisabled(std::chrono::time_point< Clock > event_time)
int MembraneChannel::GetIons(std::chrono::time_point< Clock > event_time)
void MembraneChannel::setReceptorBindingState(bool val)
Referenced by toggleDisabled, setDisabled.
void MembraneChannel::toggleReceptorBindingState(std::chrono::time_point< Clock > event_time)
void MembraneChannel::toggleDisabled(std::chrono::time_point< Clock > event_time)
References setReceptorBindingState.
void MembraneChannel::setDisabled(std::chrono::time_point< Clock > event_time, bool val)
References setReceptorBindingState.
void MembraneChannel::setReceptorType(std::chrono::time_point< Clock > event_time, int val)
void MembraneChannel::SetCounter(std::chrono::time_point< Clock > event_time, unsigned int val)
void MembraneChannel::SetEnergy(std::chrono::time_point< Clock > event_time, double val)
void MembraneChannel::SetIons(std::chrono::time_point< Clock > event_time, int val)
bool MembraneChannel::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::TheTimeNow.
Referenced by Update.
CognitiveNetwork * MembraneChannel::CreateNeurotransmitter(std::chrono::time_point< Clock > event_time)
References neurotransmitter_list.
Referenced by CreateNeurotransmitters.
std::vector< CognitiveNetwork * > MembraneChannel::CreateNeurotransmitters(std::chrono::time_point< Clock > event_time, int quantity)
References neurotransmitter_list, CreateNeurotransmitter.
CognitiveNetwork * MembraneChannel::CloneNeurotransmitter(std::chrono::time_point< Clock > event_time, CognitiveNetwork *clone_object, double perfection_membership)
std::vector< CognitiveNetwork * > MembraneChannel::CloneNeurotransmitters(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> cloning_list, double perfection_membership)
CognitiveNetwork * MembraneChannel::DestroyNeurotransmitter(std::chrono::time_point< Clock > event_time, CognitiveNetwork *destroy_object)
std::vector< CognitiveNetwork * > MembraneChannel::DestroyNeurotransmitters(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> destruction_list)
CognitiveNetwork * MembraneChannel::AddNeurotransmitter(std::chrono::time_point< Clock > event_time, CognitiveNetwork *add_object)
References neurotransmitter_list.
Referenced by AddNeurotransmitters.
std::vector< CognitiveNetwork * > MembraneChannel::AddNeurotransmitters(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> add_objects)
References neurotransmitter_list, AddNeurotransmitter.
CognitiveNetwork * MembraneChannel::RemoveNeurotransmitter(std::chrono::time_point< Clock > event_time)
std::vector< CognitiveNetwork * > MembraneChannel::RemoveNeurotransmitters(std::chrono::time_point< Clock > event_time, int quantity)
CognitiveNetwork * MembraneChannel::GetNeurotransmitter(std::chrono::time_point< Clock > event_time, int selector)
References neurotransmitter_list.
std::vector< CognitiveNetwork * > MembraneChannel::GetNeurotransmitters(std::chrono::time_point< Clock > event_time)
References neurotransmitter_list.
bool MembraneChannel::CompatibilityCheck(std::chrono::time_point< Clock > event_time, int neurotransmitterType)
int MembraneChannel::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters, GetReceptorBindingState.