Point
friend class ElementaryParticle
friend class ElementaryForce
friend class CompositeForceParticle
friend class Polyhedron
int Point::point_seq
Member variable "point_seq".
int Point::point_type
Member variable "point_type".
bool Point::object_disabled
Member variable "object_disabled".
bool Point::object_initialised
std::vector<double> Point::point_scale
Member variable "point_scale".
std::vector<double> Point::point_position
Member variable "point_position".
std::vector<double> Point::point_position_min
Member variable "point_position_min".
std::vector<int> Point::point_position_min_overflow
Member variable "point_position_min_overflow".
std::vector<double> Point::point_position_max
Member variable "point_position_max".
std::vector<int> Point::point_position_max_overflow
Member variable "point_position_max_overflow".
std::vector<double> Point::point_move
Member variable "point_move".
std::vector<double> Point::point_move_min
Member variable "point_move_min".
std::vector<int> Point::point_move_min_overflow
Member variable "point_move_min_overflow".
std::vector<double> Point::point_move_max
Member variable "point_move_max".
std::vector<int> Point::point_move_max_overflow
Member variable "point_move_max_overflow".
std::vector<double> Point::point_differential
Member variable "point_differential".
std::vector<double> Point::point_differential_min
Member variable "point_differential_min".
std::vector<int> Point::point_differential_min_overflow
Member variable "point_differential_min_overflow".
std::vector<double> Point::point_differential_max
Member variable "point_differential_max".
std::vector<int> Point::point_differential_max_overflow
Member variable "point_differential_max_overflow".
double Point::point_TTL
Member variable "point_TTL".
double Point::point_TTL_min
Member variable "point_TTL_min".
int Point::point_TTL_min_overflow
Member variable "point_TTL_min_overflow".
double Point::point_TTL_max
Member variable "point_TTL_max".
int Point::point_TTL_max_overflow
Member variable "point_TTL_max_overflow".
std::vector<double> Point::combined_acceleration
Member variable "combined_acceleration".
std::vector<double> Point::distance_apart
Member variable "distance_apart".
std::chrono::time_point<Clock> Point::time_object_created
std::chrono::time_point<Clock> Point::previous_event_time
int Point::duration_since_last_event
Point::Point()
Point::Point(unsigned int object_type)
Point::Point(unsigned int object_type, std::chrono::time_point< Clock > event_time)
Point::Point(unsigned int object_type, std::chrono::time_point< Clock > event_time, Universe &universe_connector)
References ResetParameters, Universe::Creation, Universe::time_dimension_pointer, Universe::AddDimension, Universe::SetObjectType.
virtual Point::~Point()
Default destructor
int Point::GetPointSeq(std::chrono::time_point< Clock > event_time)
Access member variable values
std::vector<double> Point::GetPointScale(std::chrono::time_point< Clock > event_time)
std::vector<double> Point::GetPointPosition(std::chrono::time_point< Clock > event_time)
Referenced by UpdateAllCommand::Execute.
std::vector<double> Point::GetPointPosition2(std::chrono::time_point< Clock > event_time)
std::vector<double> Point::GetPointPositionMin(std::chrono::time_point< Clock > event_time)
std::vector<int> Point::GetPointPositionMinOverflow(std::chrono::time_point< Clock > event_time)
std::vector<double> Point::GetPointPositionMax(std::chrono::time_point< Clock > event_time)
std::vector<int> Point::GetPointPositionMaxOverflow(std::chrono::time_point< Clock > event_time)
std::vector<double> Point::GetPointMove(std::chrono::time_point< Clock > event_time)
std::vector<double> Point::GetPointMoveMin(std::chrono::time_point< Clock > event_time)
std::vector<int> Point::GetPointMoveMinOverflow(std::chrono::time_point< Clock > event_time)
std::vector<double> Point::GetPointMoveMax(std::chrono::time_point< Clock > event_time)
std::vector<int> Point::GetPointMoveMaxOverflow(std::chrono::time_point< Clock > event_time)
std::vector<double> Point::GetPointDifferential(std::chrono::time_point< Clock > event_time)
std::vector<double> Point::GetPointDifferentialMin(std::chrono::time_point< Clock > event_time)
std::vector<int> Point::GetPointDifferentialMinOverflow(std::chrono::time_point< Clock > event_time)
std::vector<double> Point::GetPointDifferentialMax(std::chrono::time_point< Clock > event_time)
std::vector<int> Point::GetPointDifferentialMaxOverflow(std::chrono::time_point< Clock > event_time)
double Point::GetPointTTL(std::chrono::time_point< Clock > event_time)
double Point::GetPointTTLMin(std::chrono::time_point< Clock > event_time)
int Point::GetPointTTLMinOverflow(std::chrono::time_point< Clock > event_time)
double Point::GetPointTTLMax(std::chrono::time_point< Clock > event_time)
int Point::GetPointTTLMaxOverflow(std::chrono::time_point< Clock > event_time)
std::vector<double> Point::RespectLimits(std::chrono::time_point< Clock > event_time, std::vector< double > val)
Set member variable values
References SetObjectType.
Referenced by SetPointPosition, SetPointPositionMin, SetPointPositionMax, SetPointMove, SetPointMoveMin, SetPointMoveMax, SetPointDifferential, SetPointDifferentialMin, SetPointDifferentialMax.
void Point::SetObjectType(std::chrono::time_point< Clock > event_time, unsigned int val)
References ResetParameters.
Referenced by RespectLimits.
void Point::SetPointSeq(std::chrono::time_point< Clock > event_time, int val)
void Point::SetPointScale(std::chrono::time_point< Clock > event_time, std::vector< double > val)
void Point::SetPointPosition(std::chrono::time_point< Clock > event_time, std::vector< double > val)
References RespectLimits.
Referenced by Polyhedron::GenerateSpherePoints, Polyhedron::GenerateCylinderPoints.
void Point::SetPointPositionMin(std::chrono::time_point< Clock > event_time, std::vector< double > val)
References RespectLimits.
void Point::SetPointPositionMinOverflow(std::chrono::time_point< Clock > event_time, std::vector< int > val)
void Point::SetPointPositionMax(std::chrono::time_point< Clock > event_time, std::vector< double > val)
References RespectLimits.
void Point::SetPointPositionMaxOverflow(std::chrono::time_point< Clock > event_time, std::vector< int > val)
void Point::SetPointMove(std::chrono::time_point< Clock > event_time, std::vector< double > val)
References RespectLimits.
void Point::SetPointMoveMin(std::chrono::time_point< Clock > event_time, std::vector< double > val)
References RespectLimits.
void Point::SetPointMoveMinOverflow(std::chrono::time_point< Clock > event_time, std::vector< int > val)
void Point::SetPointMoveMax(std::chrono::time_point< Clock > event_time, std::vector< double > val)
References RespectLimits.
void Point::SetPointMoveMaxOverflow(std::chrono::time_point< Clock > event_time, std::vector< int > val)
void Point::SetPointDifferential(std::chrono::time_point< Clock > event_time, std::vector< double > val)
References RespectLimits.
void Point::SetPointDifferentialMin(std::chrono::time_point< Clock > event_time, std::vector< double > val)
References RespectLimits.
void Point::SetPointDifferentialMinOverflow(std::chrono::time_point< Clock > event_time, std::vector< int > val)
void Point::SetPointDifferentialMax(std::chrono::time_point< Clock > event_time, std::vector< double > val)
References RespectLimits.
void Point::SetPointDifferentialMaxOverflow(std::chrono::time_point< Clock > event_time, std::vector< int > val)
void Point::SetPointTTL(std::chrono::time_point< Clock > event_time, double val)
void Point::SetPointTTLMin(std::chrono::time_point< Clock > event_time, double val)
void Point::SetPointTTLMinOverflow(std::chrono::time_point< Clock > event_time, int val)
void Point::SetPointTTLMax(std::chrono::time_point< Clock > event_time, double val)
void Point::SetPointTTLMaxOverflow(std::chrono::time_point< Clock > event_time, int val)
References ResetParameters, PointForcePoll, Update, PointPoll, OverflowPoll.
bool Point::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::TheTimeNow, Universe::object_energy, Universe::object_energy_threshold, Universe::object_size.
Referenced by SetObjectType, Update, Point, SetPointTTLMaxOverflow.
void Point::PointForcePoll(std::chrono::time_point< Clock > event_time, Point *opposingPoint)
Referenced by SetPointTTLMaxOverflow.
int Point::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters, Universe::object_energy, PointPoll.
Referenced by SetPointTTLMaxOverflow, Polyhedron::UpdateCycle.
void Point::PointPoll(std::chrono::time_point< Clock > event_time, double val)
Referenced by Update, SetPointTTLMaxOverflow.
void Point::OverflowPoll(std::chrono::time_point< Clock > event_time)
Referenced by SetPointTTLMaxOverflow.