Dimension
friend class CognitiveNetwork
friend class CompositeForce
friend class CompositeParticle
friend class ElementaryForce
friend class ElementaryParticle
friend class Matter
friend class Membrane
friend class Monomer
friend class Neuron
friend class Polymer
friend class Point
friend class Solid
friend class Soma
std::vector<CounterAdjustment*> Dimension::temporal_adjustment_list
Referenced by ResetParameters, AdjustCounters.
int Dimension::duration_since_last_event
Referenced by Update.
double Dimension::scale_time
Referenced by TheTimeNow, ResetParameters.
std::chrono::time_point<Clock> Dimension::time_object_created
Member variable "time_object_created".
Referenced by TheTimeNow, ResetParameters, Dimension, Soma::Soma.
std::chrono::time_point<Clock> Dimension::objectExpiration
Member variable "objectExpiration".
std::chrono::time_point<Clock> Dimension::objectLifespan
Member variable "objectLifespan".
double Dimension::object_energy
int Dimension::dimension_type
unsigned int Dimension::dimensionCounter
Member variable "dimensionCounter".
double Dimension::dimension_scale
double Dimension::dimension_time_counter
double Dimension::dimension_offset
unsigned int Dimension::m_Counter
Member variable "m_Counter".
int Dimension::m_OrbitalType
int Dimension::m_Tau
double Dimension::m_Position
double Dimension::m_Phase
int Dimension::m_Duration
int Dimension::m_InternalClock
std::chrono::time_point<Clock> Dimension::previous_event_time
bool Dimension::object_initialised
bool Dimension::object_disabled
Dimension::Dimension()
Dimension::Dimension(unsigned int object_type)
Dimension::Dimension(unsigned int object_type, std::chrono::time_point< Clock > event_time)
Dimension::Dimension(unsigned int object_type, std::chrono::time_point< Clock > event_time, Universe &universe_connector)
References time_object_created, ResetParameters.
virtual Dimension::~Dimension()
unsigned int Dimension::GetCounter(std::chrono::time_point< Clock > event_time)
double Dimension::GetScale(std::chrono::time_point< Clock > event_time)
double Dimension::GetOffset(std::chrono::time_point< Clock > event_time)
std::chrono::time_point< std::chrono::high_resolution_clock > Dimension::TheTimeNow()
References Universe::TheCalculatedTimeNow, time_object_created, Universe::TheTimeNow, scale_time.
Referenced by ResetParameters.
void Dimension::SetCounter(std::chrono::time_point< Clock > event_time, unsigned int val)
void Dimension::SetScale(std::chrono::time_point< Clock > event_time, double val)
void Dimension::SetTime(std::chrono::time_point< Clock > event_time, double val)
void Dimension::SetOffset(std::chrono::time_point< Clock > event_time, double val)
void Dimension::IncScale(std::chrono::time_point< Clock > event_time, double val)
void Dimension::DecScale(std::chrono::time_point< Clock > event_time, double val)
void Dimension::IncTime(std::chrono::time_point< Clock > event_time, double val)
void Dimension::DecTime(std::chrono::time_point< Clock > event_time, double val)
void Dimension::IncOffset(std::chrono::time_point< Clock > event_time, double val)
void Dimension::DecOffset(std::chrono::time_point< Clock > event_time, double val)
void Dimension::SetObjectType(std::chrono::time_point< Clock > event_time, int val)
References ResetParameters.
int Dimension::GetObjectType(std::chrono::time_point< Clock > event_time)
References ResetParameters, AdjustCounters, Update.
bool Dimension::ResetParameters(std::chrono::time_point< Clock > event_time)
References time_object_created, TheTimeNow, scale_time, temporal_adjustment_list, Dimension::CounterAdjustment::counter_begin, Dimension::CounterAdjustment::counter_last_update, Dimension::CounterAdjustment::counter_end, Dimension::CounterAdjustment::point_to_counter, Dimension::CounterAdjustment::pool, Dimension::CounterAdjustment::interval, Dimension::CounterAdjustment::shape.
Referenced by SetObjectType, Update, Dimension, GetObjectType.
void Dimension::AdjustCounters(std::chrono::time_point< std::chrono::high_resolution_clock > currentTime)
References temporal_adjustment_list.
Referenced by GetObjectType.
int Dimension::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters, duration_since_last_event.
Referenced by GetObjectType.
void Dimension::SetCharge(std::chrono::time_point< Clock > event_time, int val) final
void Dimension::SetSpin(std::chrono::time_point< Clock > event_time, int val) final
double Dimension::GetGravitation(std::chrono::time_point< Clock > event_time) final
double Dimension::GetWeak(std::chrono::time_point< Clock > event_time) final
double Dimension::GetWeakElectroweak(std::chrono::time_point< Clock > event_time) final
double Dimension::GetElectromagnetic(std::chrono::time_point< Clock > event_time) final
double Dimension::GetElectromagneticElectroweak(std::chrono::time_point< Clock > event_time) final
double Dimension::GetStrong(std::chrono::time_point< Clock > event_time) final
double Dimension::GetStrongFundamental(std::chrono::time_point< Clock > event_time) final
double Dimension::GetStrongResidual(std::chrono::time_point< Clock > event_time) final
double Dimension::ApplyGravitation(std::chrono::time_point< Clock > event_time, double val) final
double Dimension::ApplyWeak(std::chrono::time_point< Clock > event_time, double val) final
double Dimension::ApplyWeakElectroweak(std::chrono::time_point< Clock > event_time, double val) final
double Dimension::ApplyElectromagnetic(std::chrono::time_point< Clock > event_time, double val) final
double Dimension::ApplyElectromagneticElectroweak(std::chrono::time_point< Clock > event_time, double val) final
double Dimension::ApplyStrong(std::chrono::time_point< Clock > event_time, double val) final
double Dimension::ApplyStrongFundamental(std::chrono::time_point< Clock > event_time, double val) final
double Dimension::ApplyStrongResidual(std::chrono::time_point< Clock > event_time, double val) final
void Dimension::SetGravitation(std::chrono::time_point< Clock > event_time, double val) final
void Dimension::SetWeak(std::chrono::time_point< Clock > event_time, double val) final
void Dimension::SetWeakElectroweak(std::chrono::time_point< Clock > event_time, double val) final
void Dimension::SetElectromagnetic(std::chrono::time_point< Clock > event_time, double val) final
void Dimension::SetElectromagneticElectroweak(std::chrono::time_point< Clock > event_time, double val) final
void Dimension::SetStrong(std::chrono::time_point< Clock > event_time, double val) final
void Dimension::SetStrongFundamental(std::chrono::time_point< Clock > event_time, double val) final
void Dimension::SetStrongResidual(std::chrono::time_point< Clock > event_time, double val) final
void Dimension::PollElementaryForce(std::chrono::time_point< Clock > event_time) final
void Dimension::AddTemporalAdjustment(std::chrono::time_point< Clock > event_time, double *point_to_counter, double pool, int interval, int shape)