AxonHillock
std::vector<AxonHillock*> AxonHillock::axon_list
Referenced by CreateAxon, CreateAxons, AddAxon, AddAxons, GetAxon, GetAxons, Update.
int AxonHillock::m_NeuronType
int AxonHillock::axonhillock_type
bool AxonHillock::object_disabled
bool AxonHillock::object_initialised
int AxonHillock::axon_pool
double AxonHillock::m_Volume
double AxonHillock::m_SurfaceArea
int AxonHillock::m_addStatus
double AxonHillock::object_size
std::chrono::time_point<Clock> AxonHillock::time_object_created
std::chrono::time_point<Clock> AxonHillock::previous_event_time
int AxonHillock::duration_since_last_event
unsigned int AxonHillock::m_Counter
Member variable "m_Counter".
double AxonHillock::object_energy
Member variable "object_energy".
double AxonHillock::object_energy_threshold
double AxonHillock::m_TimeDilation
double AxonHillock::m_TimeThreshold
AxonHillock::AxonHillock()
AxonHillock::AxonHillock(unsigned int object_type)
AxonHillock::AxonHillock(unsigned int object_type, std::chrono::time_point< Clock > event_time)
AxonHillock::AxonHillock(unsigned int object_type, std::chrono::time_point< Clock > event_time, Soma &soma_connector)
References ResetParameters, Universe::Creation.
virtual AxonHillock::~AxonHillock()
Default destructor
unsigned int AxonHillock::GetCounter(std::chrono::time_point< Clock > event_time)
double AxonHillock::GetEnergy(std::chrono::time_point< Clock > event_time)
void AxonHillock::SetCounter(std::chrono::time_point< Clock > event_time, unsigned int val)
void AxonHillock::SetEnergy(std::chrono::time_point< Clock > event_time, double val)
References ResetParameters, CreateAxon, CreateAxons, CloneAxon, CloneAxons, DestroyAxon, DestroyAxons, AddAxon, AddAxons, RemoveAxon, RemoveAxons, GetAxon, GetAxons, Growth, Update.
bool AxonHillock::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::TheTimeNow.
Referenced by Update, AxonHillock, SetEnergy.
AxonHillock * AxonHillock::CreateAxon(std::chrono::time_point< Clock > event_time)
References axon_list.
Referenced by CreateAxons, Update, SetEnergy.
std::vector< AxonHillock * > AxonHillock::CreateAxons(std::chrono::time_point< Clock > event_time, int quantity)
References axon_list, CreateAxon.
Referenced by SetEnergy.
AxonHillock * AxonHillock::CloneAxon(std::chrono::time_point< Clock > event_time, AxonHillock *clone_object, double perfection_membership)
Referenced by SetEnergy.
std::vector< AxonHillock * > AxonHillock::CloneAxons(std::chrono::time_point< Clock > event_time, std::vector< AxonHillock *> cloning_list, double perfection_membership)
Referenced by SetEnergy.
AxonHillock * AxonHillock::DestroyAxon(std::chrono::time_point< Clock > event_time, AxonHillock *destroy_object)
Referenced by SetEnergy.
std::vector< AxonHillock * > AxonHillock::DestroyAxons(std::chrono::time_point< Clock > event_time, std::vector< AxonHillock *> destruction_list)
Referenced by SetEnergy.
AxonHillock * AxonHillock::AddAxon(std::chrono::time_point< Clock > event_time, AxonHillock *add_object)
References axon_list.
Referenced by AddAxons, SetEnergy.
std::vector< AxonHillock * > AxonHillock::AddAxons(std::chrono::time_point< Clock > event_time, std::vector< AxonHillock *> add_objects)
References axon_list, AddAxon.
Referenced by SetEnergy.
AxonHillock * AxonHillock::RemoveAxon(std::chrono::time_point< Clock > event_time)
Referenced by SetEnergy.
std::vector< AxonHillock * > AxonHillock::RemoveAxons(std::chrono::time_point< Clock > event_time, int quantity)
Referenced by SetEnergy.
AxonHillock * AxonHillock::GetAxon(std::chrono::time_point< Clock > event_time, int selector)
References axon_list.
Referenced by SetEnergy.
std::vector< AxonHillock * > AxonHillock::GetAxons(std::chrono::time_point< Clock > event_time)
References axon_list.
Referenced by SetEnergy.
int AxonHillock::Growth(std::chrono::time_point< Clock > event_time)
Referenced by Update, SetEnergy.
int AxonHillock::Update(std::chrono::time_point< Clock > event_time)
References Universe::time_dimension_pointer, Universe::AddDimension, Universe::SetObjectType, ResetParameters, Neuron::visualisation_list, Solid::CreatePolyhedron, Solid::SetObjectType, TYPE_SOLID_POLYHEDRON_SOMA_AXONHILLOCK_GEN1, CreateAxon, Soma::SetObjectType, TYPE_NEURON_PYRAMIDAL_SOMA_AXONHILLOCK_AXON_GEN1, axon_list, Soma::object_connection_list, TYPE_SOLID_POLYHEDRON_SOMA_AXONHILLOCK_AXON_GEN1, Growth.
Referenced by SetEnergy.