MyelinSheath
std::vector<CognitiveNetwork*> MyelinSheath::axonbranch_list
int MyelinSheath::myelinsheath_type
unsigned int MyelinSheath::m_Counter
Member variable "m_Counter".
double MyelinSheath::object_energy
Member variable "object_energy".
double MyelinSheath::object_energy_threshold
double MyelinSheath::object_size
double MyelinSheath::object_energyFull
double MyelinSheath::m_Ions
double MyelinSheath::m_Volume
double MyelinSheath::m_SurfaceArea
double MyelinSheath::m_Length
std::chrono::time_point<Clock> MyelinSheath::previous_event_time
std::chrono::time_point<Clock> MyelinSheath::time_object_created
int MyelinSheath::duration_since_last_event
bool MyelinSheath::object_initialised
bool MyelinSheath::object_disabled
MyelinSheath::MyelinSheath()
MyelinSheath::MyelinSheath(unsigned int object_type)
MyelinSheath::MyelinSheath(unsigned int object_type, std::chrono::time_point< Clock > event_time)
MyelinSheath::MyelinSheath(unsigned int object_type, std::chrono::time_point< Clock > event_time, CognitiveNetwork &cognitivenetwork_connector)
References ResetParameters.
virtual MyelinSheath::~MyelinSheath()
Default destructor
References ResetParameters.
bool MyelinSheath::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::TheTimeNow.
Referenced by Update, MyelinSheath, ~MyelinSheath.
unsigned int MyelinSheath::GetCounter(std::chrono::time_point< Clock > event_time)
double MyelinSheath::GetEnergy(std::chrono::time_point< Clock > event_time)
void MyelinSheath::SetCounter(std::chrono::time_point< Clock > event_time, unsigned int val)
void MyelinSheath::SetEnergy(std::chrono::time_point< Clock > event_time, double val)
References Update.
int MyelinSheath::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters.
Referenced by SetEnergy.