Soma
friend class Dimension
std::vector<Soma*> Soma::axonhillock_list
Referenced by CreateAxonHillock, CreateAxonHillocks, AddAxonHillock, AddAxonHillocks, GetAxonHillock, GetAxonHillocks, Update.
std::vector<Soma*> Soma::dendrite_list
Referenced by CreateDendrite, CreateDendrites, AddDendrite, AddDendrites, GetDendrite, GetDendrites, Growth, Update.
std::vector<ObjectConnection> Soma::object_connection_list
Referenced by Axon::Growth, AxonBranch::Growth, AxonHillock::Update, Update.
Neuron* Soma::parent_pointer
int Soma::m_NeuronType
int Soma::soma_type
int Soma::m_addStatus
std::chrono::time_point<Clock> Soma::time_object_created
std::chrono::time_point<Clock> Soma::previous_event_time
bool Soma::object_disabled
bool Soma::object_initialised
int Soma::duration_since_last_event
double Soma::m_Volume
double Soma::m_SurfaceArea
double Soma::object_size
unsigned int Soma::m_Counter
Member variable "m_Counter".
double Soma::object_energy
Member variable "object_energy".
double Soma::object_energyInc
double Soma::object_energyDec
double Soma::object_energyLeak
double Soma::object_energy_threshold
double Soma::m_TimeDilation
double Soma::m_TimeThreshold
int Soma::axonhillock_pool
int Soma::dendrite_pool
Soma::Soma()
Soma::Soma(unsigned int object_type)
Soma::Soma(unsigned int object_type, std::chrono::time_point< Clock > event_time)
Soma::Soma(unsigned int object_type, std::chrono::time_point< Clock > event_time, Neuron &neuron_connector)
References Dimension::time_object_created, ResetParameters, Universe::Creation.
virtual Soma::~Soma()
Default destructor
double Soma::TimeFunction(double timeDelay, double timeDilation)
unsigned int Soma::GetCounter(std::chrono::time_point< Clock > event_time)
double Soma::GetEnergy(std::chrono::time_point< Clock > event_time)
double Soma::GetEnergyInc(std::chrono::time_point< Clock > event_time)
double Soma::GetEnergyDec(std::chrono::time_point< Clock > event_time)
double Soma::GetEnergyLeak(std::chrono::time_point< Clock > event_time)
double Soma::GetEnergyThreshold(std::chrono::time_point< Clock > event_time)
References Universe::object_energy_threshold.
int Soma::GetAxonHillockPool(std::chrono::time_point< Clock > event_time)
void Soma::SetAxonHillockPool(std::chrono::time_point< Clock > event_time, int set_pool)
int Soma::GetDendritePool(std::chrono::time_point< Clock > event_time)
void Soma::SetDendritePool(std::chrono::time_point< Clock > event_time, int set_pool)
void Soma::SetCounter(std::chrono::time_point< Clock > event_time, unsigned int val)
void Soma::SetEnergy(std::chrono::time_point< Clock > event_time, double val)
void Soma::SetEnergyInc(std::chrono::time_point< Clock > event_time, double val)
void Soma::SetEnergyDec(std::chrono::time_point< Clock > event_time, double val)
void Soma::SetEnergyLeak(std::chrono::time_point< Clock > event_time, double val)
void Soma::SetEnergyThreshold(std::chrono::time_point< Clock > event_time, double val)
References Universe::object_energy_threshold.
void Soma::SetObjectType(std::chrono::time_point< Clock > event_time, int object_type)
References ResetParameters.
Referenced by Axon::Growth, AxonBranch::Growth, AxonHillock::Update, Dendrite::Growth, DendriteBranch::Growth, Neuron::Update, Growth, Update.
bool Soma::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::time_dimension_pointer, Universe::AddDimension, Universe::SetObjectType, Universe::TheTimeNow.
Referenced by SetObjectType, Update, Soma.
Soma * Soma::CreateAxonHillock(std::chrono::time_point< Clock > event_time)
References axonhillock_list.
Referenced by CreateAxonHillocks, Update.
std::vector< Soma * > Soma::CreateAxonHillocks(std::chrono::time_point< Clock > event_time, int quantity)
References axonhillock_list, CreateAxonHillock.
Soma * Soma::CloneAxonHillock(std::chrono::time_point< Clock > event_time, Soma *clone_object, double perfection_membership)
std::vector< Soma * > Soma::CloneAxonHillocks(std::chrono::time_point< Clock > event_time, std::vector< Soma *> cloning_list, double perfection_membership)
Soma * Soma::DestroyAxonHillock(std::chrono::time_point< Clock > event_time, Soma *destroy_object)
std::vector< Soma * > Soma::DestroyAxonHillocks(std::chrono::time_point< Clock > event_time, std::vector< Soma *> destruction_list)
Soma * Soma::AddAxonHillock(std::chrono::time_point< Clock > event_time, Soma *add_object)
References axonhillock_list.
Referenced by AddAxonHillocks.
std::vector< Soma * > Soma::AddAxonHillocks(std::chrono::time_point< Clock > event_time, std::vector< Soma *> add_objects)
References axonhillock_list, AddAxonHillock.
Soma * Soma::RemoveAxonHillock(std::chrono::time_point< Clock > event_time)
std::vector< Soma * > Soma::RemoveAxonHillocks(std::chrono::time_point< Clock > event_time, int quantity)
Soma * Soma::GetAxonHillock(std::chrono::time_point< Clock > event_time, int selector)
References axonhillock_list.
std::vector< Soma * > Soma::GetAxonHillocks(std::chrono::time_point< Clock > event_time)
References axonhillock_list.
Soma * Soma::CreateDendrite(std::chrono::time_point< Clock > event_time)
References dendrite_list.
Referenced by CreateDendrites, Growth.
std::vector< Soma * > Soma::CreateDendrites(std::chrono::time_point< Clock > event_time, int quantity)
References dendrite_list, CreateDendrite.
Soma * Soma::CloneDendrite(std::chrono::time_point< Clock > event_time, Soma *clone_object, double perfection_membership)
std::vector< Soma * > Soma::CloneDendrites(std::chrono::time_point< Clock > event_time, std::vector< Soma *> cloning_list, double perfection_membership)
Soma * Soma::DestroyDendrite(std::chrono::time_point< Clock > event_time, Soma *destroy_object)
std::vector< Soma * > Soma::DestroyDendrites(std::chrono::time_point< Clock > event_time, std::vector< Soma *> destruction_list)
Soma * Soma::AddDendrite(std::chrono::time_point< Clock > event_time, Soma *add_object)
References dendrite_list.
Referenced by AddDendrites.
std::vector< Soma * > Soma::AddDendrites(std::chrono::time_point< Clock > event_time, std::vector< Soma *> add_objects)
References dendrite_list, AddDendrite.
Soma * Soma::RemoveDendrite(std::chrono::time_point< Clock > event_time)
std::vector< Soma * > Soma::RemoveDendrites(std::chrono::time_point< Clock > event_time, int quantity)
Soma * Soma::GetDendrite(std::chrono::time_point< Clock > event_time, int selector)
References dendrite_list.
std::vector< Soma * > Soma::GetDendrites(std::chrono::time_point< Clock > event_time)
References dendrite_list.
int Soma::Growth(std::chrono::time_point< Clock > event_time)
References CreateDendrite, SetObjectType, TYPE_NEURON_PYRAMIDAL_SOMA_DENDRITE_GEN1, dendrite_list.
Referenced by Update.
int Soma::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters, Neuron::GetVisualisationList, Solid::SetObjectType, TYPE_SOLID_POLYHEDRON_SOMA_GEN1, Neuron::visualisation_list, CreateAxonHillock, SetObjectType, TYPE_NEURON_PYRAMIDAL_SOMA_AXONHILLOCK_GEN1, axonhillock_list, object_connection_list, TYPE_SOLID_POLYHEDRON_SOMA_AXONHILLOCK_GEN1, dendrite_list, Growth.
Referenced by Neuron::UpdateCycle.