Sniffex
typedef u_int Sniffex::tcp_seq
void Sniffex::got_packet(u_char *args, const struct pcap_pkthdr *header, const u_char *packet)
References SIZE_ETHERNET, IP_HL, Sniffex::sniff_ip::ip_dst, Sniffex::sniff_ip::ip_p, TH_OFF, Sniffex::sniff_tcp::th_sport, Sniffex::sniff_tcp::th_dport, Sniffex::sniff_ip::ip_len, print_payload.
void Sniffex::print_payload(const u_char *payload, int len)
References print_hex_ascii_line.
Referenced by got_packet.
void Sniffex::print_hex_ascii_line(const u_char *payload, int len, int offset)
Referenced by print_payload.
void Sniffex::print_app_banner(void)
References APP_NAME, APP_DESC, APP_COPYRIGHT, APP_DISCLAIMER.
Referenced by sniffexmain.
void Sniffex::print_app_usage(void)
References APP_NAME.
Referenced by sniffexmain.
int Sniffex::sniffexmain(int argc, char **argv)
References print_app_banner, print_app_usage, SNAP_LEN.