Matter
friend class CompositeForceParticle
unsigned int Matter::matter_counter
Member variable "matter_counter".
int Matter::matter_type
std::chrono::time_point<Clock> Matter::time_object_created
std::chrono::time_point<Clock> Matter::previous_event_time
int Matter::duration_since_last_event
bool Matter::object_initialised
bool Matter::object_disabled
Matter::Matter()
Matter::Matter(unsigned int object_type)
Matter::Matter(unsigned int object_type, std::chrono::time_point< Clock > event_time)
Matter::Matter(unsigned int object_type, std::chrono::time_point< Clock > event_time, Universe &universe_connector)
References ResetParameters, Universe::Creation, Universe::time_dimension_pointer, Universe::AddDimension, Universe::SetObjectType.
virtual Matter::~Matter()
Default destructor
References ResetParameters.
bool Matter::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::TheTimeNow, Universe::object_energy, Universe::object_energy_threshold, Universe::object_size.
Referenced by Update, Matter, ~Matter.
unsigned int Matter::GetCounter(std::chrono::time_point< Clock > event_time)
void Matter::SetCounter(std::chrono::time_point< Clock > event_time, unsigned int val)
References Update.
int Matter::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters, Universe::object_energy.
Referenced by SetCounter.