AxonBranch
std::vector<AxonBranch*> AxonBranch::axonbouton_list
Referenced by AxonBouton::Update, CreateAxonBouton, CreateAxonBoutons, AddAxonBouton, AddAxonBoutons, GetAxonBouton, GetAxonBoutons, Growth.
int AxonBranch::axonbranch_type
int AxonBranch::m_addStatus
int AxonBranch::axonbouton_pool
std::chrono::time_point<Clock> AxonBranch::time_object_created
std::chrono::time_point<Clock> AxonBranch::previous_event_time
int AxonBranch::duration_since_last_event
double AxonBranch::m_Volume
double AxonBranch::m_SurfaceArea
unsigned int AxonBranch::m_Counter
Member variable "m_Counter".
double AxonBranch::object_energy
Member variable "object_energy".
double AxonBranch::m_TimeDilation
double AxonBranch::m_TimeThreshold
double AxonBranch::object_size
bool AxonBranch::object_disabled
bool AxonBranch::object_initialised
double AxonBranch::object_energy_threshold
AxonBranch::AxonBranch()
AxonBranch::AxonBranch(unsigned int object_type)
AxonBranch::AxonBranch(unsigned int object_type, std::chrono::time_point< Clock > event_time)
AxonBranch::AxonBranch(unsigned int object_type, std::chrono::time_point< Clock > event_time, Axon &axon_connector)
References ResetParameters, Universe::Creation.
virtual AxonBranch::~AxonBranch()
Default destructor
unsigned int AxonBranch::GetCounter(std::chrono::time_point< Clock > event_time)
double AxonBranch::GetEnergy(std::chrono::time_point< Clock > event_time)
void AxonBranch::SetCounter(std::chrono::time_point< Clock > event_time, unsigned int val)
void AxonBranch::SetEnergy(std::chrono::time_point< Clock > event_time, double val)
References ResetParameters, CreateAxonBouton, CreateAxonBoutons, CloneAxonBouton, CloneAxonBoutons, DestroyAxonBouton, DestroyAxonBoutons, AddAxonBouton, AddAxonBoutons, RemoveAxonBouton, RemoveAxonBoutons, GetAxonBouton, GetAxonBoutons, Growth, Update.
bool AxonBranch::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::TheTimeNow.
Referenced by Update, AxonBranch, SetEnergy.
AxonBranch * AxonBranch::CreateAxonBouton(std::chrono::time_point< Clock > event_time)
References axonbouton_list.
Referenced by CreateAxonBoutons, Growth, SetEnergy.
std::vector< AxonBranch * > AxonBranch::CreateAxonBoutons(std::chrono::time_point< Clock > event_time, int quantity)
References axonbouton_list, CreateAxonBouton.
Referenced by SetEnergy.
AxonBranch * AxonBranch::CloneAxonBouton(std::chrono::time_point< Clock > event_time, AxonBranch *clone_object, double perfection_membership)
Referenced by SetEnergy.
std::vector< AxonBranch * > AxonBranch::CloneAxonBoutons(std::chrono::time_point< Clock > event_time, std::vector< AxonBranch *> cloning_list, double perfection_membership)
Referenced by SetEnergy.
AxonBranch * AxonBranch::DestroyAxonBouton(std::chrono::time_point< Clock > event_time, AxonBranch *destroy_object)
Referenced by SetEnergy.
std::vector< AxonBranch * > AxonBranch::DestroyAxonBoutons(std::chrono::time_point< Clock > event_time, std::vector< AxonBranch *> destruction_list)
Referenced by SetEnergy.
AxonBranch * AxonBranch::AddAxonBouton(std::chrono::time_point< Clock > event_time, AxonBranch *add_object)
References axonbouton_list.
Referenced by AddAxonBoutons, SetEnergy.
std::vector< AxonBranch * > AxonBranch::AddAxonBoutons(std::chrono::time_point< Clock > event_time, std::vector< AxonBranch *> add_objects)
References axonbouton_list, AddAxonBouton.
Referenced by SetEnergy.
AxonBranch * AxonBranch::RemoveAxonBouton(std::chrono::time_point< Clock > event_time)
Referenced by SetEnergy.
std::vector< AxonBranch * > AxonBranch::RemoveAxonBoutons(std::chrono::time_point< Clock > event_time, int quantity)
Referenced by SetEnergy.
AxonBranch * AxonBranch::GetAxonBouton(std::chrono::time_point< Clock > event_time, int selector)
References axonbouton_list.
Referenced by SetEnergy.
std::vector< AxonBranch * > AxonBranch::GetAxonBoutons(std::chrono::time_point< Clock > event_time)
References axonbouton_list.
Referenced by SetEnergy.
int AxonBranch::Growth(std::chrono::time_point< Clock > event_time)
References CreateAxonBouton, Soma::SetObjectType, TYPE_NEURON_PYRAMIDAL_SOMA_AXONHILLOCK_AXON_AXONBRANCH_AXONBOUTON_GEN1, axonbouton_list, Soma::object_connection_list, TYPE_SOLID_POLYHEDRON_SOMA_AXONHILLOCK_AXON_AXONBRANCH_GEN1, TYPE_SOLID_POLYHEDRON_SOMA_AXONHILLOCK_AXON_AXONBRANCH_AXONBOUTON_GEN1.
Referenced by SetEnergy.
int AxonBranch::Update(std::chrono::time_point< std::chrono::high_resolution_clock > val)
References Universe::time_dimension_pointer, Universe::AddDimension, Universe::SetObjectType, ResetParameters, Neuron::visualisation_list, Solid::CreatePolyhedron, Solid::SetObjectType, TYPE_SOLID_POLYHEDRON_SOMA_AXONHILLOCK_AXON_AXONBRANCH_GEN1.
Referenced by SetEnergy.