Neuroreceptor
std::vector<CognitiveNetwork*> Neuroreceptor::neurotransmitter_list
Referenced by CreateNeurotransmitter, CreateNeurotransmitters, AddNeurotransmitter, AddNeurotransmitters, GetNeurotransmitter, GetNeurotransmitters.
int Neuroreceptor::m_NeuronType
int Neuroreceptor::neuroreceptor_type
int Neuroreceptor::neurotransmitter_pool
int Neuroreceptor::m_addStatus
std::chrono::time_point<Clock> Neuroreceptor::previous_event_time
std::chrono::time_point<Clock> Neuroreceptor::time_object_created
int Neuroreceptor::duration_since_last_event
double Neuroreceptor::m_Volume
double Neuroreceptor::m_SurfaceArea
unsigned int Neuroreceptor::m_Counter
Member variable "m_Counter".
double Neuroreceptor::object_energy
Member variable "object_energy".
double Neuroreceptor::object_energy_threshold
double Neuroreceptor::m_TimeDilation
double Neuroreceptor::m_TimeThreshold
double Neuroreceptor::m_Length
bool Neuroreceptor::object_initialised
bool Neuroreceptor::object_disabled
double Neuroreceptor::object_size
double Neuroreceptor::object_energyFull
int Neuroreceptor::m_Ions
bool Neuroreceptor::m_boundReceptor
Member variable "m_boundReceptor".
int Neuroreceptor::m_typeReceptor
Member variable "m_typeReceptor".
Neuroreceptor::Neuroreceptor()
Neuroreceptor::Neuroreceptor(unsigned int object_type)
Neuroreceptor::Neuroreceptor(unsigned int object_type, std::chrono::time_point< Clock > event_time)
Neuroreceptor::Neuroreceptor(unsigned int object_type, std::chrono::time_point< Clock > event_time, DendriteCleft &dendritecleft_connector)
References Universe::Creation.
virtual Neuroreceptor::~Neuroreceptor()
Default destructor
unsigned int Neuroreceptor::GetCounter(std::chrono::time_point< Clock > event_time)
double Neuroreceptor::GetEnergy(std::chrono::time_point< Clock > event_time)
bool Neuroreceptor::GetReceptorBindingState(std::chrono::time_point< Clock > event_time)
Referenced by Update.
int Neuroreceptor::GetReceptorType(std::chrono::time_point< Clock > event_time)
bool Neuroreceptor::GetDisabled(std::chrono::time_point< Clock > event_time)
int Neuroreceptor::GetIons(std::chrono::time_point< Clock > event_time)
void Neuroreceptor::SetReceptorBindingState(std::chrono::time_point< Clock > event_time, bool val)
Referenced by Update, ToggleDisabled, SetDisabled.
void Neuroreceptor::ToggleReceptorBindingState(std::chrono::time_point< Clock > event_time)
void Neuroreceptor::ToggleDisabled(std::chrono::time_point< Clock > event_time)
References SetReceptorBindingState.
void Neuroreceptor::SetDisabled(std::chrono::time_point< Clock > event_time, bool val)
References SetReceptorBindingState.
void Neuroreceptor::SetReceptorType(std::chrono::time_point< Clock > event_time, int val)
void Neuroreceptor::SetCounter(std::chrono::time_point< Clock > event_time, unsigned int val)
void Neuroreceptor::SetEnergy(std::chrono::time_point< Clock > event_time, double val)
void Neuroreceptor::SetIons(std::chrono::time_point< Clock > event_time, int val)
References ResetParameters, CreateNeurotransmitter, CreateNeurotransmitters, CloneNeurotransmitter, CloneNeurotransmitters, DestroyNeurotransmitter, DestroyNeurotransmitters, AddNeurotransmitter, AddNeurotransmitters, RemoveNeurotransmitter, RemoveNeurotransmitters, GetNeurotransmitter, GetNeurotransmitters, CompatibilityCheck, Update.
bool Neuroreceptor::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::TheTimeNow.
Referenced by Update, SetIons.
CognitiveNetwork * Neuroreceptor::CreateNeurotransmitter(std::chrono::time_point< Clock > event_time)
References neurotransmitter_list.
Referenced by CreateNeurotransmitters, SetIons.
std::vector< CognitiveNetwork * > Neuroreceptor::CreateNeurotransmitters(std::chrono::time_point< Clock > event_time, int quantity)
References neurotransmitter_list, CreateNeurotransmitter.
Referenced by SetIons.
CognitiveNetwork * Neuroreceptor::CloneNeurotransmitter(std::chrono::time_point< Clock > event_time, CognitiveNetwork *clone_object, double perfection_membership)
Referenced by SetIons.
std::vector< CognitiveNetwork * > Neuroreceptor::CloneNeurotransmitters(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> cloning_list, double perfection_membership)
Referenced by SetIons.
CognitiveNetwork * Neuroreceptor::DestroyNeurotransmitter(std::chrono::time_point< Clock > event_time, CognitiveNetwork *destroy_object)
Referenced by SetIons.
std::vector< CognitiveNetwork * > Neuroreceptor::DestroyNeurotransmitters(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> destruction_list)
Referenced by SetIons.
CognitiveNetwork * Neuroreceptor::AddNeurotransmitter(std::chrono::time_point< Clock > event_time, CognitiveNetwork *add_object)
References neurotransmitter_list.
Referenced by AddNeurotransmitters, SetIons.
std::vector< CognitiveNetwork * > Neuroreceptor::AddNeurotransmitters(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> add_objects)
References neurotransmitter_list, AddNeurotransmitter.
Referenced by SetIons.
CognitiveNetwork * Neuroreceptor::RemoveNeurotransmitter(std::chrono::time_point< Clock > event_time)
Referenced by SetIons.
std::vector< CognitiveNetwork * > Neuroreceptor::RemoveNeurotransmitters(std::chrono::time_point< Clock > event_time, int quantity)
Referenced by SetIons.
CognitiveNetwork * Neuroreceptor::GetNeurotransmitter(std::chrono::time_point< Clock > event_time, int selector)
References neurotransmitter_list.
Referenced by SetIons.
std::vector< CognitiveNetwork * > Neuroreceptor::GetNeurotransmitters(std::chrono::time_point< Clock > event_time)
References neurotransmitter_list.
Referenced by SetIons.
bool Neuroreceptor::CompatibilityCheck(std::chrono::time_point< Clock > event_time, int neurotransmitterType)
Referenced by SetIons.
int Neuroreceptor::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters, GetReceptorBindingState, SetReceptorBindingState.
Referenced by SetIons.