Neurotransmitter
int Neurotransmitter::m_NeurotransmitterType
int Neurotransmitter::neurotransmitter_type
int Neurotransmitter::m_addStatus
std::chrono::time_point<Clock> Neurotransmitter::time_object_created
std::chrono::time_point<Clock> Neurotransmitter::previous_event_time
bool Neurotransmitter::object_disabled
bool Neurotransmitter::object_initialised
int Neurotransmitter::duration_since_last_event
double Neurotransmitter::m_Volume
double Neurotransmitter::m_SurfaceArea
double Neurotransmitter::object_size
unsigned int Neurotransmitter::m_Counter
Member variable "m_Counter".
double Neurotransmitter::object_energy
Member variable "object_energy".
double Neurotransmitter::object_energy_threshold
double Neurotransmitter::m_TimeDilation
double Neurotransmitter::m_TimeThreshold
Neurotransmitter::Neurotransmitter()
Neurotransmitter::Neurotransmitter(unsigned int object_type)
Neurotransmitter::Neurotransmitter(unsigned int object_type, std::chrono::time_point< Clock > event_time)
Neurotransmitter::Neurotransmitter(unsigned int object_type, std::chrono::time_point< Clock > event_time, CognitiveNetwork &cognitivenetwork_connector)
References ResetParameters, Universe::Creation.
virtual Neurotransmitter::~Neurotransmitter()
Default destructor
unsigned int Neurotransmitter::GetCounter(std::chrono::time_point< Clock > event_time)
double Neurotransmitter::GetEnergy(std::chrono::time_point< Clock > event_time)
int Neurotransmitter::GetType(std::chrono::time_point< Clock > event_time)
void Neurotransmitter::SetType(std::chrono::time_point< Clock > event_time, int val)
void Neurotransmitter::SetCounter(std::chrono::time_point< Clock > event_time, unsigned int val)
void Neurotransmitter::SetEnergy(std::chrono::time_point< Clock > event_time, double val)
References ResetParameters, Update.
bool Neurotransmitter::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::TheTimeNow.
Referenced by Update, Neurotransmitter, SetEnergy.
int Neurotransmitter::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters, Universe::AdjustCounters.
Referenced by SetEnergy.