InterneuronSpace
std::vector<CognitiveNetwork*> InterneuronSpace::neurotransmitter_list
Referenced by CreateNeurotransmitter, CreateNeurotransmitters, AddNeurotransmitter, AddNeurotransmitters, GetNeurotransmitter, GetNeurotransmitters.
int InterneuronSpace::interneuronspace_type
double InterneuronSpace::object_size
double InterneuronSpace::object_energy
double InterneuronSpace::object_energy_threshold
int InterneuronSpace::m_NeuronType
int InterneuronSpace::neurotransmitter_pool
int InterneuronSpace::m_Tag
int InterneuronSpace::m_addStatus
int InterneuronSpace::m_TauCyclesAdd
int InterneuronSpace::m_TauCyclesDecay
int InterneuronSpace::m_ChargeType
int InterneuronSpace::m_DischargeType
bool InterneuronSpace::object_disabled
std::chrono::time_point<Clock> InterneuronSpace::time_object_created
std::chrono::time_point<Clock> InterneuronSpace::previous_event_time
int InterneuronSpace::duration_since_last_event
double InterneuronSpace::m_Volume
double InterneuronSpace::m_SurfaceArea
unsigned int InterneuronSpace::m_Counter
Member variable "m_Counter".
double InterneuronSpace::m_axonlength
double InterneuronSpace::m_TimeDilation
double InterneuronSpace::m_TimeThreshold
bool InterneuronSpace::object_initialised
double InterneuronSpace::m_ReduceBy
double InterneuronSpace::m_ReducedBy
std::vector<s_BindList> InterneuronSpace::m_BindList
int InterneuronSpace::interneuronspaceCounter
Member variable "interneuronspaceCounter".
int InterneuronSpace::interneuronspaceDemand
double InterneuronSpace::minimumDistance
std::vector<NearbyNeuron> InterneuronSpace::neuronList
std::vector<NearbyNeuron>::iterator InterneuronSpace::it
InterneuronSpace::InterneuronSpace()
InterneuronSpace::InterneuronSpace(unsigned int object_type)
InterneuronSpace::InterneuronSpace(unsigned int object_type, std::chrono::time_point< Clock > event_time)
InterneuronSpace::InterneuronSpace(unsigned int object_type, std::chrono::time_point< Clock > event_time, CognitiveNetwork &cognitivenetwork_connector)
References ResetParameters, Universe::Creation.
virtual InterneuronSpace::~InterneuronSpace()
Default destructor
double InterneuronSpace::GetEnergy(std::chrono::time_point< Clock > event_time)
int InterneuronSpace::GetTauCyclesAdd(std::chrono::time_point< Clock > event_time)
int InterneuronSpace::GetTauCyclesDecay(std::chrono::time_point< Clock > event_time)
int InterneuronSpace::GetChargeType(std::chrono::time_point< Clock > event_time)
int InterneuronSpace::GetDischargeType(std::chrono::time_point< Clock > event_time)
int InterneuronSpace::GetInterneuronSpaceDeviceTag(std::chrono::time_point< Clock > event_time)
void InterneuronSpace::SetCounter(std::chrono::time_point< Clock > event_time, unsigned int val)
void InterneuronSpace::SetEnergy(std::chrono::time_point< Clock > event_time, double val)
void InterneuronSpace::SetTauCyclesAdd(std::chrono::time_point< Clock > event_time, int val)
void InterneuronSpace::SetTauCyclesDecay(std::chrono::time_point< Clock > event_time, int val)
void InterneuronSpace::SetChargeType(std::chrono::time_point< Clock > event_time, int val)
void InterneuronSpace::SetDischargeType(std::chrono::time_point< Clock > event_time, int val)
void InterneuronSpace::SetInterneuronSpaceDeviceTag(std::chrono::time_point< Clock > event_time, int val)
References ResetParameters, CreateNeurotransmitter, CreateNeurotransmitters, CloneNeurotransmitter, CloneNeurotransmitters, DestroyNeurotransmitter, DestroyNeurotransmitters, AddNeurotransmitter, AddNeurotransmitters, RemoveNeurotransmitter, RemoveNeurotransmitters, GetNeurotransmitter, GetNeurotransmitters, GetDemand, GetDistance, GetAllocatedInterneuronSpace, GetMinimumDistance, GetInterneuronSpaceList, SetDemand, SetNeuron, SendBareSpike, SendTransmitterSpike, Update.
bool InterneuronSpace::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::TheTimeNow.
Referenced by Update, InterneuronSpace, SetInterneuronSpaceDeviceTag.
CognitiveNetwork * InterneuronSpace::CreateNeurotransmitter(std::chrono::time_point< Clock > event_time)
References neurotransmitter_list.
Referenced by CreateNeurotransmitters, SendTransmitterSpike, SetInterneuronSpaceDeviceTag.
std::vector< CognitiveNetwork * > InterneuronSpace::CreateNeurotransmitters(std::chrono::time_point< Clock > event_time, int quantity)
References neurotransmitter_list, CreateNeurotransmitter.
Referenced by SetInterneuronSpaceDeviceTag.
CognitiveNetwork * InterneuronSpace::CloneNeurotransmitter(std::chrono::time_point< Clock > event_time, CognitiveNetwork *clone_object, double perfection_membership)
Referenced by SetInterneuronSpaceDeviceTag.
std::vector< CognitiveNetwork * > InterneuronSpace::CloneNeurotransmitters(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> cloning_list, double perfection_membership)
Referenced by SetInterneuronSpaceDeviceTag.
CognitiveNetwork * InterneuronSpace::DestroyNeurotransmitter(std::chrono::time_point< Clock > event_time, CognitiveNetwork *destroy_object)
Referenced by SetInterneuronSpaceDeviceTag.
std::vector< CognitiveNetwork * > InterneuronSpace::DestroyNeurotransmitters(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> destruction_list)
Referenced by SetInterneuronSpaceDeviceTag.
CognitiveNetwork * InterneuronSpace::AddNeurotransmitter(std::chrono::time_point< Clock > event_time, CognitiveNetwork *add_object)
References neurotransmitter_list.
Referenced by AddNeurotransmitters, SetInterneuronSpaceDeviceTag.
std::vector< CognitiveNetwork * > InterneuronSpace::AddNeurotransmitters(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> add_objects)
References neurotransmitter_list, AddNeurotransmitter.
Referenced by SetInterneuronSpaceDeviceTag.
CognitiveNetwork * InterneuronSpace::RemoveNeurotransmitter(std::chrono::time_point< Clock > event_time)
Referenced by SetInterneuronSpaceDeviceTag.
std::vector< CognitiveNetwork * > InterneuronSpace::RemoveNeurotransmitters(std::chrono::time_point< Clock > event_time, int quantity)
Referenced by SetInterneuronSpaceDeviceTag.
CognitiveNetwork * InterneuronSpace::GetNeurotransmitter(std::chrono::time_point< Clock > event_time, int selector)
References neurotransmitter_list.
Referenced by SetInterneuronSpaceDeviceTag.
std::vector< CognitiveNetwork * > InterneuronSpace::GetNeurotransmitters(std::chrono::time_point< Clock > event_time)
References neurotransmitter_list.
Referenced by SetInterneuronSpaceDeviceTag.
int InterneuronSpace::GetDemand(std::chrono::time_point< Clock > event_time)
Referenced by SetInterneuronSpaceDeviceTag.
double InterneuronSpace::GetDistance(std::chrono::time_point< Clock > event_time, int val)
Referenced by SetInterneuronSpaceDeviceTag.
int InterneuronSpace::GetAllocatedInterneuronSpace(std::chrono::time_point< Clock > event_time)
Referenced by SetInterneuronSpaceDeviceTag.
double InterneuronSpace::GetMinimumDistance(std::chrono::time_point< Clock > event_time)
Referenced by SetInterneuronSpaceDeviceTag.
void InterneuronSpace::GetInterneuronSpaceList(std::chrono::time_point< Clock > event_time)
Referenced by SetInterneuronSpaceDeviceTag.
void InterneuronSpace::SetDemand(std::chrono::time_point< Clock > event_time, int val)
Referenced by SetInterneuronSpaceDeviceTag.
void InterneuronSpace::SetNeuron(std::chrono::time_point< Clock > event_time, int val)
Referenced by SetInterneuronSpaceDeviceTag.
void InterneuronSpace::SendBareSpike(std::chrono::time_point< Clock > event_time)
Referenced by SendTransmitterSpike, SetInterneuronSpaceDeviceTag.
void InterneuronSpace::SendTransmitterSpike(std::chrono::time_point< Clock > event_time)
References CreateNeurotransmitter, SendBareSpike.
Referenced by SetInterneuronSpaceDeviceTag.
int InterneuronSpace::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters.
Referenced by SetInterneuronSpaceDeviceTag.