Line
int Line::lineLineID
int Line::line_type
double Line::lineLineX1
Member variable "lineLineX1".
double Line::lineLineY1
Member variable "lineLineY1".
double Line::lineLineX2
Member variable "lineLineX2".
double Line::lineLineY2
Member variable "lineLineY2".
double Line::lineSlope
Member variable "lineSlope".
double Line::lineYint
Member variable "lineYint".
double Line::lineLineTTL
Member variable "lineLineTTL".
int Line::lineLineSeq
int Line::lineLineCounter
std::chrono::time_point<Clock> Line::time_object_created
std::chrono::time_point<Clock> Line::previous_event_time
int Line::duration_since_last_event
bool Line::object_disabled
bool Line::object_initialised
Line::Line()
Line::Line(unsigned int object_type)
Line::Line(unsigned int object_type, std::chrono::time_point< Clock > event_time)
Line::Line(unsigned int object_type, std::chrono::time_point< Clock > event_time, Universe &universe_connector)
References ResetParameters, Universe::Creation.
virtual Line::~Line()
Default destructor
bool Line::ResetParameters(std::chrono::time_point< Clock > event_time)
Access lineCounter The current value of lineCounter
References Universe::TheTimeNow, Universe::object_energy, Universe::object_energy_threshold, Universe::object_size.
Referenced by Update, Line.
int Line::GetLineID(std::chrono::time_point< Clock > event_time)
double Line::GetLineXYBubble(std::chrono::time_point< Clock > event_time) const
References GetLineX1Y1Bubble, GetLineX2Y2Bubble.
double Line::GetLineX1(std::chrono::time_point< Clock > event_time) const
double Line::GetLineY1(std::chrono::time_point< Clock > event_time) const
double Line::GetLineX1Y1Bubble(std::chrono::time_point< Clock > event_time) const
Referenced by GetLineXYBubble.
double Line::GetLineX2(std::chrono::time_point< Clock > event_time) const
double Line::GetLineY2(std::chrono::time_point< Clock > event_time) const
double Line::GetLineX2Y2Bubble(std::chrono::time_point< Clock > event_time) const
Referenced by GetLineXYBubble.
double Line::GetLineXMin(std::chrono::time_point< Clock > event_time)
double Line::GetLineYMin(std::chrono::time_point< Clock > event_time)
double Line::GetLineXMax(std::chrono::time_point< Clock > event_time)
double Line::GetLineYMax(std::chrono::time_point< Clock > event_time)
double Line::GetLineMinOrdinal(std::chrono::time_point< Clock > event_time)
double Line::GetLineMaxOrdinal(std::chrono::time_point< Clock > event_time)
double Line::GetSlope(std::chrono::time_point< Clock > event_time)
double Line::GetYint(std::chrono::time_point< Clock > event_time)
double Line::GetLineTTL(std::chrono::time_point< Clock > event_time) const
int Line::GetLineSeq(std::chrono::time_point< Clock > event_time)
int Line::GetLineCounter(std::chrono::time_point< Clock > event_time) const
bool Line::GetInLine(std::chrono::time_point< Clock > event_time, double X1, double Y1, double X2, double Y2, double Threshold)
void Line::setLineID(std::chrono::time_point< Clock > event_time, int val)
set lineCounter val New value to set
void Line::setLineX1(std::chrono::time_point< Clock > event_time, double val)
void Line::setLineY1(std::chrono::time_point< Clock > event_time, double val)
void Line::setLineX2(std::chrono::time_point< Clock > event_time, double val)
void Line::setLineY2(std::chrono::time_point< Clock > event_time, double val)
void Line::setSlope(std::chrono::time_point< Clock > event_time, double val)
void Line::setYint(std::chrono::time_point< Clock > event_time, double val)
void Line::setLineTTL(std::chrono::time_point< Clock > event_time, double val)
void Line::setLineSeq(std::chrono::time_point< Clock > event_time, int val)
void Line::setLineCounter(std::chrono::time_point< Clock > event_time, int val)
int Line::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters, Universe::AdjustCounters, Universe::object_energy.