Neuron
friend class Orbital
std::vector<Neuron*> Neuron::soma_list
Referenced by CreateSoma, CreateSomas, AddSoma, AddSomas, GetSoma, GetSomas, Update.
std::vector<Neuron*> Neuron::membrane_list
Referenced by CreateMembrane, CreateMembranes, AddMembrane, AddMembranes, GetMembrane, GetMembranes, Update.
std::vector<Universe*> Neuron::visualisation_list
Referenced by Axon::Update, AxonBouton::Update, AxonBranch::Update, AxonHillock::Update, Dendrite::Update, DendriteBranch::Update, DendriteCleft::Update, Update, GetVisualisationList, Soma::Update.
std::vector<ObjectConnection> Neuron::object_connection_list
int Neuron::neuron_type
int Neuron::m_Tag
int Neuron::membrane_pool
double Neuron::object_size
double Neuron::m_RestingPotential
bool Neuron::object_initialised
bool Neuron::object_disabled
std::chrono::time_point<Clock> Neuron::time_object_created
std::chrono::time_point<Clock> Neuron::previous_event_time
int Neuron::duration_since_last_event
int Neuron::m_addStatus
int Neuron::m_Counter
Member variable "m_Counter".
double Neuron::object_energy
Member variable "object_energy".
double Neuron::object_energy_threshold
double Neuron::m_Spike
Member variable "m_Spike".
double Neuron::m_GateKeeper
Member variable "m_GateKeeper".
double Neuron::m_ChannelMin
Member variable "m_ChannelMin".
double Neuron::m_ChannelMax
Member variable "m_ChannelMax".
double Neuron::m_TimeDilation
double Neuron::m_TimeThreshold
unsigned int Neuron::neuronCounter
Member variable "elementaryParticleCounter".
int Neuron::neuronCapacity
int Neuron::neuronUsage
int Neuron::soma_pool
Neuron::Neuron()
Neuron::Neuron(unsigned int object_type)
Neuron::Neuron(unsigned int object_type, std::chrono::time_point< Clock > event_time)
Neuron::Neuron(unsigned int object_type, std::chrono::time_point< Clock > event_time, CognitiveNetwork &cognitivenetwork_connector)
References ResetParameters, Universe::Creation.
virtual Neuron::~Neuron()
Default destructor
unsigned int Neuron::GetCounter(std::chrono::time_point< Clock > event_time)
int Neuron::GetCapacity(std::chrono::time_point< Clock > event_time)
void Neuron::SetCapacity(std::chrono::time_point< Clock > event_time, int val)
int Neuron::GetUsage(std::chrono::time_point< Clock > event_time)
void Neuron::SetUsage(std::chrono::time_point< Clock > event_time, int val)
double Neuron::GetEnergy(std::chrono::time_point< Clock > event_time)
double Neuron::GetGateKeeper(std::chrono::time_point< Clock > event_time)
double Neuron::GetChannelMin(std::chrono::time_point< Clock > event_time)
double Neuron::GetChannelMax(std::chrono::time_point< Clock > event_time)
bool Neuron::GetDisabled(std::chrono::time_point< Clock > event_time)
int Neuron::GetNeuronType(std::chrono::time_point< Clock > event_time)
double Neuron::GetRestingPotential(std::chrono::time_point< Clock > event_time)
int Neuron::GetNeuronDeviceTag(std::chrono::time_point< Clock > event_time)
int Neuron::GetSomaPool(std::chrono::time_point< Clock > event_time)
int Neuron::SetSomaPool(std::chrono::time_point< Clock > event_time, int set_pool)
void Neuron::SetCounter(std::chrono::time_point< Clock > event_time, int val)
void Neuron::SetEnergy(std::chrono::time_point< Clock > event_time, double val)
void Neuron::SetGateKeeper(std::chrono::time_point< Clock > event_time, double val)
void Neuron::SetChannelMin(std::chrono::time_point< Clock > event_time, double val)
void Neuron::SetChannelMax(std::chrono::time_point< Clock > event_time, double val)
void Neuron::SetDisabled(std::chrono::time_point< Clock > event_time, bool val)
void Neuron::toggleDisabled(std::chrono::time_point< Clock > event_time)
void Neuron::SetNeuronType(std::chrono::time_point< Clock > event_time, int val)
References ResetParameters.
void Neuron::SetNeuronDeviceTag(std::chrono::time_point< Clock > event_time, int val)
References SetObjectType, ResetParameters, OpenGate, CreateSoma, CreateSomas, CloneSoma, CloneSomas, DestroySoma, DestroySomas, AddSoma, AddSomas, RemoveSoma, RemoveSomas, GetSoma, GetSomas, CreateMembrane, CreateMembranes, CloneMembrane, CloneMembranes, DestroyMembrane, DestroyMembranes, AddMembrane, AddMembranes, RemoveMembrane, RemoveMembranes, GetMembrane, GetMembranes, Growth, UpdateCycle, UpdateCycle2, Update.
void Neuron::SetObjectType(std::chrono::time_point< Clock > event_time, int object_type)
References ResetParameters.
Referenced by SetNeuronDeviceTag.
bool Neuron::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::time_dimension_pointer, Universe::AddDimension, Universe::SetObjectType, Universe::TheTimeNow.
Referenced by SetObjectType, Update, Neuron, SetNeuronType, SetNeuronDeviceTag.
bool Neuron::OpenGate(std::chrono::time_point< Clock > event_time, double val)
Referenced by SetNeuronDeviceTag.
Neuron * Neuron::CreateSoma(std::chrono::time_point< Clock > event_time)
References soma_list.
Referenced by CreateSomas, SetNeuronDeviceTag.
std::vector< Neuron * > Neuron::CreateSomas(std::chrono::time_point< Clock > event_time, int quantity)
References soma_list, CreateSoma.
Referenced by Update, SetNeuronDeviceTag.
Neuron * Neuron::CloneSoma(std::chrono::time_point< Clock > event_time, Neuron *clone_object, double perfection_membership)
Referenced by SetNeuronDeviceTag.
std::vector< Neuron * > Neuron::CloneSomas(std::chrono::time_point< Clock > event_time, std::vector< Neuron *> cloning_list, double perfection_membership)
Referenced by SetNeuronDeviceTag.
Neuron * Neuron::DestroySoma(std::chrono::time_point< Clock > event_time, Neuron *destroy_object)
Referenced by SetNeuronDeviceTag.
std::vector< Neuron * > Neuron::DestroySomas(std::chrono::time_point< Clock > event_time, std::vector< Neuron *> destruction_list)
Referenced by SetNeuronDeviceTag.
Neuron * Neuron::AddSoma(std::chrono::time_point< Clock > event_time, Neuron *add_object)
References soma_list.
Referenced by AddSomas, SetNeuronDeviceTag.
std::vector< Neuron * > Neuron::AddSomas(std::chrono::time_point< Clock > event_time, std::vector< Neuron *> add_objects)
References soma_list, AddSoma.
Referenced by SetNeuronDeviceTag.
Neuron * Neuron::RemoveSoma(std::chrono::time_point< Clock > event_time)
Referenced by SetNeuronDeviceTag.
std::vector< Neuron * > Neuron::RemoveSomas(std::chrono::time_point< Clock > event_time, int quantity)
Referenced by SetNeuronDeviceTag.
Neuron * Neuron::GetSoma(std::chrono::time_point< Clock > event_time, int selector)
References soma_list.
Referenced by SetNeuronDeviceTag.
std::vector< Neuron * > Neuron::GetSomas(std::chrono::time_point< Clock > event_time)
References soma_list.
Referenced by SetNeuronDeviceTag.
Neuron * Neuron::CreateMembrane(std::chrono::time_point< Clock > event_time)
References membrane_list.
Referenced by CreateMembranes, SetNeuronDeviceTag.
std::vector< Neuron * > Neuron::CreateMembranes(std::chrono::time_point< Clock > event_time, int quantity)
References membrane_list, CreateMembrane.
Referenced by Update, SetNeuronDeviceTag.
Neuron * Neuron::CloneMembrane(std::chrono::time_point< Clock > event_time, Neuron *clone_object, double perfection_membership)
Referenced by SetNeuronDeviceTag.
std::vector< Neuron * > Neuron::CloneMembranes(std::chrono::time_point< Clock > event_time, std::vector< Neuron *> cloning_list, double perfection_membership)
Referenced by SetNeuronDeviceTag.
Neuron * Neuron::DestroyMembrane(std::chrono::time_point< Clock > event_time, Neuron *destroy_object)
Referenced by SetNeuronDeviceTag.
std::vector< Neuron * > Neuron::DestroyMembranes(std::chrono::time_point< Clock > event_time, std::vector< Neuron *> destruction_list)
Referenced by SetNeuronDeviceTag.
Neuron * Neuron::AddMembrane(std::chrono::time_point< Clock > event_time, Neuron *add_object)
References membrane_list.
Referenced by AddMembranes, SetNeuronDeviceTag.
std::vector< Neuron * > Neuron::AddMembranes(std::chrono::time_point< Clock > event_time, std::vector< Neuron *> add_objects)
References membrane_list, AddMembrane.
Referenced by SetNeuronDeviceTag.
Neuron * Neuron::RemoveMembrane(std::chrono::time_point< Clock > event_time)
Referenced by SetNeuronDeviceTag.
std::vector< Neuron * > Neuron::RemoveMembranes(std::chrono::time_point< Clock > event_time, int quantity)
Referenced by SetNeuronDeviceTag.
Neuron * Neuron::GetMembrane(std::chrono::time_point< Clock > event_time, int selector)
References membrane_list.
Referenced by SetNeuronDeviceTag.
std::vector< Neuron * > Neuron::GetMembranes(std::chrono::time_point< Clock > event_time)
References membrane_list.
Referenced by SetNeuronDeviceTag.
int Neuron::Growth(std::chrono::time_point< Clock > event_time)
Referenced by Update, SetNeuronDeviceTag.
void Neuron::UpdateCycle(std::chrono::time_point< Clock > event_time, std::vector< Neuron *> set_of_update_pointers, unsigned int pointer_type)
References Soma::Update, Membrane::Update.
Referenced by Update, SetNeuronDeviceTag.
void Neuron::UpdateCycle2(std::chrono::time_point< Clock > event_time, std::vector< Universe *> set_of_update_pointers, unsigned int pointer_type)
References Universe::Update.
Referenced by Update, SetNeuronDeviceTag.
int Neuron::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters, Universe::AddSolid, Solid::SetObjectType, TYPE_SOLID_NEURON_GEN1, visualisation_list, CreateSomas, Soma::SetObjectType, TYPE_NEURON_PYRAMIDAL_SOMA_GEN1, soma_list, CreateMembranes, Membrane::SetObjectType, TYPE_NEURON_PYRAMIDAL_MEMBRANE_GEN1, membrane_list, UpdateCycle, UpdateCycle2, Growth.
Referenced by SetNeuronDeviceTag.
std::vector<Universe*> Neuron::GetVisualisationList()
References visualisation_list.
Referenced by Soma::Update.