CognitiveNetwork
std::vector<Dimension*> CognitiveNetwork::dimension_list
std::vector<CognitiveNetwork*> CognitiveNetwork::cognitiveinput_list
Referenced by Update, CreateCognitiveInput, CreateCognitiveInputs, AddCognitiveInput, AddCognitiveInputs, GetCognitiveInput, GetCognitiveInputs.
std::vector<CognitiveNetwork*> CognitiveNetwork::cognitiveoutput_list
Referenced by Update, CreateCognitiveOutput, CreateCognitiveOutputs, AddCognitiveOutput, AddCognitiveOutputs, GetCognitiveOutput, GetCognitiveOutputs.
std::vector<CognitiveNetwork*> CognitiveNetwork::interneuronspace_list
Referenced by Update, AddCognitiveInput, AddCognitiveOutput, CreateInterneuronSpace, CreateInterneuronSpaces, AddInterneuronSpace, AddInterneuronSpaces, GetInterneuronSpace, GetInterneuronSpaces.
std::vector<CognitiveNetwork*> CognitiveNetwork::orbital_list
Referenced by Update, CreateOrbital, CreateOrbitals, AddOrbital, AddOrbitals, GetOrbital, GetOrbitals.
std::vector<CognitiveNetwork*> CognitiveNetwork::neuron_list
Referenced by Update, CreateNeuron, CreateNeurons, AddNeuron, AddNeurons, GetNeuron, GetNeurons.
std::vector<CognitiveNetwork*> CognitiveNetwork::synapse_list
Referenced by Update, CreateSynapse, CreateSynapses, AddSynapse, AddSynapses, GetSynapse, GetSynapses.
std::vector<CognitiveNetwork*> CognitiveNetwork::neurotransmitter_list
Referenced by Update, CreateNeurotransmitter, CreateNeurotransmitters, AddNeurotransmitter, AddNeurotransmitters, GetNeurotransmitter, GetNeurotransmitters.
int CognitiveNetwork::cognitivenetwork_type
int CognitiveNetwork::m_Tag
double CognitiveNetwork::object_size
double CognitiveNetwork::m_RestingPotential
bool CognitiveNetwork::object_disabled
bool CognitiveNetwork::object_initialised
std::chrono::time_point<Clock> CognitiveNetwork::time_object_created
std::chrono::time_point<Clock> CognitiveNetwork::previous_event_time
int CognitiveNetwork::duration_since_last_event
int CognitiveNetwork::m_addStatus
int CognitiveNetwork::m_Counter
Member variable "m_Counter".
double CognitiveNetwork::object_energy
Member variable "object_energy".
double CognitiveNetwork::object_energy_threshold
double CognitiveNetwork::m_Spike
Member variable "m_Spike".
double CognitiveNetwork::m_GateKeeper
Member variable "m_GateKeeper".
double CognitiveNetwork::m_ChannelMin
Member variable "m_ChannelMin".
double CognitiveNetwork::m_ChannelMax
Member variable "m_ChannelMax".
double CognitiveNetwork::m_TimeDilation
double CognitiveNetwork::m_TimeThreshold
unsigned int CognitiveNetwork::cognitivenetworkCounter
Member variable "elementaryParticleCounter".
int CognitiveNetwork::cognitivenetworkCapacity
int CognitiveNetwork::cognitivenetworkUsage
int CognitiveNetwork::interneuronspace_pool
int CognitiveNetwork::cognitiveinput_pool
int CognitiveNetwork::cognitiveoutput_pool
int CognitiveNetwork::orbital_pool
int CognitiveNetwork::neuron_pool
int CognitiveNetwork::synapse_pool
int CognitiveNetwork::neurotransmitter_pool
std::vector<OrbitalConnection> CognitiveNetwork::orbital_connection_list
CognitiveNetwork::CognitiveNetwork()
CognitiveNetwork::CognitiveNetwork(unsigned int object_type)
CognitiveNetwork::CognitiveNetwork(unsigned int object_type, std::chrono::time_point< Clock > event_time)
CognitiveNetwork::CognitiveNetwork(unsigned int object_type, std::chrono::time_point< Clock > event_time, Universe &universe_connector)
References ResetParameters, Universe::Creation.
virtual CognitiveNetwork::~CognitiveNetwork()
Default destructor
unsigned int CognitiveNetwork::GetCounter(std::chrono::time_point< Clock > event_time)
int CognitiveNetwork::GetCapacity(std::chrono::time_point< Clock > event_time)
void CognitiveNetwork::SetCapacity(std::chrono::time_point< Clock > event_time, int val)
int CognitiveNetwork::GetUsage(std::chrono::time_point< Clock > event_time)
void CognitiveNetwork::SetUsage(std::chrono::time_point< Clock > event_time, int val)
double CognitiveNetwork::GetEnergy(std::chrono::time_point< Clock > event_time)
double CognitiveNetwork::GetGateKeeper(std::chrono::time_point< Clock > event_time)
double CognitiveNetwork::GetChannelMin(std::chrono::time_point< Clock > event_time)
double CognitiveNetwork::GetChannelMax(std::chrono::time_point< Clock > event_time)
bool CognitiveNetwork::GetDisabled(std::chrono::time_point< Clock > event_time)
int CognitiveNetwork::GetObjectType(std::chrono::time_point< Clock > event_time)
double CognitiveNetwork::GetRestingPotential(std::chrono::time_point< Clock > event_time)
int CognitiveNetwork::GetCognitiveNetworkDeviceTag(std::chrono::time_point< Clock > event_time)
void CognitiveNetwork::SetCounter(std::chrono::time_point< Clock > event_time, int val)
void CognitiveNetwork::SetEnergy(std::chrono::time_point< Clock > event_time, double val)
void CognitiveNetwork::SetGateKeeper(std::chrono::time_point< Clock > event_time, double val)
void CognitiveNetwork::SetChannelMin(std::chrono::time_point< Clock > event_time, double val)
void CognitiveNetwork::SetChannelMax(std::chrono::time_point< Clock > event_time, double val)
void CognitiveNetwork::SetDisabled(std::chrono::time_point< Clock > event_time, bool val)
void CognitiveNetwork::toggleDisabled(std::chrono::time_point< Clock > event_time)
int CognitiveNetwork::GetOrbitalPool(std::chrono::time_point< Clock > event_time)
int CognitiveNetwork::GetNeuronPool(std::chrono::time_point< Clock > event_time)
int CognitiveNetwork::GetSynapsePool(std::chrono::time_point< Clock > event_time)
int CognitiveNetwork::GetNeurotransmitterPool(std::chrono::time_point< Clock > event_time)
int CognitiveNetwork::SetOrbitalPool(std::chrono::time_point< Clock > event_time, int set_pool)
int CognitiveNetwork::SetNeuronPool(std::chrono::time_point< Clock > event_time, int set_pool)
int CognitiveNetwork::SetSynapsePool(std::chrono::time_point< Clock > event_time, int set_pool)
int CognitiveNetwork::SetNeurotransmitterPool(std::chrono::time_point< Clock > event_time, int set_pool)
References SetObjectType.
void CognitiveNetwork::SetObjectType(std::chrono::time_point< Clock > event_time, int object_type)
References ResetParameters.
Referenced by SetNeurotransmitterPool.
void CognitiveNetwork::SetCognitiveNetworkDeviceTag(std::chrono::time_point< Clock > event_time, int val)
References ResetParameters, UpdateCycle, Update, CreateCognitiveInput, CreateCognitiveInputs, CloneCognitiveInput, CloneCognitiveInputs, DestroyCognitiveInput, DestroyCognitiveInputs, AddCognitiveInput, AddCognitiveInputs, RemoveCognitiveInput, RemoveCognitiveInputs, GetCognitiveInput, GetCognitiveInputs, CreateCognitiveOutput, CreateCognitiveOutputs, CloneCognitiveOutput, CloneCognitiveOutputs, DestroyCognitiveOutput, DestroyCognitiveOutputs, AddCognitiveOutput, AddCognitiveOutputs, RemoveCognitiveOutput, RemoveCognitiveOutputs, GetCognitiveOutput, GetCognitiveOutputs, CreateInterneuronSpace, CreateInterneuronSpaces, CloneInterneuronSpace, CloneInterneuronSpaces, DestroyInterneuronSpace, DestroyInterneuronSpaces, AddInterneuronSpace, AddInterneuronSpaces, RemoveInterneuronSpace, RemoveInterneuronSpaces, GetInterneuronSpace, GetInterneuronSpaces, CreateOrbital, CreateOrbitals, CloneOrbital, CloneOrbitals, DestroyOrbital, DestroyOrbitals, AddOrbital, AddOrbitals, RemoveOrbital, RemoveOrbitals, GetOrbital, GetOrbitals, CreateNeuron, CreateNeurons, CloneNeuron, CloneNeurons, DestroyNeuron, DestroyNeurons, AddNeuron, AddNeurons, RemoveNeuron, RemoveNeurons, GetNeuron, GetNeurons, CreateSynapse, CreateSynapses, CloneSynapse, CloneSynapses, DestroySynapse, DestroySynapses, AddSynapse, AddSynapses, RemoveSynapse, RemoveSynapses, GetSynapse, GetSynapses, CreateNeurotransmitter, CreateNeurotransmitters, CloneNeurotransmitter, CloneNeurotransmitters, DestroyNeurotransmitter, DestroyNeurotransmitters, AddNeurotransmitter, AddNeurotransmitters, RemoveNeurotransmitter, RemoveNeurotransmitters, GetNeurotransmitter, GetNeurotransmitters.
bool CognitiveNetwork::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::time_dimension_pointer, Universe::AddDimension, Universe::SetObjectType, Universe::TheTimeNow.
Referenced by SetObjectType, Update, CognitiveNetwork, SetCognitiveNetworkDeviceTag.
void CognitiveNetwork::UpdateCycle(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> set_of_update_pointers, unsigned int pointer_type)
References Update.
Referenced by Update, SetCognitiveNetworkDeviceTag.
int CognitiveNetwork::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters, UpdateCycle, cognitiveinput_list, cognitiveoutput_list, interneuronspace_list, orbital_list, neuron_list, synapse_list, neurotransmitter_list.
Referenced by UpdateCycle, SetCognitiveNetworkDeviceTag, Orbital::UpdateCycle.
CognitiveNetwork * CognitiveNetwork::CreateCognitiveInput(std::chrono::time_point< Clock > event_time)
References cognitiveinput_list.
Referenced by CreateCognitiveInputs, SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::CreateCognitiveInputs(std::chrono::time_point< Clock > event_time, int quantity)
References cognitiveinput_list, CreateCognitiveInput.
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::CloneCognitiveInput(std::chrono::time_point< Clock > event_time, CognitiveNetwork *clone_object, double perfection_membership)
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::CloneCognitiveInputs(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> cloning_list, double perfection_membership)
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::DestroyCognitiveInput(std::chrono::time_point< Clock > event_time, CognitiveNetwork *destroy_object)
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::DestroyCognitiveInputs(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> destruction_list)
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::AddCognitiveInput(std::chrono::time_point< Clock > event_time, CognitiveNetwork *add_object)
References cognitiveinput_list, interneuronspace_list.
Referenced by AddCognitiveInputs, SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::AddCognitiveInputs(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> add_objects)
References cognitiveinput_list, AddCognitiveInput.
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::RemoveCognitiveInput(std::chrono::time_point< Clock > event_time)
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::RemoveCognitiveInputs(std::chrono::time_point< Clock > event_time, int quantity)
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::GetCognitiveInput(std::chrono::time_point< Clock > event_time, int selector)
References cognitiveinput_list.
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::GetCognitiveInputs(std::chrono::time_point< Clock > event_time)
References cognitiveinput_list.
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::CreateCognitiveOutput(std::chrono::time_point< Clock > event_time)
References cognitiveoutput_list.
Referenced by CreateCognitiveOutputs, SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::CreateCognitiveOutputs(std::chrono::time_point< Clock > event_time, int quantity)
References cognitiveoutput_list, CreateCognitiveOutput.
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::CloneCognitiveOutput(std::chrono::time_point< Clock > event_time, CognitiveNetwork *clone_object, double perfection_membership)
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::CloneCognitiveOutputs(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> cloning_list, double perfection_membership)
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::DestroyCognitiveOutput(std::chrono::time_point< Clock > event_time, CognitiveNetwork *destroy_object)
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::DestroyCognitiveOutputs(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> destruction_list)
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::AddCognitiveOutput(std::chrono::time_point< Clock > event_time, CognitiveNetwork *add_object)
References cognitiveoutput_list, interneuronspace_list.
Referenced by AddCognitiveOutputs, SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::AddCognitiveOutputs(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> add_objects)
References cognitiveoutput_list, AddCognitiveOutput.
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::RemoveCognitiveOutput(std::chrono::time_point< Clock > event_time)
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::RemoveCognitiveOutputs(std::chrono::time_point< Clock > event_time, int quantity)
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::GetCognitiveOutput(std::chrono::time_point< Clock > event_time, int selector)
References cognitiveoutput_list.
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::GetCognitiveOutputs(std::chrono::time_point< Clock > event_time)
References cognitiveoutput_list.
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::CreateInterneuronSpace(std::chrono::time_point< Clock > event_time)
References interneuronspace_list.
Referenced by CreateInterneuronSpaces, SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::CreateInterneuronSpaces(std::chrono::time_point< Clock > event_time, int quantity)
References interneuronspace_list, CreateInterneuronSpace.
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::CloneInterneuronSpace(std::chrono::time_point< Clock > event_time, CognitiveNetwork *clone_object, double perfection_membership)
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::CloneInterneuronSpaces(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> cloning_list, double perfection_membership)
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::DestroyInterneuronSpace(std::chrono::time_point< Clock > event_time, CognitiveNetwork *destroy_object)
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::DestroyInterneuronSpaces(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> destruction_list)
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::AddInterneuronSpace(std::chrono::time_point< Clock > event_time, CognitiveNetwork *add_object)
References interneuronspace_list.
Referenced by AddInterneuronSpaces, SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::AddInterneuronSpaces(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> add_objects)
References interneuronspace_list, AddInterneuronSpace.
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::RemoveInterneuronSpace(std::chrono::time_point< Clock > event_time)
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::RemoveInterneuronSpaces(std::chrono::time_point< Clock > event_time, int quantity)
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::GetInterneuronSpace(std::chrono::time_point< Clock > event_time, int selector)
References interneuronspace_list.
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::GetInterneuronSpaces(std::chrono::time_point< Clock > event_time)
References interneuronspace_list.
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::CreateOrbital(std::chrono::time_point< Clock > event_time)
References orbital_list.
Referenced by CreateOrbitals, SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::CreateOrbitals(std::chrono::time_point< Clock > event_time, int quantity)
References orbital_list, CreateOrbital.
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::CloneOrbital(std::chrono::time_point< Clock > event_time, CognitiveNetwork *clone_object, double perfection_membership)
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::CloneOrbitals(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> cloning_list, double perfection_membership)
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::DestroyOrbital(std::chrono::time_point< Clock > event_time, CognitiveNetwork *destroy_object)
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::DestroyOrbitals(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> destruction_list)
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::AddOrbital(std::chrono::time_point< Clock > event_time, CognitiveNetwork *add_object)
References orbital_list.
Referenced by AddOrbitals, SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::AddOrbitals(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> add_objects)
References orbital_list, AddOrbital.
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::RemoveOrbital(std::chrono::time_point< Clock > event_time)
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::RemoveOrbitals(std::chrono::time_point< Clock > event_time, int quantity)
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::GetOrbital(std::chrono::time_point< Clock > event_time, int selector)
References orbital_list.
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::GetOrbitals(std::chrono::time_point< Clock > event_time)
References orbital_list.
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::CreateNeuron(std::chrono::time_point< Clock > event_time)
References neuron_list.
Referenced by CreateNeurons, SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::CreateNeurons(std::chrono::time_point< Clock > event_time, int quantity)
References neuron_list, CreateNeuron.
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::CloneNeuron(std::chrono::time_point< Clock > event_time, CognitiveNetwork *clone_object, double perfection_membership)
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::CloneNeurons(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> cloning_list, double perfection_membership)
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::DestroyNeuron(std::chrono::time_point< Clock > event_time, CognitiveNetwork *destroy_object)
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::DestroyNeurons(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> destruction_list)
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::AddNeuron(std::chrono::time_point< Clock > event_time, CognitiveNetwork *add_object)
References neuron_list.
Referenced by AddNeurons, SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::AddNeurons(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> add_objects)
References neuron_list, AddNeuron.
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::RemoveNeuron(std::chrono::time_point< Clock > event_time)
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::RemoveNeurons(std::chrono::time_point< Clock > event_time, int quantity)
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::GetNeuron(std::chrono::time_point< Clock > event_time, int selector)
References neuron_list.
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::GetNeurons(std::chrono::time_point< Clock > event_time)
References neuron_list.
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::CreateSynapse(std::chrono::time_point< Clock > event_time)
References synapse_list.
Referenced by CreateSynapses, SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::CreateSynapses(std::chrono::time_point< Clock > event_time, int quantity)
References synapse_list, CreateSynapse.
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::CloneSynapse(std::chrono::time_point< Clock > event_time, CognitiveNetwork *clone_object, double perfection_membership)
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::CloneSynapses(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> cloning_list, double perfection_membership)
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::DestroySynapse(std::chrono::time_point< Clock > event_time, CognitiveNetwork *destroy_object)
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::DestroySynapses(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> destruction_list)
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::AddSynapse(std::chrono::time_point< Clock > event_time, CognitiveNetwork *add_object)
References synapse_list.
Referenced by AddSynapses, SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::AddSynapses(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> add_objects)
References synapse_list, AddSynapse.
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::RemoveSynapse(std::chrono::time_point< Clock > event_time)
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::RemoveSynapses(std::chrono::time_point< Clock > event_time, int quantity)
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::GetSynapse(std::chrono::time_point< Clock > event_time, int selector)
References synapse_list.
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::GetSynapses(std::chrono::time_point< Clock > event_time)
References synapse_list.
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::CreateNeurotransmitter(std::chrono::time_point< Clock > event_time)
References neurotransmitter_list.
Referenced by CreateNeurotransmitters, SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::CreateNeurotransmitters(std::chrono::time_point< Clock > event_time, int quantity)
References neurotransmitter_list, CreateNeurotransmitter.
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::CloneNeurotransmitter(std::chrono::time_point< Clock > event_time, CognitiveNetwork *clone_object, double perfection_membership)
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::CloneNeurotransmitters(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> cloning_list, double perfection_membership)
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::DestroyNeurotransmitter(std::chrono::time_point< Clock > event_time, CognitiveNetwork *destroy_object)
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::DestroyNeurotransmitters(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> destruction_list)
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::AddNeurotransmitter(std::chrono::time_point< Clock > event_time, CognitiveNetwork *add_object)
References neurotransmitter_list.
Referenced by AddNeurotransmitters, SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::AddNeurotransmitters(std::chrono::time_point< Clock > event_time, std::vector< CognitiveNetwork *> add_objects)
References neurotransmitter_list, AddNeurotransmitter.
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::RemoveNeurotransmitter(std::chrono::time_point< Clock > event_time)
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::RemoveNeurotransmitters(std::chrono::time_point< Clock > event_time, int quantity)
Referenced by SetCognitiveNetworkDeviceTag.
CognitiveNetwork * CognitiveNetwork::GetNeurotransmitter(std::chrono::time_point< Clock > event_time, int selector)
References neurotransmitter_list.
Referenced by SetCognitiveNetworkDeviceTag.
std::vector< CognitiveNetwork * > CognitiveNetwork::GetNeurotransmitters(std::chrono::time_point< Clock > event_time)
References neurotransmitter_list.
Referenced by SetCognitiveNetworkDeviceTag.
void CognitiveNetwork::SetCharge(std::chrono::time_point< Clock > event_time, int val) final
void CognitiveNetwork::SetSpin(std::chrono::time_point< Clock > event_time, int val) final
double CognitiveNetwork::GetGravitation(std::chrono::time_point< Clock > event_time) final
double CognitiveNetwork::GetWeak(std::chrono::time_point< Clock > event_time) final
double CognitiveNetwork::GetWeakElectroweak(std::chrono::time_point< Clock > event_time) final
double CognitiveNetwork::GetElectromagnetic(std::chrono::time_point< Clock > event_time) final
double CognitiveNetwork::GetElectromagneticElectroweak(std::chrono::time_point< Clock > event_time) final
double CognitiveNetwork::GetStrong(std::chrono::time_point< Clock > event_time) final
double CognitiveNetwork::GetStrongFundamental(std::chrono::time_point< Clock > event_time) final
double CognitiveNetwork::GetStrongResidual(std::chrono::time_point< Clock > event_time) final
double CognitiveNetwork::ApplyGravitation(std::chrono::time_point< Clock > event_time, double val) final
double CognitiveNetwork::ApplyWeak(std::chrono::time_point< Clock > event_time, double val) final
double CognitiveNetwork::ApplyWeakElectroweak(std::chrono::time_point< Clock > event_time, double val) final
double CognitiveNetwork::ApplyElectromagnetic(std::chrono::time_point< Clock > event_time, double val) final
double CognitiveNetwork::ApplyElectromagneticElectroweak(std::chrono::time_point< Clock > event_time, double val) final
double CognitiveNetwork::ApplyStrong(std::chrono::time_point< Clock > event_time, double val) final
double CognitiveNetwork::ApplyStrongFundamental(std::chrono::time_point< Clock > event_time, double val) final
double CognitiveNetwork::ApplyStrongResidual(std::chrono::time_point< Clock > event_time, double val) final
void CognitiveNetwork::SetGravitation(std::chrono::time_point< Clock > event_time, double val) final
void CognitiveNetwork::SetWeak(std::chrono::time_point< Clock > event_time, double val) final
void CognitiveNetwork::SetWeakElectroweak(std::chrono::time_point< Clock > event_time, double val) final
void CognitiveNetwork::SetElectromagnetic(std::chrono::time_point< Clock > event_time, double val) final
void CognitiveNetwork::SetElectromagneticElectroweak(std::chrono::time_point< Clock > event_time, double val) final
void CognitiveNetwork::SetStrong(std::chrono::time_point< Clock > event_time, double val) final
void CognitiveNetwork::SetStrongFundamental(std::chrono::time_point< Clock > event_time, double val) final
void CognitiveNetwork::SetStrongResidual(std::chrono::time_point< Clock > event_time, double val) final
void CognitiveNetwork::PollElementaryForce(std::chrono::time_point< Clock > event_time) final