Membrane
std::vector<Membrane*> Membrane::membranechannel_list
Referenced by CreateMembraneChannel, CreateMembraneChannels, AddMembraneChannel, AddMembraneChannels, GetMembraneChannel, GetMembraneChannels, Update.
std::vector<Solid*> Membrane::visualisation_list
Referenced by Update.
int Membrane::m_NeuronType
int Membrane::membrane_type
int Membrane::m_addStatus
std::chrono::time_point<Clock> Membrane::time_object_created
std::chrono::time_point<Clock> Membrane::previous_event_time
bool Membrane::object_disabled
bool Membrane::object_initialised
int Membrane::duration_since_last_event
double Membrane::m_Volume
double Membrane::m_SurfaceArea
double Membrane::object_size
unsigned int Membrane::m_Counter
Member variable "m_Counter".
double Membrane::object_energy
Member variable "object_energy".
double Membrane::object_energyInc
double Membrane::object_energyDec
double Membrane::object_energyLeak
double Membrane::object_energy_threshold
double Membrane::m_TimeDilation
double Membrane::m_TimeThreshold
int Membrane::membranechannel_pool
Membrane::Membrane()
Membrane::Membrane(unsigned int object_type)
Membrane::Membrane(unsigned int object_type, std::chrono::time_point< Clock > event_time)
Membrane::Membrane(unsigned int object_type, std::chrono::time_point< Clock > event_time, Neuron &neuron_connector)
References ResetParameters, Universe::Creation.
virtual Membrane::~Membrane()
Default destructor
double Membrane::TimeFunction(double timeDelay, double timeDilation)
unsigned int Membrane::GetCounter(std::chrono::time_point< Clock > event_time)
double Membrane::GetEnergy(std::chrono::time_point< Clock > event_time)
double Membrane::GetEnergyInc(std::chrono::time_point< Clock > event_time)
double Membrane::GetEnergyDec(std::chrono::time_point< Clock > event_time)
double Membrane::GetEnergyLeak(std::chrono::time_point< Clock > event_time)
double Membrane::GetEnergyThreshold(std::chrono::time_point< Clock > event_time)
int Membrane::GetMembraneChannelPool(std::chrono::time_point< Clock > event_time)
int Membrane::SetMembraneChannelPool(std::chrono::time_point< Clock > event_time, int set_pool)
void Membrane::SetCounter(std::chrono::time_point< Clock > event_time, unsigned int val)
void Membrane::SetEnergy(std::chrono::time_point< Clock > event_time, double val)
void Membrane::SetEnergyInc(std::chrono::time_point< Clock > event_time, double val)
void Membrane::SetEnergyDec(std::chrono::time_point< Clock > event_time, double val)
void Membrane::SetEnergyLeak(std::chrono::time_point< Clock > event_time, double val)
void Membrane::SetEnergyThreshold(std::chrono::time_point< Clock > event_time, double val)
References SetObjectType, ResetParameters, CreateMembraneChannel, CreateMembraneChannels, CloneMembraneChannel, CloneMembraneChannels, DestroyMembraneChannel, DestroyMembraneChannels, AddMembraneChannel, AddMembraneChannels, RemoveMembraneChannel, RemoveMembraneChannels, GetMembraneChannel, GetMembraneChannels, Growth, Update.
void Membrane::SetObjectType(std::chrono::time_point< Clock > event_time, int object_type)
References ResetParameters.
Referenced by SetEnergyThreshold, Neuron::Update.
bool Membrane::ResetParameters(std::chrono::time_point< Clock > event_time)
References Universe::time_dimension_pointer, Universe::AddDimension, Universe::SetObjectType, Universe::TheTimeNow, Universe::object_energy, Universe::object_energy_threshold, Universe::object_size.
Referenced by SetObjectType, Update, Membrane, SetEnergyThreshold.
Membrane * Membrane::CreateMembraneChannel(std::chrono::time_point< Clock > event_time)
References membranechannel_list.
Referenced by CreateMembraneChannels, SetEnergyThreshold.
std::vector< Membrane * > Membrane::CreateMembraneChannels(std::chrono::time_point< Clock > event_time, int quantity)
References membranechannel_list, CreateMembraneChannel.
Referenced by SetEnergyThreshold.
Membrane * Membrane::CloneMembraneChannel(std::chrono::time_point< Clock > event_time, Membrane *clone_object, double perfection_membership)
Referenced by SetEnergyThreshold.
std::vector< Membrane * > Membrane::CloneMembraneChannels(std::chrono::time_point< Clock > event_time, std::vector< Membrane *> cloning_list, double perfection_membership)
Referenced by SetEnergyThreshold.
Membrane * Membrane::DestroyMembraneChannel(std::chrono::time_point< Clock > event_time, Membrane *destroy_object)
Referenced by SetEnergyThreshold.
std::vector< Membrane * > Membrane::DestroyMembraneChannels(std::chrono::time_point< Clock > event_time, std::vector< Membrane *> destruction_list)
Referenced by SetEnergyThreshold.
Membrane * Membrane::AddMembraneChannel(std::chrono::time_point< Clock > event_time, Membrane *add_object)
References membranechannel_list.
Referenced by AddMembraneChannels, SetEnergyThreshold.
std::vector< Membrane * > Membrane::AddMembraneChannels(std::chrono::time_point< Clock > event_time, std::vector< Membrane *> add_objects)
References membranechannel_list, AddMembraneChannel.
Referenced by SetEnergyThreshold.
Membrane * Membrane::RemoveMembraneChannel(std::chrono::time_point< Clock > event_time)
Referenced by SetEnergyThreshold.
std::vector< Membrane * > Membrane::RemoveMembraneChannels(std::chrono::time_point< Clock > event_time, int quantity)
Referenced by SetEnergyThreshold.
Membrane * Membrane::GetMembraneChannel(std::chrono::time_point< Clock > event_time, int selector)
References membranechannel_list.
Referenced by SetEnergyThreshold.
std::vector< Membrane * > Membrane::GetMembraneChannels(std::chrono::time_point< Clock > event_time)
References membranechannel_list.
Referenced by SetEnergyThreshold.
int Membrane::Growth(std::chrono::time_point< Clock > event_time)
References Universe::object_energy, Universe::object_energy_threshold, Universe::object_size.
Referenced by Update, SetEnergyThreshold.
int Membrane::Update(std::chrono::time_point< Clock > event_time)
References ResetParameters, visualisation_list, Solid::CreatePolyhedron, Solid::SetObjectType, TYPE_SOLID_POLYHEDRON_MEMBRANE_GEN1, Universe::object_energy, membranechannel_list, Growth, Universe::object_energy_threshold, Universe::object_size.
Referenced by SetEnergyThreshold, Neuron::UpdateCycle.