implementation orig.cpp
Graph<char> example_graph
std::basic_iostream<char>::basic_ostream& operator<<(std::basic_iostream< char >::basic_ostream &out, tuple< int, int > loc)
void draw_grid(const Graph &graph, int field_width, unordered_map< typename Graph::Location, int > *distances=nullptr, unordered_map< typename Graph::Location, typename Graph::Location > *point_to=nullptr, vector< typename Graph::Location > *path=nullptr)
void add_rect(SquareGrid &grid, int x1, int y1, int x2, int y2)
References SquareGrid::walls.
Referenced by make_diagram1, make_diagram4.
SquareGrid make_diagram1()
References add_rect.
GridWithWeights make_diagram4()
References add_rect, GridWithWeights::forests.
void dijkstra_search(Graph graph, typename Graph::Location start, typename Graph::Location goal, unordered_map< typename Graph::Location, typename Graph::Location > &came_from, unordered_map< typename Graph::Location, int > &cost_so_far)
References PriorityQueue< T, Number >::put, PriorityQueue< T, Number >::empty, PriorityQueue< T, Number >::get, Graph< L >::neighbors.
Referenced by PriorityQueue< T, Number >::get.
vector<Location> reconstruct_path(Location start, Location goal, unordered_map< Location, Location > &came_from)
int heuristic(SquareGrid::Location a, SquareGrid::Location b)
References a_star_search.
Referenced by a_star_search.
void a_star_search(Graph graph, typename Graph::Location start, typename Graph::Location goal, unordered_map< typename Graph::Location, typename Graph::Location > &came_from, unordered_map< typename Graph::Location, int > &cost_so_far)
References PriorityQueue< T, Number >::put, PriorityQueue< T, Number >::empty, PriorityQueue< T, Number >::get, Graph< L >::neighbors, heuristic.
Referenced by heuristic.