linmath.h
LINMATH_H_FUNC
LINMATH_H_DEFINE_VEC
quat_norm
typedef vec4 mat4x4[4][4]
typedef float quat[4][4]
LINMATH_H_FUNC void vec3_mul_cross(vec3 r, vec3 const a, vec3 const b)
Referenced by mat4x4_look_at, quat_mul, quat_mul_vec3, mat4x4_arcball.
LINMATH_H_FUNC void vec3_reflect(vec3 r, vec3 const v, vec3 const n)
LINMATH_H_FUNC void vec4_mul_cross(vec4 r, vec4 a, vec4 b)
LINMATH_H_FUNC void vec4_reflect(vec4 r, vec4 v, vec4 n)
LINMATH_H_FUNC void mat4x4_identity(mat4x4 M)
Referenced by mat4x4_translate, mat4x4_rotate.
LINMATH_H_FUNC void mat4x4_dup(mat4x4 M, mat4x4 N)
Referenced by mat4x4_mul, mat4x4_rotate, mat4x4_orthonormalize.
LINMATH_H_FUNC void mat4x4_row(vec4 r, mat4x4 M, int i)
Referenced by mat4x4_translate_in_place.
LINMATH_H_FUNC void mat4x4_col(vec4 r, mat4x4 M, int i)
LINMATH_H_FUNC void mat4x4_transpose(mat4x4 M, mat4x4 N)
LINMATH_H_FUNC void mat4x4_add(mat4x4 M, mat4x4 a, mat4x4 b)
Referenced by mat4x4_rotate.
LINMATH_H_FUNC void mat4x4_sub(mat4x4 M, mat4x4 a, mat4x4 b)
Referenced by mat4x4_rotate.
LINMATH_H_FUNC void mat4x4_scale(mat4x4 M, mat4x4 a, float k)
Referenced by mat4x4_rotate.
LINMATH_H_FUNC void mat4x4_scale_aniso(mat4x4 M, mat4x4 a, float x, float y, float z)
LINMATH_H_FUNC void mat4x4_mul(mat4x4 M, mat4x4 a, mat4x4 b)
References mat4x4_dup.
Referenced by mat4x4_rotate, mat4x4_rotate_X, mat4x4_rotate_Y, mat4x4_rotate_Z.
LINMATH_H_FUNC void mat4x4_mul_vec4(vec4 r, mat4x4 M, vec4 v)
LINMATH_H_FUNC void mat4x4_translate(mat4x4 T, float x, float y, float z)
References mat4x4_identity.
LINMATH_H_FUNC void mat4x4_translate_in_place(mat4x4 M, float x, float y, float z)
References mat4x4_row.
Referenced by mat4x4_look_at.
LINMATH_H_FUNC void mat4x4_from_vec3_mul_outer(mat4x4 M, vec3 a, vec3 b)
Referenced by mat4x4_rotate.
LINMATH_H_FUNC void mat4x4_rotate(mat4x4 R, mat4x4 M, float x, float y, float z, float angle)
References mat4x4_from_vec3_mul_outer, mat4x4_scale, mat4x4_identity, mat4x4_sub, mat4x4_add, mat4x4_mul, mat4x4_dup.
Referenced by mat4x4_arcball.
LINMATH_H_FUNC void mat4x4_rotate_X(mat4x4 Q, mat4x4 M, float angle)
References mat4x4_mul.
LINMATH_H_FUNC void mat4x4_rotate_Y(mat4x4 Q, mat4x4 M, float angle)
References mat4x4_mul.
LINMATH_H_FUNC void mat4x4_rotate_Z(mat4x4 Q, mat4x4 M, float angle)
References mat4x4_mul.
LINMATH_H_FUNC void mat4x4_invert(mat4x4 T, mat4x4 M)
LINMATH_H_FUNC void mat4x4_orthonormalize(mat4x4 R, mat4x4 M)
References mat4x4_dup.
LINMATH_H_FUNC void mat4x4_frustum(mat4x4 M, float l, float r, float b, float t, float n, float f)
LINMATH_H_FUNC void mat4x4_ortho(mat4x4 M, float l, float r, float b, float t, float n, float f)
LINMATH_H_FUNC void mat4x4_perspective(mat4x4 m, float y_fov, float aspect, float n, float f)
Referenced by framebuffer_size_callback.
LINMATH_H_FUNC void mat4x4_look_at(mat4x4 m, vec3 eye, vec3 center, vec3 up)
References vec3_mul_cross, mat4x4_translate_in_place.
LINMATH_H_FUNC void quat_identity(quat q)
LINMATH_H_FUNC void quat_add(quat r, quat a, quat b)
LINMATH_H_FUNC void quat_sub(quat r, quat a, quat b)
LINMATH_H_FUNC void quat_mul(quat r, quat p, quat q)
References vec3_mul_cross.
LINMATH_H_FUNC void quat_scale(quat r, quat v, float s)
LINMATH_H_FUNC float quat_inner_product(quat a, quat b)
LINMATH_H_FUNC void quat_conj(quat r, quat q)
LINMATH_H_FUNC void quat_rotate(quat r, float angle, vec3 axis)
LINMATH_H_FUNC void quat_mul_vec3(vec3 r, quat q, vec3 v)
References vec3_mul_cross.
Referenced by mat4x4o_mul_quat.
LINMATH_H_FUNC void mat4x4_from_quat(mat4x4 M, quat q)
LINMATH_H_FUNC void mat4x4o_mul_quat(mat4x4 R, mat4x4 M, quat q)
References quat_mul_vec3.
LINMATH_H_FUNC void quat_from_mat4x4(quat q, mat4x4 M)
LINMATH_H_FUNC void mat4x4_arcball(mat4x4 R, mat4x4 M, vec2 _a, vec2 _b, float s)
References vec3_mul_cross, mat4x4_rotate.