main.cc
DEFAULTBIASES
< For array in CRC-32 call < For handling strings < For byte handling in CRC-32 < For reading files < Formatting output to console < For output to console < For open and closed maps in A* < For Sine, Cosine, Power, Fabs & Sqrt functions < For CRC-32 < For assigning priority queue in A* < For stringstream input from console < For handling strings < For thread handling < To use vectors, which automatically handle resizing, as arrays to keep track of instances
LOWPOWERBIASES
DEBUG_PROGRAM
< Graphics library http://sfml-dev.org < Python interpreter < Top of the tree, begin with Universe class < Add Dimensions for spatial identification < Follow with the creation of quarks/leptons < Basic interactions form protons/neutrons < Define Force interaction between fundamentals < Define Force interaction between Composites < Specify how Composites interact < Composites form elements of periodic table < Composites form molecules < Composites form molecules < Materials are a combination of Matter < Materials can be formed into multiDimensional shapes < Complex shapes are a combination of simpler forms < Reducing high Dimensions to lower < Further reduction < Fundamental spatial description < Node class for A* search < Interim function describing time before inclusion as Dimension < Example of harmonic motion of particles < Neuron container for other neuron components < Dendritic synaptic cleft, input to the neuron < Neuroreceptor, component of dendritic cleft < Synapse, area of stimulus transmission/reception < Potassium channel, component of the membrane < Dendrite, pre-Soma component of a neuron < Dendrite branch, division/join of dendrites < Soma, component of a neuron < Axon Hillock, component of Soma < Axon, connected to Axon Hillock < Axon branch, division/join of Axon < Axon synaptic cleft, output area of neuron < Synaptic vesicle, container of neurotransmitters < Neurotransmitter, transfer component between clefts
INVALID_SOCKET
SOCKET_ERROR
SOCKET_PORT
SOCKET_ADDRESS
DEG2RAD
Avoids having to recalculate a constant PI/180
RAD2DEG
Avoids having to recalculate a constant 180/PI
ONERAD
Avoids having to recalculate
GRAVITY
struct caer_dynapse_info dynapse_info
Referenced by ClearDynapse, main.
float g_speed
Speed of robot
float g_deltaheading
Change current angle of robot by this amount
float g_toggle
Discover or localise
Referenced by main.
bool g_buttonPressed
static std::atomic_bool globalShutdown(false)
static void globalShutdownSignalHandler(int signal)
bool msg_handling(std::vector< std::string > *m_messages, bool m_response, int m_ok, int m_fail)
References DEBUG_PROGRAM.
int CreateUniverse(std::vector< Universe > *toAddto)
int AddElementaryParticle(std::vector< ElementaryParticle > *toAddto, std::vector< Dimension > *aPartof, int arrayEntry)
int AddCompositeParticle(std::vector< CompositeParticle > *toAddto, std::vector< ElementaryParticle > *aPartof, int arrayEntry)
int AddElementaryForce(std::vector< ElementaryForce > *toAddto, std::vector< ElementaryParticle > *aPartof, int arrayEntry)
int AddCompositeForce(std::vector< CompositeForce > *toAddto, std::vector< CompositeParticle > *aPartof, int arrayEntry)
int AddLaw(std::vector< CompositeForce > *toAddto, int arrayEntry, std::vector< CompositeParticle > *toAddto2, int arrayEntry2)
int AddMatter(std::vector< Matter > *toAddto, std::vector< Dimension > *aPartof, int arrayEntry)
int AddMonomer(std::vector< Monomer > *toAddto, std::vector< Dimension > *aPartof, int arrayEntry)
int AddPolymer(std::vector< Polymer > *toAddto, std::vector< Dimension > *aPartof, int arrayEntry)
int AddSolid(std::vector< Solid > *toAddto, std::vector< Dimension > *aPartof, int arrayEntry)
int AddPoint(std::vector< Point > *toAddto, std::vector< Dimension > *aPartof, int arrayEntry)
Referenced by main.
int AddPolyhedron(std::vector< Polyhedron > *toAddto, std::vector< Solid > *aPartof, int arrayEntry)
int AddPolygon(std::vector< Polygon > *toAddto, std::vector< Polyhedron > *aPartof, int arrayEntry)
int AddQuad(std::vector< Quad > *toAddto, std::vector< Polygon > *aPartof, int arrayEntry)
int AddLine(std::vector< Line > *toAddto, std::vector< Polygon > *aPartof, int arrayEntry)
int AddNeuron(std::vector< Neuron > *toAddto, std::vector< Dimension > *aPartof, int arrayEntry)
Referenced by analyseStream, main.
int AddSpike(std::vector< Spike > *toAddto)
Referenced by main.
int AddDendrite(std::vector< Dendrite > *toAddto)
int AddSynapse(std::vector< Synapse > *toAddto, std::vector< Dimension > *aPartof, int arrayEntry)
Referenced by main.
int AddOrbital(std::vector< Orbital > *toAddto, std::vector< Dimension > *aPartof, int arrayEntry, int orbType)
Referenced by main.
int AddApptimer(std::vector< AppTimer > *toAddto)
int AddSFMLRectangle(std::vector< sf::RectangleShape > *toAddto, std::vector< Dimension > *aPartof, int arrayEntry)
Referenced by main.
int AddSFMLText(std::vector< sf::Text > *toAddto, std::vector< Dimension > *aPartof, int arrayEntry, sf::Font *font)
Referenced by main.
bool compare_swapElementaryParticle(std::vector< ElementaryParticle > *origin, int l_origin_Swap, int l_origin_Candidate1, int l_origin_Candidate2)
Referenced by main.
int distanceBetweenNodes(std::vector< Point > *nodesQuery, std::vector< int > *nodesList, int nodesDimensions, double desiredDistance)
References RAD2DEG, DEG2RAD.
bool compare_swapCompositeParticle(std::vector< CompositeParticle > *origin, int l_origin_Swap, int l_origin_Candidate1, int l_origin_Candidate2)
bool compare_swapSynapse(std::vector< Synapse > *origin, int l_origin_Swap, int l_origin_Candidate1, int l_origin_Candidate2)
bool analyseStream(std::vector< Neuron > *neuronList, std::vector< Point > *aPoint, int startPoint, int endPoint, int stepPoint, int neuralSequence, std::vector< Dimension > *dimensionList)
References AddNeuron.
void ClearDimensionSelection(std::vector< int > *dimension_list)
void SelectDimension(const int PossibleDimensions[10], std::vector< int > *dimension_list, int whichDimension)
Referenced by SelectMultiDimensions, main.
void SelectMultiDimensions(const int PossibleDimensions[10], std::vector< int > *dimension_list, int howManyDimensions)
References SelectDimension.
Referenced by main.
bool ClearDynapse(caerDeviceHandle *usb_handle)
References dynapse_info, DEFAULTBIASES.
Referenced by main.
void exitCB()
Referenced by init.
int init(int argc, const char *argv[])
References exitCB.
Referenced by main, resourcePath.
int main(int argc, const char *argv[])
References init, ClearDynapse, AddSFMLRectangle, AddSFMLText, compare_swapElementaryParticle, AddSpike, AddPoint, DEG2RAD, AddNeuron, Screen_0::creation, AddSynapse, AddOrbital, dynapse_info, LOWPOWERBIASES, SelectMultiDimensions, SelectDimension, g_toggle.